MOM6: /glade/work/altuntas/cesm.sandboxes/cesm2_2_alpha_X_mom/components/mom/MOM6/config_src/solo_driver/MOM_driver.F90 File Reference
MOM_driver.F90 File Reference
#include <MOM_memory.h>
#include "version_variable.h"
Functions/Subroutines
program mom_main
Function/Subroutine Documentation
mom_main()
program mom_main ()
Definition at line 1 of file MOM_driver.F90.
References mom_ice_shelf::add_shelf_forces(), mom_error_handler::calltree_enter(), mom_error_handler::calltree_leave(), mom_error_handler::calltree_waypoint(), mom_file_parser::close_param_file(), mom_diag_mediator::diag_mediator_close_registration(), mom_diag_mediator::diag_mediator_end(), mom_diag_mediator::disable_averaging(), mom_diag_mediator::enable_averaging(), mom::extract_surface_state(), mom::finish_mom_initialization(), mom_forcing_type::forcing_diagnostics(), mom_surface_forcing::forcing_save_restart(), mom::get_mom_state_elements(), mom_ice_shelf::ice_shelf_end(), mom_ice_shelf::ice_shelf_save_restart(), mom_ice_shelf::initialize_ice_shelf(), mom::initialize_mom(), mom_error_handler::is_root_pe(), mom_forcing_type::mech_forcing_diags(), mom::mom_end(), mom_error_handler::mom_error(), mom_forcing_type::mom_forcing_chksum(), mom_forcing_type::mom_mech_forcing_chksum(), mom_error_handler::mom_mesg(), mom::mom_state_is_synchronized(), mom_wave_interface::mom_wave_interface_init(), mom_wave_interface::mom_wave_interface_init_lite(), mom_write_cputime::mom_write_cputime_init(), mom_time_manager::real_to_time(), mom_restart::save_restart(), mom_surface_forcing::set_forcing(), mom_ice_shelf::shelf_calc_flux(), mom::step_mom(), mom::step_offline(), mom_surface_forcing::surface_forcing_init(), mom_wave_interface::update_surface_waves(), mom_string_functions::uppercase(), mom_write_cputime::write_cputime(), and mom_write_cputime::write_cputime_start_clock().