MOM6: /glade/work/altuntas/cesm.sandboxes/cesm2_2_alpha_X_mom/components/mom/MOM6/src/framework/MOM_checksums.F90 File Reference
MOM_checksums.F90 File Reference
#include "version_variable.h"
Data Types
interface mom_checksums::hchksum_pair
Checksums a pair of arrays (2d or 3d) staggered at tracer points.
interface mom_checksums::uvchksum
Checksums a pair velocity arrays (2d or 3d) staggered at C-grid locations.
interface mom_checksums::uchksum
Checksums an array (2d or 3d) staggered at C-grid u points.
interface mom_checksums::vchksum
Checksums an array (2d or 3d) staggered at C-grid v points.
interface mom_checksums::bchksum_pair
Checksums a pair of arrays (2d or 3d) staggered at corner points.
interface mom_checksums::hchksum
Checksums an array (2d or 3d) staggered at tracer points.
interface mom_checksums::bchksum
Checksums an array (2d or 3d) staggered at corner points.
interface mom_checksums::qchksum
This is an older interface that has been renamed Bchksum.
interface mom_checksums::chksum
This is an older interface for 1-, 2-, or 3-D checksums.
interface mom_checksums::chk_sum_msg
Write a message with either checksums or numerical statistics of arrays.
interface mom_checksums::is_nan
Returns .true. if any element of x is a NaN, and .false. otherwise.
Modules
module mom_checksums
Routines to calculate checksums of various array and vector types.
Functions/Subroutines
subroutine, public mom_checksums::chksum0 (scalar, mesg, scale, logunit)
Checksum a scalar field (consistent with array checksums)
subroutine, public mom_checksums::zchksum (array, mesg, scale, logunit)
Checksum a 1d array (typically a column).
integer function subchk (array, scale)
subroutine substats (array, aMean, aMin, aMax)
subroutine mom_checksums::chksum_pair_h_2d (mesg, arrayA, arrayB, HI, haloshift, omit_corners, scale, logunit)
Checksums on a pair of 2d arrays staggered at tracer points.
subroutine mom_checksums::chksum_pair_h_3d (mesg, arrayA, arrayB, HI, haloshift, omit_corners, scale, logunit)
Checksums on a pair of 3d arrays staggered at tracer points.
subroutine mom_checksums::chksum_h_2d (array, mesg, HI, haloshift, omit_corners, scale, logunit)
Checksums a 2d array staggered at tracer points.
integer function subchk (array, HI, di, dj, scale)
subroutine substats (HI, array, aMean, aMin, aMax)
subroutine mom_checksums::chksum_pair_b_2d (mesg, arrayA, arrayB, HI, haloshift, symmetric, omit_corners, scale, logunit)
Checksums on a pair of 2d arrays staggered at q-points.
subroutine mom_checksums::chksum_pair_b_3d (mesg, arrayA, arrayB, HI, haloshift, symmetric, omit_corners, scale, logunit)
Checksums on a pair of 3d arrays staggered at q-points.
subroutine mom_checksums::chksum_b_2d (array, mesg, HI, haloshift, symmetric, omit_corners, scale, logunit)
Checksums a 2d array staggered at corner points.
integer function subchk (array, HI, di, dj, scale)
subroutine substats (HI, array, sym_stats, aMean, aMin, aMax)
subroutine mom_checksums::chksum_uv_2d (mesg, arrayU, arrayV, HI, haloshift, symmetric, omit_corners, scale, logunit)
Checksums a pair of 2d velocity arrays staggered at C-grid locations.
subroutine mom_checksums::chksum_uv_3d (mesg, arrayU, arrayV, HI, haloshift, symmetric, omit_corners, scale, logunit)
Checksums a pair of 3d velocity arrays staggered at C-grid locations.
subroutine mom_checksums::chksum_u_2d (array, mesg, HI, haloshift, symmetric, omit_corners, scale, logunit)
Checksums a 2d array staggered at C-grid u points.
integer function subchk (array, HI, di, dj, scale)
subroutine substats (HI, array, sym_stats, aMean, aMin, aMax)
subroutine mom_checksums::chksum_v_2d (array, mesg, HI, haloshift, symmetric, omit_corners, scale, logunit)
Checksums a 2d array staggered at C-grid v points.
integer function subchk (array, HI, di, dj, scale)
subroutine substats (HI, array, sym_stats, aMean, aMin, aMax)
subroutine mom_checksums::chksum_h_3d (array, mesg, HI, haloshift, omit_corners, scale, logunit)
Checksums a 3d array staggered at tracer points.
integer function subchk (array, HI, di, dj, scale)
subroutine substats (HI, array, aMean, aMin, aMax)
subroutine mom_checksums::chksum_b_3d (array, mesg, HI, haloshift, symmetric, omit_corners, scale, logunit)
Checksums a 3d array staggered at corner points.
integer function subchk (array, HI, di, dj, scale)
subroutine substats (HI, array, sym_stats, aMean, aMin, aMax)
subroutine mom_checksums::chksum_u_3d (array, mesg, HI, haloshift, symmetric, omit_corners, scale, logunit)
Checksums a 3d array staggered at C-grid u points.
integer function subchk (array, HI, di, dj, scale)
subroutine substats (HI, array, sym_stats, aMean, aMin, aMax)
subroutine mom_checksums::chksum_v_3d (array, mesg, HI, haloshift, symmetric, omit_corners, scale, logunit)
Checksums a 3d array staggered at C-grid v points.
integer function subchk (array, HI, di, dj, scale)
subroutine substats (HI, array, sym_stats, aMean, aMin, aMax)
subroutine mom_checksums::chksum1d (array, mesg, start_i, end_i, compare_PEs)
chksum1d does a checksum of a 1-dimensional array.
subroutine mom_checksums::chksum2d (array, mesg)
chksum2d does a checksum of all data in a 2-d array.
subroutine mom_checksums::chksum3d (array, mesg)
chksum3d does a checksum of all data in a 2-d array.
logical function mom_checksums::is_nan_0d (x)
This function returns .true. if x is a NaN, and .false. otherwise.
logical function mom_checksums::is_nan_1d (x, skip_mpp)
Returns .true. if any element of x is a NaN, and .false. otherwise.
logical function mom_checksums::is_nan_2d (x)
Returns .true. if any element of x is a NaN, and .false. otherwise.
logical function mom_checksums::is_nan_3d (x)
Returns .true. if any element of x is a NaN, and .false. otherwise.
subroutine mom_checksums::chk_sum_msg1 (fmsg, bc0, mesg, iounit)
Write a message including the checksum of the non-shifted array.
subroutine mom_checksums::chk_sum_msg5 (fmsg, bc0, bcSW, bcSE, bcNW, bcNE, mesg, iounit)
Write a message including checksums of non-shifted and diagonally shifted arrays.
subroutine mom_checksums::chk_sum_msg_nsew (fmsg, bc0, bcN, bcS, bcE, bcW, mesg, iounit)
Write a message including checksums of non-shifted and laterally shifted arrays.
subroutine mom_checksums::chk_sum_msg_s (fmsg, bc0, bcS, mesg, iounit)
Write a message including checksums of non-shifted and southward shifted arrays.
subroutine mom_checksums::chk_sum_msg_w (fmsg, bc0, bcW, mesg, iounit)
Write a message including checksums of non-shifted and westward shifted arrays.
subroutine mom_checksums::chk_sum_msg2 (fmsg, bc0, bcSW, mesg, iounit)
Write a message including checksums of non-shifted and southwestward shifted arrays.
subroutine mom_checksums::chk_sum_msg3 (fmsg, aMean, aMin, aMax, mesg, iounit)
Write a message including the global mean, maximum and minimum of an array.
subroutine, public mom_checksums::mom_checksums_init (param_file)
MOM_checksums_init initializes the MOM_checksums module. As it happens, the only thing that it does is to log the version of this module.
subroutine mom_checksums::chksum_error (signal, message)
A wrapper for MOM_error used in the checksum code.
integer function mom_checksums::bitcount (x)
Does a bitcount of a number by first casting to an integer and then using BTEST to check bit by bit.
Variables
integer, parameter mom_checksums::bc_modulus = 1000000000
Modulus of checksum bitcount.
integer, parameter mom_checksums::default_shift =0
The default array shift.
logical mom_checksums::calculatestatistics =.true.
If true, report min, max and mean.
logical mom_checksums::writechksums =.true.
If true, report the bitcount checksum.
logical mom_checksums::checkfornans =.true.
If true, checks array for NaNs and cause FATAL error is any are found.
Function/Subroutine Documentation
subchk() [1/9]
integer function chksum_h_2d::subchk (real, dimension(hi%isd:,hi%jsd:), intent(in) array, type(hor_index_type), intent(in) HI, integer, intent(in) di, integer, intent(in) dj, real, intent(in) scale) private
Parameters
[in] hi A horizontal index type
[in] array The array to be checksummed
[in] di i- direction array shift for this checksum
[in] dj j- direction array shift for this checksum
[in] scale A scaling factor for this array.
Definition at line 335 of file MOM_checksums.F90.
     type(hor_index_type), intent(in) ::  HI     !< A horizontal index type
     real, dimension(HI%isd:,HI%jsd:), intent(in) :: array !< The array to be checksummed
     integer, intent(in) :: di    !< i- direction array shift for this checksum
     integer, intent(in) :: dj    !< j- direction array shift for this checksum
     real, intent(in)    :: scale !< A scaling factor for this array.
     integer :: i, j, bc
     subchk = 0
     do j=hi%jsc+dj,hi%jec+dj; do i=hi%isc+di,hi%iec+di
       bc = bitcount(abs(scale*array(i,j)))
       subchk = subchk + bc
     enddo ; enddo
     call sum_across_pes(subchk)
     subchk=mod(subchk, bc_modulus)
References mom_checksums::bc_modulus, mom_checksums::bitcount(), and subchk().
subchk() [2/9]
integer function chksum_b_2d::subchk (real, dimension(hi%isdb:,hi%jsdb:), intent(in) array, type(hor_index_type), intent(in) HI, integer, intent(in) di, integer, intent(in) dj, real, intent(in) scale) private
Parameters
[in] hi A horizontal index type
[in] array The array to be checksummed
[in] di i- direction array shift for this checksum
[in] dj j- direction array shift for this checksum
[in] scale A scaling factor for this array.
Definition at line 542 of file MOM_checksums.F90.
     type(hor_index_type), intent(in) ::  HI     !< A horizontal index type
     real, dimension(HI%IsdB:,HI%JsdB:), intent(in) :: array !< The array to be checksummed
     integer, intent(in) :: di    !< i- direction array shift for this checksum
     integer, intent(in) :: dj    !< j- direction array shift for this checksum
     real, intent(in)    :: scale !< A scaling factor for this array.
     integer :: i, j, bc
     subchk = 0
     ! This line deliberately uses the h-point computational domain.
     do j=hi%jsc+dj,hi%jec+dj; do i=hi%isc+di,hi%iec+di
       bc = bitcount(abs(scale*array(i,j)))
       subchk = subchk + bc
     enddo ; enddo
     call sum_across_pes(subchk)
     subchk=mod(subchk, bc_modulus)
References mom_checksums::bc_modulus, mom_checksums::bitcount(), and subchk().
subchk() [3/9]
integer function chksum_u_2d::subchk (real, dimension(hi%isdb:,hi%jsd:), intent(in) array, type(hor_index_type), intent(in) HI, integer, intent(in) di, integer, intent(in) dj, real, intent(in) scale) private
Parameters
[in] hi A horizontal index type
[in] array The array to be checksummed
[in] di i- direction array shift for this checksum
[in] dj j- direction array shift for this checksum
[in] scale A scaling factor for this array.
Definition at line 753 of file MOM_checksums.F90.
     type(hor_index_type), intent(in) ::  HI     !< A horizontal index type
     real, dimension(HI%IsdB:,HI%jsd:), intent(in) :: array !< The array to be checksummed
     integer, intent(in) :: di    !< i- direction array shift for this checksum
     integer, intent(in) :: dj    !< j- direction array shift for this checksum
     real, intent(in)    :: scale !< A scaling factor for this array.
     integer :: i, j, bc
     subchk = 0
     ! This line deliberately uses the h-point computational domain.
     do j=hi%jsc+dj,hi%jec+dj; do i=hi%isc+di,hi%iec+di
       bc = bitcount(abs(scale*array(i,j)))
       subchk = subchk + bc
     enddo ; enddo
     call sum_across_pes(subchk)
     subchk=mod(subchk, bc_modulus)
References mom_checksums::bc_modulus, mom_checksums::bitcount(), and subchk().
subchk() [4/9]
integer function chksum_v_2d::subchk (real, dimension(hi%isd:,hi%jsdb:), intent(in) array, type(hor_index_type), intent(in) HI, integer, intent(in) di, integer, intent(in) dj, real, intent(in) scale) private
Parameters
[in] hi A horizontal index type
[in] array The array to be checksummed
[in] di i- direction array shift for this checksum
[in] dj j- direction array shift for this checksum
[in] scale A scaling factor for this array.
Definition at line 907 of file MOM_checksums.F90.
     type(hor_index_type), intent(in) ::  HI     !< A horizontal index type
     real, dimension(HI%isd:,HI%JsdB:), intent(in) :: array !< The array to be checksummed
     integer, intent(in) :: di    !< i- direction array shift for this checksum
     integer, intent(in) :: dj    !< j- direction array shift for this checksum
     real, intent(in)    :: scale !< A scaling factor for this array.
     integer :: i, j, bc
     subchk = 0
     ! This line deliberately uses the h-point computational domain.
     do j=hi%jsc+dj,hi%jec+dj; do i=hi%isc+di,hi%iec+di
       bc = bitcount(abs(scale*array(i,j)))
       subchk = subchk + bc
     enddo ; enddo
     call sum_across_pes(subchk)
     subchk=mod(subchk, bc_modulus)
References mom_checksums::bc_modulus, mom_checksums::bitcount(), and subchk().
subchk() [5/9]
integer function chksum_h_3d::subchk (real, dimension(hi%isd:,hi%jsd:,:), intent(in) array, type(hor_index_type), intent(in) HI, integer, intent(in) di, integer, intent(in) dj, real, intent(in) scale) private
Parameters
[in] hi A horizontal index type
[in] array The array to be checksummed
[in] di i- direction array shift for this checksum
[in] dj j- direction array shift for this checksum
[in] scale A scaling factor for this array.
Definition at line 1043 of file MOM_checksums.F90.
     type(hor_index_type), intent(in) ::  HI     !< A horizontal index type
     real, dimension(HI%isd:,HI%jsd:,:), intent(in) :: array !< The array to be checksummed
     integer, intent(in) :: di    !< i- direction array shift for this checksum
     integer, intent(in) :: dj    !< j- direction array shift for this checksum
     real, intent(in)    :: scale !< A scaling factor for this array.
     integer :: i, j, k, bc
     subchk = 0
     do k=lbound(array,3),ubound(array,3) ; do j=hi%jsc+dj,hi%jec+dj ; do i=hi%isc+di,hi%iec+di
       bc = bitcount(abs(scale*array(i,j,k)))
       subchk = subchk + bc
     enddo ; enddo ; enddo
     call sum_across_pes(subchk)
     subchk=mod(subchk, bc_modulus)
References mom_checksums::bc_modulus, mom_checksums::bitcount(), and subchk().
subchk() [6/9]
integer function chksum_b_3d::subchk (real, dimension(hi%isdb:,hi%jsdb:,:), intent(in) array, type(hor_index_type), intent(in) HI, integer, intent(in) di, integer, intent(in) dj, real, intent(in) scale) private
Parameters
[in] hi A horizontal index type
[in] array The array to be checksummed
[in] di i- direction array shift for this checksum
[in] dj j- direction array shift for this checksum
[in] scale A scaling factor for this array.
Definition at line 1194 of file MOM_checksums.F90.
     type(hor_index_type), intent(in) ::  HI     !< A horizontal index type
     real, dimension(HI%IsdB:,HI%JsdB:,:), intent(in) :: array !< The array to be checksummed
     integer, intent(in) :: di    !< i- direction array shift for this checksum
     integer, intent(in) :: dj    !< j- direction array shift for this checksum
     real, intent(in)    :: scale !< A scaling factor for this array.
     integer :: i, j, k, bc
     subchk = 0
     ! This line deliberately uses the h-point computational domain.
     do k=lbound(array,3),ubound(array,3) ; do j=hi%jsc+dj,hi%jec+dj ; do i=hi%isc+di,hi%iec+di
       bc = bitcount(abs(scale*array(i,j,k)))
       subchk = subchk + bc
     enddo ; enddo ; enddo
     call sum_across_pes(subchk)
     subchk=mod(subchk, bc_modulus)
References mom_checksums::bc_modulus, mom_checksums::bitcount(), and subchk().
subchk() [7/9]
integer function chksum_u_3d::subchk (real, dimension(hi%isdb:,hi%jsd:,:), intent(in) array, type(hor_index_type), intent(in) HI, integer, intent(in) di, integer, intent(in) dj, real, intent(in) scale) private
Parameters
[in] hi A horizontal index type
[in] array The array to be checksummed
[in] di i- direction array shift for this checksum
[in] dj j- direction array shift for this checksum
[in] scale A scaling factor for this array.
Definition at line 1348 of file MOM_checksums.F90.
     type(hor_index_type), intent(in) ::  HI     !< A horizontal index type
     real, dimension(HI%IsdB:,HI%jsd:,:), intent(in) :: array !< The array to be checksummed
     integer, intent(in) :: di    !< i- direction array shift for this checksum
     integer, intent(in) :: dj    !< j- direction array shift for this checksum
     real, intent(in)    :: scale !< A scaling factor for this array.
     integer :: i, j, k, bc
     subchk = 0
     ! This line deliberately uses the h-point computational domain.
     do k=lbound(array,3),ubound(array,3) ; do j=hi%jsc+dj,hi%jec+dj ; do i=hi%isc+di,hi%iec+di
       bc = bitcount(abs(scale*array(i,j,k)))
       subchk = subchk + bc
     enddo ; enddo ; enddo
     call sum_across_pes(subchk)
     subchk=mod(subchk, bc_modulus)
References mom_checksums::bc_modulus, mom_checksums::bitcount(), and subchk().
subchk() [8/9]
integer function chksum_v_3d::subchk (real, dimension(hi%isd:,hi%jsdb:,:), intent(in) array, type(hor_index_type), intent(in) HI, integer, intent(in) di, integer, intent(in) dj, real, intent(in) scale) private
Parameters
[in] hi A horizontal index type
[in] array The array to be checksummed
[in] di i- direction array shift for this checksum
[in] dj j- direction array shift for this checksum
[in] scale A scaling factor for this array.
Definition at line 1502 of file MOM_checksums.F90.
     type(hor_index_type), intent(in) ::  HI     !< A horizontal index type
     real, dimension(HI%isd:,HI%JsdB:,:), intent(in) :: array !< The array to be checksummed
     integer, intent(in) :: di    !< i- direction array shift for this checksum
     integer, intent(in) :: dj    !< j- direction array shift for this checksum
     real, intent(in)    :: scale !< A scaling factor for this array.
     integer :: i, j, k, bc
     subchk = 0
     ! This line deliberately uses the h-point computational domain.
     do k=lbound(array,3),ubound(array,3) ; do j=hi%jsc+dj,hi%jec+dj ; do i=hi%isc+di,hi%iec+di
       bc = bitcount(abs(scale*array(i,j,k)))
       subchk = subchk + bc
     enddo ; enddo ; enddo
     call sum_across_pes(subchk)
     subchk=mod(subchk, bc_modulus)
References mom_checksums::bc_modulus, mom_checksums::bitcount(), and subchk().
subchk() [9/9]
integer function zchksum::subchk (real, dimension(:), intent(in) array, real, intent(in) scale) private
Parameters
[in] array The array to be checksummed
[in] scale A scaling factor for this array.
Definition at line 167 of file MOM_checksums.F90.
     real, dimension(:), intent(in) :: array !< The array to be checksummed
     real, intent(in) :: scale !< A scaling factor for this array.
     integer :: k, bc
     subchk = 0
     do k=lbound(array, 1), ubound(array, 1)
       bc = bitcount(abs(scale * array(k)))
       subchk = subchk + bc
     enddo
     subchk=mod(subchk, bc_modulus)
References mom_checksums::bc_modulus, and mom_checksums::bitcount().
Referenced by mom_checksums::chksum_b_2d(), mom_checksums::chksum_b_3d(), mom_checksums::chksum_h_2d(), mom_checksums::chksum_h_3d(), mom_checksums::chksum_u_2d(), mom_checksums::chksum_u_3d(), mom_checksums::chksum_v_2d(), mom_checksums::chksum_v_3d(), subchk(), and mom_checksums::zchksum().
substats() [1/9]
subroutine zchksum::substats (real, dimension(:), intent(in) array, real, intent(out) aMean, real, intent(out) aMin, real, intent(out) aMax) private
Parameters
[in] array The array to be checksummed
Definition at line 179 of file MOM_checksums.F90.
     real, dimension(:), intent(in) :: array !< The array to be checksummed
     real, intent(out) :: aMean, aMin, aMax
     integer :: k, n
     amin = array(1)
     amax = array(1)
     n = 0
     do k=lbound(array,1), ubound(array,1)
       amin = min(amin, array(k))
       amax = max(amax, array(k))
       n = n + 1
     enddo
     amean = sum(array(:)) / real(n)
Referenced by mom_checksums::chksum_b_2d(), mom_checksums::chksum_b_3d(), mom_checksums::chksum_h_2d(), mom_checksums::chksum_h_3d(), mom_checksums::chksum_u_2d(), mom_checksums::chksum_u_3d(), mom_checksums::chksum_v_2d(), mom_checksums::chksum_v_3d(), and mom_checksums::zchksum().
substats() [2/9]
subroutine chksum_h_2d::substats (type(hor_index_type), intent(in) HI, real, dimension(hi%isd:,hi%jsd:), intent(in) array, real, intent(out) aMean, real, intent(out) aMin, real, intent(out) aMax) private
Parameters
[in] hi A horizontal index type
[in] array The array to be checksummed
Definition at line 351 of file MOM_checksums.F90.
     type(hor_index_type), intent(in) ::  HI     !< A horizontal index type
     real, dimension(HI%isd:,HI%jsd:), intent(in) :: array !< The array to be checksummed
     real, intent(out) :: aMean, aMin, aMax
     integer :: i, j, n
     amin = array(hi%isc,hi%jsc)
     amax = array(hi%isc,hi%jsc)
     n = 0
     do j=hi%jsc,hi%jec ; do i=hi%isc,hi%iec
       amin = min(amin, array(i,j))
       amax = max(amax, array(i,j))
       n = n + 1
     enddo ; enddo
     amean = reproducing_sum(array(hi%isc:hi%iec,hi%jsc:hi%jec))
     call sum_across_pes(n)
     call min_across_pes(amin)
     call max_across_pes(amax)
     amean = amean / real(n)
substats() [3/9]
subroutine chksum_h_3d::substats (type(hor_index_type), intent(in) HI, real, dimension(hi%isd:,hi%jsd:,:), intent(in) array, real, intent(out) aMean, real, intent(out) aMin, real, intent(out) aMax) private
Parameters
[in] hi A horizontal index type
[in] array The array to be checksummed
Definition at line 1059 of file MOM_checksums.F90.
     type(hor_index_type), intent(in) ::  HI     !< A horizontal index type
     real, dimension(HI%isd:,HI%jsd:,:), intent(in) :: array !< The array to be checksummed
     real, intent(out) :: aMean, aMin, aMax
     integer :: i, j, k, n
     amin = array(hi%isc,hi%jsc,1)
     amax = array(hi%isc,hi%jsc,1)
     n = 0
     do k=lbound(array,3),ubound(array,3) ; do j=hi%jsc,hi%jec ; do i=hi%isc,hi%iec
       amin = min(amin, array(i,j,k))
       amax = max(amax, array(i,j,k))
       n = n + 1
     enddo ; enddo ; enddo
     amean = reproducing_sum(array(hi%isc:hi%iec,hi%jsc:hi%jec,:))
     call sum_across_pes(n)
     call min_across_pes(amin)
     call max_across_pes(amax)
     amean = amean / real(n)
substats() [4/9]
subroutine chksum_b_2d::substats (type(hor_index_type), intent(in) HI, real, dimension(hi%isdb:,hi%jsdb:), intent(in) array, logical, intent(in) sym_stats, real, intent(out) aMean, real, intent(out) aMin, real, intent(out) aMax) private
Parameters
[in] hi A horizontal index type
[in] array The array to be checksummed
[in] sym_stats If true, evaluate the statistics on the full symmetric computational domain.
Definition at line 559 of file MOM_checksums.F90.
     type(hor_index_type), intent(in) ::  HI     !< A horizontal index type
     real, dimension(HI%IsdB:,HI%JsdB:), intent(in) :: array !< The array to be checksummed
     logical,          intent(in) :: sym_stats !< If true, evaluate the statistics on the
                                               !! full symmetric computational domain.
     real, intent(out) :: aMean, aMin, aMax
     integer :: i, j, n, IsB, JsB
     isb = hi%isc ; if (sym_stats) isb = hi%isc-1
     jsb = hi%jsc ; if (sym_stats) jsb = hi%jsc-1
     amin = array(hi%isc,hi%jsc) ; amax = amin
     do j=jsb,hi%JecB ; do i=isb,hi%IecB
       amin = min(amin, array(i,j))
       amax = max(amax, array(i,j))
     enddo ; enddo
     ! This line deliberately uses the h-point computational domain.
     amean = reproducing_sum(array(hi%isc:hi%iec,hi%jsc:hi%jec))
     n = (1 + hi%jec - hi%jsc) * (1 + hi%iec - hi%isc)
     call sum_across_pes(n)
     call min_across_pes(amin)
     call max_across_pes(amax)
     amean = amean / real(n)
substats() [5/9]
subroutine chksum_u_2d::substats (type(hor_index_type), intent(in) HI, real, dimension(hi%isdb:,hi%jsd:), intent(in) array, logical, intent(in) sym_stats, real, intent(out) aMean, real, intent(out) aMin, real, intent(out) aMax) private
Parameters
[in] hi A horizontal index type
[in] array The array to be checksummed
[in] sym_stats If true, evaluate the statistics on the full symmetric computational domain.
Definition at line 770 of file MOM_checksums.F90.
     type(hor_index_type), intent(in) ::  HI     !< A horizontal index type
     real, dimension(HI%IsdB:,HI%jsd:), intent(in) :: array !< The array to be checksummed
     logical,          intent(in) :: sym_stats !< If true, evaluate the statistics on the
                                               !! full symmetric computational domain.
     real, intent(out) :: aMean, aMin, aMax
     integer :: i, j, n, IsB
     isb = hi%isc ; if (sym_stats) isb = hi%isc-1
     amin = array(hi%isc,hi%jsc) ; amax = amin
     do j=hi%jsc,hi%jec ; do i=isb,hi%IecB
       amin = min(amin, array(i,j))
       amax = max(amax, array(i,j))
     enddo ; enddo
     ! This line deliberately uses the h-point computational domain.
     amean = reproducing_sum(array(hi%isc:hi%iec,hi%jsc:hi%jec))
     n = (1 + hi%jec - hi%jsc) * (1 + hi%iec - hi%isc)
     call sum_across_pes(n)
     call min_across_pes(amin)
     call max_across_pes(amax)
     amean = amean / real(n)
substats() [6/9]
subroutine chksum_v_2d::substats (type(hor_index_type), intent(in) HI, real, dimension(hi%isd:,hi%jsdb:), intent(in) array, logical, intent(in) sym_stats, real, intent(out) aMean, real, intent(out) aMin, real, intent(out) aMax) private
Parameters
[in] hi A horizontal index type
[in] array The array to be checksummed
[in] sym_stats If true, evaluate the statistics on the full symmetric computational domain.
Definition at line 924 of file MOM_checksums.F90.
     type(hor_index_type), intent(in) ::  HI     !< A horizontal index type
     real, dimension(HI%isd:,HI%JsdB:), intent(in) :: array !< The array to be checksummed
     logical,          intent(in) :: sym_stats !< If true, evaluate the statistics on the
                                               !! full symmetric computational domain.
     real, intent(out) :: aMean, aMin, aMax
     integer :: i, j, n, JsB
     jsb = hi%jsc ; if (sym_stats) jsb = hi%jsc-1
     amin = array(hi%isc,hi%jsc) ; amax = amin
     do j=jsb,hi%JecB ; do i=hi%isc,hi%iec
       amin = min(amin, array(i,j))
       amax = max(amax, array(i,j))
     enddo ; enddo
     ! This line deliberately uses the h-computational domain.
     amean = reproducing_sum(array(hi%isc:hi%iec,hi%jsc:hi%jec))
     n = (1 + hi%jec - hi%jsc) * (1 + hi%iec - hi%isc)
     call sum_across_pes(n)
     call min_across_pes(amin)
     call max_across_pes(amax)
     amean = amean / real(n)
substats() [7/9]
subroutine chksum_b_3d::substats (type(hor_index_type), intent(in) HI, real, dimension(hi%isdb:,hi%jsdb:,:), intent(in) array, logical, intent(in) sym_stats, real, intent(out) aMean, real, intent(out) aMin, real, intent(out) aMax) private
Parameters
[in] hi A horizontal index type
[in] array The array to be checksummed
[in] sym_stats If true, evaluate the statistics on the full symmetric computational domain.
Definition at line 1211 of file MOM_checksums.F90.
     type(hor_index_type), intent(in) ::  HI     !< A horizontal index type
     real, dimension(HI%IsdB:,HI%JsdB:,:), intent(in) :: array !< The array to be checksummed
     logical,          intent(in) :: sym_stats !< If true, evaluate the statistics on the
                                               !! full symmetric computational domain.
     real, intent(out) :: aMean, aMin, aMax
     integer :: i, j, k, n, IsB, JsB
     isb = hi%isc ; if (sym_stats) isb = hi%isc-1
     jsb = hi%jsc ; if (sym_stats) jsb = hi%jsc-1
     amin = array(hi%isc,hi%jsc,1) ; amax = amin
     do k=lbound(array,3),ubound(array,3) ; do j=jsb,hi%JecB ; do i=isb,hi%IecB
       amin = min(amin, array(i,j,k))
       amax = max(amax, array(i,j,k))
     enddo ; enddo ; enddo
     amean = reproducing_sum(array(hi%isc:hi%iec,hi%jsc:hi%jec,:))
     n = (1 + hi%jec - hi%jsc) * (1 + hi%iec - hi%isc) * size(array,3)
     call sum_across_pes(n)
     call min_across_pes(amin)
     call max_across_pes(amax)
     amean = amean / real(n)
substats() [8/9]
subroutine chksum_u_3d::substats (type(hor_index_type), intent(in) HI, real, dimension(hi%isdb:,hi%jsd:,:), intent(in) array, logical, intent(in) sym_stats, real, intent(out) aMean, real, intent(out) aMin, real, intent(out) aMax) private
Parameters
[in] hi A horizontal index type
[in] array The array to be checksummed
[in] sym_stats If true, evaluate the statistics on the full symmetric computational domain.
Definition at line 1365 of file MOM_checksums.F90.
     type(hor_index_type), intent(in) ::  HI     !< A horizontal index type
     real, dimension(HI%IsdB:,HI%jsd:,:), intent(in) :: array !< The array to be checksummed
     logical,          intent(in) :: sym_stats !< If true, evaluate the statistics on the
                                               !! full symmetric computational domain.
     real, intent(out) :: aMean, aMin, aMax
     integer :: i, j, k, n, IsB
     isb = hi%isc ; if (sym_stats) isb = hi%isc-1
     amin = array(hi%isc,hi%jsc,1) ; amax = amin
     do k=lbound(array,3),ubound(array,3) ; do j=hi%jsc,hi%jec ; do i=isb,hi%IecB
       amin = min(amin, array(i,j,k))
       amax = max(amax, array(i,j,k))
     enddo ; enddo ; enddo
     ! This line deliberately uses the h-point computational domain.
     amean = reproducing_sum(array(hi%isc:hi%iec,hi%jsc:hi%jec,:))
     n = (1 + hi%jec - hi%jsc) * (1 + hi%iec - hi%isc) * size(array,3)
     call sum_across_pes(n)
     call min_across_pes(amin)
     call max_across_pes(amax)
     amean = amean / real(n)
substats() [9/9]
subroutine chksum_v_3d::substats (type(hor_index_type), intent(in) HI, real, dimension(hi%isd:,hi%jsdb:,:), intent(in) array, logical, intent(in) sym_stats, real, intent(out) aMean, real, intent(out) aMin, real, intent(out) aMax) private
Parameters
[in] hi A horizontal index type
[in] array The array to be checksummed
[in] sym_stats If true, evaluate the statistics on the full symmetric computational domain.
[out] amax Mean/min/max of array over domain
Definition at line 1520 of file MOM_checksums.F90.
     type(hor_index_type), intent(in) ::  HI     !< A horizontal index type
     real, dimension(HI%isd:,HI%JsdB:,:), intent(in) :: array !< The array to be checksummed
     logical,          intent(in) :: sym_stats !< If true, evaluate the statistics on the
                                               !! full symmetric computational domain.
     real, intent(out) :: aMean, aMin, aMax    !< Mean/min/max of array over domain
     integer :: i, j, k, n, JsB
     jsb = hi%jsc ; if (sym_stats) jsb = hi%jsc-1
     amin = array(hi%isc,hi%jsc,1) ; amax = amin
     do k=lbound(array,3),ubound(array,3) ; do j=jsb,hi%JecB ; do i=hi%isc,hi%iec
       amin = min(amin, array(i,j,k))
       amax = max(amax, array(i,j,k))
     enddo ; enddo ; enddo
     ! This line deliberately uses the h-point computational domain.
     amean = reproducing_sum(array(hi%isc:hi%iec,hi%jsc:hi%jec,:))
     n = (1 + hi%jec - hi%jsc) * (1 + hi%iec - hi%isc) * size(array,3)
     call sum_across_pes(n)
     call min_across_pes(amin)
     call max_across_pes(amax)
     amean = amean / real(n)