MOM6: dyed_obc_tracer Module Reference
dyed_obc_tracer Module Reference
Detailed Description
This tracer package dyes flow through open boundaries.
By Kate Hedstrom, 2017, copied from DOME tracers and also dye_example.
This file contains an example of the code that is needed to set up and use a set of dynamically passive tracers. These tracers dye the inflowing water, one per open boundary segment.
A single subroutine is called from within each file to register each of the tracers for reinitialization and advection and to register the subroutine that initializes the tracers and set up their output and the subroutine that does any tracer physics or chemistry along with diapycnal mixing (included here because some tracers may float or swim vertically or dye diapycnal processes).
Data Types
type dyed_obc_tracer_cs
The control structure for the dyed_obc tracer package.
Functions/Subroutines
logical function, public register_dyed_obc_tracer (HI, GV, param_file, CS, tr_Reg, restart_CS)
Register tracer fields and subroutines to be used with MOM.
subroutine, public initialize_dyed_obc_tracer (restart, day, G, GV, h, diag, OBC, CS)
Initializes the CSntr tracer fields in tr(:,:,:,:) and sets up the tracer output.
subroutine, public dyed_obc_tracer_column_physics (h_old, h_new, ea, eb, fluxes, dt, G, GV, US, CS, evap_CFL_limit, minimum_forcing_depth)
This subroutine applies diapycnal diffusion and any other column tracer physics or chemistry to the tracers from this file. This is a simple example of a set of advected passive tracers.
subroutine, public dyed_obc_tracer_end (CS)
Clean up memory allocations, if any.
Function/Subroutine Documentation
dyed_obc_tracer_column_physics()
subroutine, public dyed_obc_tracer::dyed_obc_tracer_column_physics (real, dimension(g %isd: g %ied, g %jsd: g %jed, g %ke), intent(in) h_old, real, dimension(g %isd: g %ied, g %jsd: g %jed, g %ke), intent(in) h_new, real, dimension(g %isd: g %ied, g %jsd: g %jed, g %ke), intent(in) ea, real, dimension(g %isd: g %ied, g %jsd: g %jed, g %ke), intent(in) eb, type(forcing), intent(in) fluxes, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, type(unit_scale_type), intent(in) US, type(dyed_obc_tracer_cs), pointer CS, real, intent(in), optional evap_CFL_limit, real, intent(in), optional minimum_forcing_depth)
This subroutine applies diapycnal diffusion and any other column tracer physics or chemistry to the tracers from this file. This is a simple example of a set of advected passive tracers.
The arguments to this subroutine are redundant in that h_new(k) = h_old(k) + ea(k) - eb(k-1) + eb(k) - ea(k+1)
Parameters
[in] g The ocean's grid structure
[in] gv The ocean's vertical grid structure
[in] h_old Layer thickness before entrainment [H ~> m or kg m-2].
[in] h_new Layer thickness after entrainment [H ~> m or kg m-2].
[in] ea an array to which the amount of fluid entrained
[in] eb an array to which the amount of fluid entrained
[in] fluxes A structure containing pointers to thermodynamic and tracer forcing fields. Unused fields have NULL ptrs.
[in] dt The amount of time covered by this call [T ~> s]
[in] us A dimensional unit scaling type
cs The control structure returned by a previous call to dyed_obc_register_tracer.
[in] evap_cfl_limit Limit on the fraction of the water that can be fluxed out of the top layer in a timestep [nondim]
[in] minimum_forcing_depth The smallest depth over which fluxes can be applied [H ~> m or kg m-2]
Definition at line 205 of file dyed_obc_tracer.F90.
   type(ocean_grid_type),   intent(in) :: G    !< The ocean's grid structure
   type(verticalGrid_type), intent(in) :: GV   !< The ocean's vertical grid structure
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)), &
                            intent(in) :: h_old !< Layer thickness before entrainment [H ~> m or kg m-2].
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)), &
                            intent(in) :: h_new !< Layer thickness after entrainment [H ~> m or kg m-2].
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)), &
                            intent(in) :: ea   !< an array to which the amount of fluid entrained
                                               !! from the layer above during this call will be
                                               !! added [H ~> m or kg m-2].
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)), &
                            intent(in) :: eb   !< an array to which the amount of fluid entrained
                                               !! from the layer below during this call will be
                                               !! added [H ~> m or kg m-2].
   type(forcing),           intent(in) :: fluxes !< A structure containing pointers to thermodynamic
                                               !! and tracer forcing fields.  Unused fields have NULL ptrs.
   real,                    intent(in) :: dt   !< The amount of time covered by this call [T ~> s]
   type(unit_scale_type),   intent(in) :: US   !< A dimensional unit scaling type
   type(dyed_obc_tracer_CS), pointer   :: CS   !< The control structure returned by a previous
                                               !! call to dyed_obc_register_tracer.
   real,          optional, intent(in) :: evap_CFL_limit !< Limit on the fraction of the water that can
                                               !! be fluxed out of the top layer in a timestep [nondim]
   real,          optional, intent(in) :: minimum_forcing_depth !< The smallest depth over which
                                               !! fluxes can be applied [H ~> m or kg m-2]
 ! Local variables
   real :: b1(SZI_(G))          ! b1 and c1 are variables used by the
   real :: c1(SZI_(G),SZK_(G))  ! tridiagonal solver.
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)) :: h_work ! Used so that h can be modified
   integer :: i, j, k, is, ie, js, je, nz, m
   is = g%isc ; ie = g%iec ; js = g%jsc ; je = g%jec ; nz = gv%ke
   if (.not.associated(cs)) return
   if (cs%ntr < 1) return
   if (present(evap_cfl_limit) .and. present(minimum_forcing_depth)) then
     do m=1,cs%ntr
       do k=1,nz ;do j=js,je ; do i=is,ie
         h_work(i,j,k) = h_old(i,j,k)
       enddo ; enddo ; enddo
       call applytracerboundaryfluxesinout(g, gv, cs%tr(:,:,:,m), dt, fluxes, h_work, &
                                           evap_cfl_limit, minimum_forcing_depth)
       if (nz > 1) call tracer_vertdiff(h_work, ea, eb, dt, cs%tr(:,:,:,m), g, gv)
     enddo
   else
     do m=1,cs%ntr
       if (nz > 1) call tracer_vertdiff(h_old, ea, eb, dt, cs%tr(:,:,:,m), g, gv)
     enddo
   endif
References mom_tracer_diabatic::applytracerboundaryfluxesinout(), and mom_tracer_diabatic::tracer_vertdiff().
dyed_obc_tracer_end()
subroutine, public dyed_obc_tracer::dyed_obc_tracer_end (type(dyed_obc_tracer_cs), pointer CS)
Clean up memory allocations, if any.
Parameters
cs The control structure returned by a previous call to dyed_obc_register_tracer.
Definition at line 259 of file dyed_obc_tracer.F90.
   type(dyed_obc_tracer_CS), pointer :: CS   !< The control structure returned by a previous
                                             !! call to dyed_obc_register_tracer.
   integer :: m
   if (associated(cs)) then
     if (associated(cs%tr)) deallocate(cs%tr)
     deallocate(cs)
   endif
initialize_dyed_obc_tracer()
subroutine, public dyed_obc_tracer::initialize_dyed_obc_tracer (logical, intent(in) restart, type(time_type), intent(in), target day, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, real, dimension(szi_(g),szj_(g),szk_(g)), intent(in) h, type(diag_ctrl), intent(in), target diag, type(ocean_obc_type), pointer OBC, type(dyed_obc_tracer_cs), pointer CS)
Initializes the CSntr tracer fields in tr(:,:,:,:) and sets up the tracer output.
Parameters
[in] g The ocean's grid structure
[in] gv The ocean's vertical grid structure
[in] restart .true. if the fields have already been read from a restart file.
[in] day Time of the start of the run.
[in] h Layer thicknesses [H ~> m or kg m-2]
[in] diag Structure used to regulate diagnostic output.
obc Structure specifying open boundary options.
cs The control structure returned by a previous call to dyed_obc_register_tracer.
Definition at line 136 of file dyed_obc_tracer.F90.
   type(ocean_grid_type),                 intent(in) :: G    !< The ocean's grid structure
   type(verticalGrid_type),               intent(in) :: GV   !< The ocean's vertical grid structure
   logical,                               intent(in) :: restart !< .true. if the fields have already
                                                                !! been read from a restart file.
   type(time_type), target,               intent(in) :: day     !< Time of the start of the run.
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)), intent(in) :: h    !< Layer thicknesses [H ~> m or kg m-2]
   type(diag_ctrl), target,               intent(in) :: diag    !< Structure used to regulate diagnostic output.
   type(ocean_OBC_type),                  pointer    :: OBC     !< Structure specifying open boundary options.
   type(dyed_obc_tracer_CS),              pointer    :: CS      !< The control structure returned by a previous
                                                                !! call to dyed_obc_register_tracer.
 ! Local variables
   real, allocatable :: temp(:,:,:)
   real, pointer, dimension(:,:,:) :: &
     OBC_tr1_u => null(), & ! These arrays should be allocated and set to
     obc_tr1_v => null()    ! specify the values of tracer 1 that should come
                            ! in through u- and v- points through the open
                            ! boundary conditions, in the same units as tr.
   character(len=24) :: name     ! A variable's name in a NetCDF file.
   character(len=72) :: longname ! The long name of that variable.
   character(len=48) :: units    ! The dimensions of the variable.
   character(len=48) :: flux_units ! The units for tracer fluxes, usually
                             ! kg(tracer) kg(water)-1 m3 s-1 or kg(tracer) s-1.
   real, pointer :: tr_ptr(:,:,:) => null()
   real :: h_neglect         ! A thickness that is so small it is usually lost
                             ! in roundoff and can be neglected [H ~> m or kg m-2].
   real :: e(SZK_(G)+1), e_top, e_bot, d_tr
   integer :: i, j, k, is, ie, js, je, isd, ied, jsd, jed, nz, m
   integer :: IsdB, IedB, JsdB, JedB
   if (.not.associated(cs)) return
   if (cs%ntr < 1) return
   is = g%isc ; ie = g%iec ; js = g%jsc ; je = g%jec ; nz = gv%ke
   isd = g%isd ; ied = g%ied ; jsd = g%jsd ; jed = g%jed
   isdb = g%IsdB ; iedb = g%IedB ; jsdb = g%JsdB ; jedb = g%JedB
   h_neglect = gv%H_subroundoff
   cs%Time => day
   cs%diag => diag
   if (.not.restart) then
     if (len_trim(cs%tracer_IC_file) >= 1) then
       !  Read the tracer concentrations from a netcdf file.
       if (.not.file_exists(cs%tracer_IC_file, g%Domain)) &
         call mom_error(fatal, "dyed_obc_initialize_tracer: Unable to open "// &
                         cs%tracer_IC_file)
       do m=1,cs%ntr
         call query_vardesc(cs%tr_desc(m), name, caller="initialize_dyed_obc_tracer")
         call mom_read_data(cs%tracer_IC_file, trim(name), cs%tr(:,:,:,m), g%Domain)
       enddo
     else
       do m=1,cs%ntr
         do k=1,nz ; do j=js,je ; do i=is,ie
           cs%tr(i,j,k,m) = 0.0
         enddo ; enddo ; enddo
       enddo
     endif
   endif ! restart
References mom_error_handler::mom_error(), and mom_io::query_vardesc().
register_dyed_obc_tracer()
logical function, public dyed_obc_tracer::register_dyed_obc_tracer (type(hor_index_type), intent(in) HI, type(verticalgrid_type), intent(in) GV, type(param_file_type), intent(in) param_file, type(dyed_obc_tracer_cs), pointer CS, type(tracer_registry_type), pointer tr_Reg, type(mom_restart_cs), pointer restart_CS)
Register tracer fields and subroutines to be used with MOM.
Parameters
[in] hi A horizontal index type structure.
[in] gv The ocean's vertical grid structure
[in] param_file A structure to parse for run-time parameters
cs A pointer that is set to point to the control structure for this module
tr_reg A pointer to the tracer registry.
restart_cs A pointer to the restart control structure.
Definition at line 55 of file dyed_obc_tracer.F90.
   type(hor_index_type),       intent(in) :: HI   !< A horizontal index type structure.
   type(verticalGrid_type),    intent(in) :: GV   !< The ocean's vertical grid structure
   type(param_file_type),      intent(in) :: param_file !< A structure to parse for run-time parameters
   type(dyed_obc_tracer_CS),   pointer    :: CS   !< A pointer that is set to point to the
                                                  !! control structure for this module
   type(tracer_registry_type), pointer    :: tr_Reg !< A pointer to the tracer registry.
   type(MOM_restart_CS),       pointer    :: restart_CS !< A pointer to the restart control structure.
 ! Local variables
   character(len=80)  :: name, longname
 ! This include declares and sets the variable "version".
 #include "version_variable.h"
   character(len=40)  :: mdl = "dyed_obc_tracer" ! This module's name.
   character(len=200) :: inputdir
   character(len=48)  :: flux_units ! The units for tracer fluxes, usually
                             ! kg(tracer) kg(water)-1 m3 s-1 or kg(tracer) s-1.
   real, pointer :: tr_ptr(:,:,:) => null()
   logical :: register_dyed_obc_tracer
   integer :: isd, ied, jsd, jed, nz, m
   isd = hi%isd ; ied = hi%ied ; jsd = hi%jsd ; jed = hi%jed ; nz = gv%ke
   if (associated(cs)) then
     call mom_error(warning, "dyed_obc_register_tracer called with an "// &
                             "associated control structure.")
     return
   endif
   allocate(cs)
   ! Read all relevant parameters and write them to the model log.
   call log_version(param_file, mdl, version, "")
   call get_param(param_file, mdl, "NUM_DYE_TRACERS", cs%ntr, &
                  "The number of dye tracers in this run. Each tracer "//&
                  "should have a separate boundary segment.", default=0)
   allocate(cs%ind_tr(cs%ntr))
   allocate(cs%tr_desc(cs%ntr))
   call get_param(param_file, mdl, "dyed_obc_TRACER_IC_FILE", cs%tracer_IC_file, &
                  "The name of a file from which to read the initial "//&
                  "conditions for the dyed_obc tracers, or blank to initialize "//&
                  "them internally.", default=" ")
   if (len_trim(cs%tracer_IC_file) >= 1) then
     call get_param(param_file, mdl, "INPUTDIR", inputdir, default=".")
     inputdir = slasher(inputdir)
     cs%tracer_IC_file = trim(inputdir)//trim(cs%tracer_IC_file)
     call log_param(param_file, mdl, "INPUTDIR/dyed_obc_TRACER_IC_FILE", &
                    cs%tracer_IC_file)
   endif
   allocate(cs%tr(isd:ied,jsd:jed,nz,cs%ntr)) ; cs%tr(:,:,:,:) = 0.0
   do m=1,cs%ntr
     write(name,'("dye_",I2.2)') m
     write(longname,'("Concentration of dyed_obc Tracer ",I2.2)') m
     cs%tr_desc(m) = var_desc(name, units="kg kg-1", longname=longname, caller=mdl)
     if (gv%Boussinesq) then ; flux_units = "kg kg-1 m3 s-1"
     else ; flux_units = "kg s-1" ; endif
     ! This is needed to force the compiler not to do a copy in the registration
     ! calls.  Curses on the designers and implementers of Fortran90.
     tr_ptr => cs%tr(:,:,:,m)
     ! Register the tracer for horizontal advection, diffusion, and restarts.
     call register_tracer(tr_ptr, tr_reg, param_file, hi, gv, &
                          name=name, longname=longname, units="kg kg-1", &
                          registry_diags=.true., flux_units=flux_units, &
                          restart_cs=restart_cs)
     !   Set coupled_tracers to be true (hard-coded above) to provide the surface
     ! values to the coupler (if any).  This is meta-code and its arguments will
     ! currently (deliberately) give fatal errors if it is used.
     if (cs%coupled_tracers) &
       cs%ind_tr(m) = aof_set_coupler_flux(trim(name)//'_flux', &
           flux_type=' ', implementation=' ', caller="register_dyed_obc_tracer")
   enddo
   cs%tr_Reg => tr_reg
   cs%restart_CSp => restart_cs
   register_dyed_obc_tracer = .true.
References atmos_ocean_fluxes_mod::aof_set_coupler_flux(), mom_error_handler::mom_error(), mom_tracer_registry::register_tracer(), and mom_io::var_desc().