MOM6: mom_variables Module Reference
mom_variables Module Reference
Detailed Description
Provides transparent structures with groups of MOM6 variables and supporting routines.
Data Types
type accel_diag_ptrs
Pointers to arrays with accelerations, which can later be used for derived diagnostics, like energy balances.
type bt_cont_type
Container for information about the summed layer transports and how they will vary as the barotropic velocity is changed.
type cont_diag_ptrs
Pointers to arrays with transports, which can later be used for derived diagnostics, like energy balances.
type ocean_internal_state
Pointers to all of the prognostic variables allocated in MOM_variables.F90 and MOM.F90.
type p2d
A structure for creating arrays of pointers to 2D arrays.
type p3d
A structure for creating arrays of pointers to 3D arrays.
type surface
Pointers to various fields which may be used describe the surface state of MOM, and which will be returned to a the calling program.
type thermo_var_ptrs
Pointers to an assortment of thermodynamic fields that may be available, including potential temperature, salinity, heat capacity, and the equation of state control structure.
type vertvisc_type
Vertical viscosities, drag coefficients, and related fields.
Functions/Subroutines
subroutine, public allocate_surface_state (sfc_state, G, use_temperature, do_integrals, gas_fields_ocn, use_meltpot, use_iceshelves)
Allocates the fields for the surface (return) properties of the ocean model. Unused fields are unallocated.
subroutine, public deallocate_surface_state (sfc_state)
Deallocates the elements of a surface state type.
subroutine, public alloc_bt_cont_type (BT_cont, G, alloc_faces)
Allocates the arrays contained within a BT_cont_type and initializes them to 0.
subroutine, public dealloc_bt_cont_type (BT_cont)
Deallocates the arrays contained within a BT_cont_type.
subroutine, public mom_thermovar_chksum (mesg, tv, G)
Diagnostic checksums on various elements of a thermo_var_ptrs type for debugging.
Function/Subroutine Documentation
alloc_bt_cont_type()
subroutine, public mom_variables::alloc_bt_cont_type (type(bt_cont_type), pointer BT_cont, type(ocean_grid_type), intent(in) G, logical, intent(in), optional alloc_faces)
Allocates the arrays contained within a BT_cont_type and initializes them to 0.
Parameters
bt_cont The BT_cont_type whose elements will be allocated
[in] g The ocean's grid structure
[in] alloc_faces If present and true, allocate memory for effective face thicknesses.
Definition at line 395 of file MOM_variables.F90.
   type(BT_cont_type),    pointer    :: BT_cont !< The BT_cont_type whose elements will be allocated
   type(ocean_grid_type), intent(in) :: G    !< The ocean's grid structure
   logical,     optional, intent(in) :: alloc_faces !< If present and true, allocate
                                             !! memory for effective face thicknesses.
   integer :: isd, ied, jsd, jed, IsdB, IedB, JsdB, JedB
   isd = g%isd ; ied = g%ied ; jsd = g%jsd ; jed = g%jed
   isdb = g%IsdB ; iedb = g%IedB ; jsdb = g%JsdB ; jedb = g%JedB
   if (associated(bt_cont)) call mom_error(fatal, &
     "alloc_BT_cont_type called with an associated BT_cont_type pointer.")
   allocate(bt_cont)
   allocate(bt_cont%FA_u_WW(isdb:iedb,jsd:jed)) ; bt_cont%FA_u_WW(:,:) = 0.0
   allocate(bt_cont%FA_u_W0(isdb:iedb,jsd:jed)) ; bt_cont%FA_u_W0(:,:) = 0.0
   allocate(bt_cont%FA_u_E0(isdb:iedb,jsd:jed)) ; bt_cont%FA_u_E0(:,:) = 0.0
   allocate(bt_cont%FA_u_EE(isdb:iedb,jsd:jed)) ; bt_cont%FA_u_EE(:,:) = 0.0
   allocate(bt_cont%uBT_WW(isdb:iedb,jsd:jed))  ; bt_cont%uBT_WW(:,:) = 0.0
   allocate(bt_cont%uBT_EE(isdb:iedb,jsd:jed))  ; bt_cont%uBT_EE(:,:) = 0.0
   allocate(bt_cont%FA_v_SS(isd:ied,jsdb:jedb)) ; bt_cont%FA_v_SS(:,:) = 0.0
   allocate(bt_cont%FA_v_S0(isd:ied,jsdb:jedb)) ; bt_cont%FA_v_S0(:,:) = 0.0
   allocate(bt_cont%FA_v_N0(isd:ied,jsdb:jedb)) ; bt_cont%FA_v_N0(:,:) = 0.0
   allocate(bt_cont%FA_v_NN(isd:ied,jsdb:jedb)) ; bt_cont%FA_v_NN(:,:) = 0.0
   allocate(bt_cont%vBT_SS(isd:ied,jsdb:jedb))  ; bt_cont%vBT_SS(:,:) = 0.0
   allocate(bt_cont%vBT_NN(isd:ied,jsdb:jedb))  ; bt_cont%vBT_NN(:,:) = 0.0
   if (present(alloc_faces)) then ; if (alloc_faces) then
     allocate(bt_cont%h_u(isdb:iedb,jsd:jed,1:g%ke)) ; bt_cont%h_u(:,:,:) = 0.0
     allocate(bt_cont%h_v(isd:ied,jsdb:jedb,1:g%ke)) ; bt_cont%h_v(:,:,:) = 0.0
   endif ; endif
References mom_error_handler::mom_error().
Referenced by mom_barotropic::barotropic_init().
allocate_surface_state()
subroutine, public mom_variables::allocate_surface_state (type(surface), intent(inout) sfc_state, type(ocean_grid_type), intent(in) G, logical, intent(in), optional use_temperature, logical, intent(in), optional do_integrals, type(coupler_1d_bc_type), intent(in), optional gas_fields_ocn, logical, intent(in), optional use_meltpot, logical, intent(in), optional use_iceshelves)
Allocates the fields for the surface (return) properties of the ocean model. Unused fields are unallocated.
Parameters
[in] g ocean grid structure
[in,out] sfc_state ocean surface state type to be allocated.
[in] use_temperature If true, allocate the space for thermodynamic variables.
[in] do_integrals If true, allocate the space for vertically integrated fields.
[in] gas_fields_ocn If present, this type describes the ocean
[in] use_meltpot If true, allocate the space for melt potential
[in] use_iceshelves If true, allocate the space for the stresses under ice shelves.
Definition at line 297 of file MOM_variables.F90.
   type(ocean_grid_type), intent(in)    :: G                !< ocean grid structure
   type(surface),         intent(inout) :: sfc_state        !< ocean surface state type to be allocated.
   logical,     optional, intent(in)    :: use_temperature  !< If true, allocate the space for thermodynamic variables.
   logical,     optional, intent(in)    :: do_integrals     !< If true, allocate the space for vertically
                                                            !! integrated fields.
   type(coupler_1d_bc_type), &
                optional, intent(in)    :: gas_fields_ocn  !< If present, this type describes the ocean
                                               !! ocean and surface-ice fields that will participate
                                               !! in the calculation of additional gas or other
                                               !! tracer fluxes, and can be used to spawn related
                                               !! internal variables in the ice model.
   logical,     optional, intent(in)    :: use_meltpot      !< If true, allocate the space for melt potential
   logical,     optional, intent(in)    :: use_iceshelves   !< If true, allocate the space for the stresses
                                                            !! under ice shelves.
   ! local variables
   logical :: use_temp, alloc_integ, use_melt_potential, alloc_iceshelves
   integer :: is, ie, js, je, isd, ied, jsd, jed
   integer :: isdB, iedB, jsdB, jedB
   is  = g%isc ; ie  = g%iec ; js  = g%jsc ; je  = g%jec
   isd = g%isd ; ied = g%ied ; jsd = g%jsd ; jed = g%jed
   isdb = g%isdB ; iedb = g%iedB; jsdb = g%jsdB ; jedb = g%jedB
   use_temp = .true. ; if (present(use_temperature)) use_temp = use_temperature
   alloc_integ = .true. ; if (present(do_integrals)) alloc_integ = do_integrals
   use_melt_potential = .false. ; if (present(use_meltpot)) use_melt_potential = use_meltpot
   alloc_iceshelves = .false. ; if (present(use_iceshelves)) alloc_iceshelves = use_iceshelves
   if (sfc_state%arrays_allocated) return
   if (use_temp) then
     allocate(sfc_state%SST(isd:ied,jsd:jed)) ; sfc_state%SST(:,:) = 0.0
     allocate(sfc_state%SSS(isd:ied,jsd:jed)) ; sfc_state%SSS(:,:) = 0.0
   else
     allocate(sfc_state%sfc_density(isd:ied,jsd:jed)) ; sfc_state%sfc_density(:,:) = 0.0
   endif
   allocate(sfc_state%sea_lev(isd:ied,jsd:jed)) ; sfc_state%sea_lev(:,:) = 0.0
   allocate(sfc_state%Hml(isd:ied,jsd:jed)) ; sfc_state%Hml(:,:) = 0.0
   allocate(sfc_state%u(isdb:iedb,jsd:jed)) ; sfc_state%u(:,:) = 0.0
   allocate(sfc_state%v(isd:ied,jsdb:jedb)) ; sfc_state%v(:,:) = 0.0
   if (use_melt_potential) then
     allocate(sfc_state%melt_potential(isd:ied,jsd:jed)) ; sfc_state%melt_potential(:,:) = 0.0
   endif
   if (alloc_integ) then
     ! Allocate structures for the vertically integrated ocean_mass, ocean_heat, and ocean_salt.
     allocate(sfc_state%ocean_mass(isd:ied,jsd:jed)) ; sfc_state%ocean_mass(:,:) = 0.0
     if (use_temp) then
       allocate(sfc_state%ocean_heat(isd:ied,jsd:jed)) ; sfc_state%ocean_heat(:,:) = 0.0
       allocate(sfc_state%ocean_salt(isd:ied,jsd:jed)) ; sfc_state%ocean_salt(:,:) = 0.0
       allocate(sfc_state%TempxPmE(isd:ied,jsd:jed))   ; sfc_state%TempxPmE(:,:) = 0.0
       allocate(sfc_state%salt_deficit(isd:ied,jsd:jed))  ; sfc_state%salt_deficit(:,:) = 0.0
       allocate(sfc_state%internal_heat(isd:ied,jsd:jed)) ; sfc_state%internal_heat(:,:) = 0.0
     endif
   endif
   if (alloc_iceshelves) then
     allocate(sfc_state%taux_shelf(isdb:iedb,jsd:jed)) ; sfc_state%taux_shelf(:,:) = 0.0
     allocate(sfc_state%tauy_shelf(isd:ied,jsdb:jedb)) ; sfc_state%tauy_shelf(:,:) = 0.0
   endif
   if (present(gas_fields_ocn)) &
     call coupler_type_spawn(gas_fields_ocn, sfc_state%tr_fields, &
                             (/is,is,ie,ie/), (/js,js,je,je/), as_needed=.true.)
   sfc_state%arrays_allocated = .true.
dealloc_bt_cont_type()
subroutine, public mom_variables::dealloc_bt_cont_type (type(bt_cont_type), pointer BT_cont)
Deallocates the arrays contained within a BT_cont_type.
Parameters
bt_cont The BT_cont_type whose elements will be deallocated.
Definition at line 431 of file MOM_variables.F90.
   type(BT_cont_type), pointer :: BT_cont !< The BT_cont_type whose elements will be deallocated.
   if (.not.associated(bt_cont)) return
   deallocate(bt_cont%FA_u_WW) ; deallocate(bt_cont%FA_u_W0)
   deallocate(bt_cont%FA_u_E0) ; deallocate(bt_cont%FA_u_EE)
   deallocate(bt_cont%uBT_WW)  ; deallocate(bt_cont%uBT_EE)
   deallocate(bt_cont%FA_v_SS) ; deallocate(bt_cont%FA_v_S0)
   deallocate(bt_cont%FA_v_N0) ; deallocate(bt_cont%FA_v_NN)
   deallocate(bt_cont%vBT_SS)  ; deallocate(bt_cont%vBT_NN)
   if (allocated(bt_cont%h_u)) deallocate(bt_cont%h_u)
   if (allocated(bt_cont%h_v)) deallocate(bt_cont%h_v)
   deallocate(bt_cont)
deallocate_surface_state()
subroutine, public mom_variables::deallocate_surface_state (type(surface), intent(inout) sfc_state)
Deallocates the elements of a surface state type.
Parameters
[in,out] sfc_state ocean surface state type to be deallocated here.
Definition at line 370 of file MOM_variables.F90.
   type(surface), intent(inout) :: sfc_state !< ocean surface state type to be deallocated here.
   if (.not.sfc_state%arrays_allocated) return
   if (allocated(sfc_state%melt_potential)) deallocate(sfc_state%melt_potential)
   if (allocated(sfc_state%SST)) deallocate(sfc_state%SST)
   if (allocated(sfc_state%SSS)) deallocate(sfc_state%SSS)
   if (allocated(sfc_state%sfc_density)) deallocate(sfc_state%sfc_density)
   if (allocated(sfc_state%sea_lev)) deallocate(sfc_state%sea_lev)
   if (allocated(sfc_state%Hml)) deallocate(sfc_state%Hml)
   if (allocated(sfc_state%u)) deallocate(sfc_state%u)
   if (allocated(sfc_state%v)) deallocate(sfc_state%v)
   if (allocated(sfc_state%ocean_mass)) deallocate(sfc_state%ocean_mass)
   if (allocated(sfc_state%ocean_heat)) deallocate(sfc_state%ocean_heat)
   if (allocated(sfc_state%ocean_salt)) deallocate(sfc_state%ocean_salt)
   if (allocated(sfc_state%salt_deficit)) deallocate(sfc_state%salt_deficit)
   call coupler_type_destructor(sfc_state%tr_fields)
   sfc_state%arrays_allocated = .false.
mom_thermovar_chksum()
subroutine, public mom_variables::mom_thermovar_chksum (character(len=*), intent(in) mesg, type(thermo_var_ptrs), intent(in) tv, type(ocean_grid_type), intent(in) G)
Diagnostic checksums on various elements of a thermo_var_ptrs type for debugging.
Parameters
[in] mesg A message that appears in the checksum lines
[in] tv A structure pointing to various thermodynamic variables
[in] g The ocean's grid structure
Definition at line 452 of file MOM_variables.F90.
   character(len=*),      intent(in) :: mesg !< A message that appears in the checksum lines
   type(thermo_var_ptrs), intent(in) :: tv   !< A structure pointing to various thermodynamic variables
   type(ocean_grid_type), intent(in) :: G    !< The ocean's grid structure
   ! Note that for the chksum calls to be useful for reproducing across PE
   ! counts, there must be no redundant points, so all variables use is..ie
   ! and js...je as their extent.
   if (associated(tv%T)) &
     call hchksum(tv%T, mesg//" tv%T", g%HI)
   if (associated(tv%S)) &
     call hchksum(tv%S, mesg//" tv%S", g%HI)
   if (associated(tv%frazil)) &
     call hchksum(tv%frazil, mesg//" tv%frazil", g%HI)
   if (associated(tv%salt_deficit)) &
     call hchksum(tv%salt_deficit, mesg//" tv%salt_deficit", g%HI, scale=g%US%R_to_kg_m3*g%US%Z_to_m)
   if (associated(tv%TempxPmE)) &
     call hchksum(tv%TempxPmE, mesg//" tv%TempxPmE", g%HI, scale=g%US%R_to_kg_m3*g%US%Z_to_m)
Referenced by mom_diabatic_driver::diabatic_ale(), mom_diabatic_driver::diabatic_ale_legacy(), and mom_diabatic_driver::layered_diabatic().