MOM6: mom_cap_mod Module Reference
mom_cap_mod Module Reference
Detailed Description
This module contains a set of subroutines that are required by NUOPC.
Data Types
type fld_list_type
Contains field information.
type ocean_internalstate_type
Internal state type with pointers to three types defined by MOM.
type ocean_internalstate_wrapper
Wrapper-derived type required to associate an internal state instance with the ESMF/NUOPC component.
Functions/Subroutines
subroutine, public setservices (gcomp, rc)
NUOPC SetService method is the only public entry point. SetServices registers all of the user-provided subroutines in the module with the NUOPC layer.
subroutine initializep0 (gcomp, importState, exportState, clock, rc)
First initialize subroutine called by NUOPC. The purpose is to set which version of the Initialize Phase Definition (IPD) to use.
subroutine initializeadvertise (gcomp, importState, exportState, clock, rc)
Called by NUOPC to advertise import and export fields. "Advertise" simply means that the standard names of all import and export fields are supplied. The NUOPC layer uses these to match fields between components in the coupled system.
subroutine initializerealize (gcomp, importState, exportState, clock, rc)
Called by NUOPC to realize import and export fields. "Realizing" a field means that its grid has been defined and an ESMF_Field object has been created and put into the import or export State.
subroutine datainitialize (gcomp, rc)
TODO.
subroutine modeladvance (gcomp, rc)
Called by NUOPC to advance the model a single timestep.
subroutine modelsetrunclock (gcomp, rc)
subroutine ocean_model_finalize (gcomp, rc)
Called by NUOPC at the end of the run to clean up.
subroutine state_setscalar (value, scalar_id, State, mytask, scalar_name, scalar_count, rc)
Set scalar data from state for a particula name.
subroutine mom_realizefields (state, nfields, field_defs, tag, grid, mesh, rc)
Realize the import and export fields using either a grid or a mesh.
subroutine fld_list_add (num, fldlist, stdname, transferOffer, shortname)
Set up list of field information.
subroutine shr_file_setlogunit (nunit)
subroutine shr_file_getlogunit (nunit)
Variables
integer, parameter fldsmax = 100
integer fldstoocn_num = 0
type(fld_list_type), dimension(fldsmax) fldstoocn
integer fldsfrocn_num = 0
type(fld_list_type), dimension(fldsmax) fldsfrocn
integer debug = 0
integer import_slice = 1
integer export_slice = 1
character(len=256) tmpstr
logical write_diagnostics = .false.
character(len=32) runtype
run type
integer logunit
stdout logging unit number
logical profile_memory = .true.
logical grid_attach_area = .false.
character(len=128) scalar_field_name = ''
integer scalar_field_count = 0
integer scalar_field_idx_grid_nx = 0
integer scalar_field_idx_grid_ny = 0
character(len= *), parameter u_file_u = __FILE__
logical cesm_coupled = .true.
type(esmf_geomtype_flag) geomtype = ESMF_GEOMTYPE_MESH
Function/Subroutine Documentation
datainitialize()
subroutine mom_cap_mod::datainitialize (type(esmf_gridcomp) gcomp, integer, intent(out) rc) private
TODO.
Parameters
gcomp an ESMF_GridComp object
rc return code
gcomp ESMF_GridComp object
[out] rc return code
Definition at line 1771 of file mom_cap.F90.
   type(ESMF_GridComp)  :: gcomp !< ESMF_GridComp object
   integer, intent(out) :: rc    !< return code
   ! local variables
   type(ESMF_Clock)                       :: clock
   type(ESMF_State)                       :: importState, exportState
   type (ocean_public_type),      pointer :: ocean_public       => null()
   type (ocean_state_type),       pointer :: ocean_state        => null()
   type(ice_ocean_boundary_type), pointer :: Ice_ocean_boundary => null()
   type(ocean_internalstate_wrapper)      :: ocean_internalstate
   type(ocean_grid_type), pointer         :: ocean_grid
   character(240)                         :: msgString
   integer                                :: fieldCount, n
   type(ESMF_Field)                       :: field
   character(len=64),allocatable          :: fieldNameList(:)
   character(len=*),parameter  :: subname='(MOM_cap:DataInitialize)'
   !--------------------------------
   ! query the Component for its clock, importState and exportState
   call esmf_gridcompget(gcomp, clock=clock, importstate=importstate, exportstate=exportstate, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   call esmf_gridcompgetinternalstate(gcomp, ocean_internalstate, rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   ice_ocean_boundary => ocean_internalstate%ptr%ice_ocean_boundary_type_ptr
   ocean_public       => ocean_internalstate%ptr%ocean_public_type_ptr
   ocean_state        => ocean_internalstate%ptr%ocean_state_type_ptr
   call get_ocean_grid(ocean_state, ocean_grid)
   if (cesm_coupled) then
      call mom_export(ocean_public, ocean_grid, ocean_state, exportstate, clock, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
           line=__line__, &
           file=__file__)) &
           return  ! bail out
   endif
   call esmf_stateget(exportstate, itemcount=fieldcount, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   allocate(fieldnamelist(fieldcount))
   call esmf_stateget(exportstate, itemnamelist=fieldnamelist, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   do n=1, fieldcount
     call esmf_stateget(exportstate, itemname=fieldnamelist(n), field=field, rc=rc)
     if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
       line=__line__, &
       file=__file__)) &
       return  ! bail out
     call nuopc_setattribute(field, name="Updated", value="true", rc=rc)
     if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
       line=__line__, &
       file=__file__)) &
       return  ! bail out
   enddo
   deallocate(fieldnamelist)
   ! check whether all Fields in the exportState are "Updated"
   if (nuopc_isupdated(exportstate)) then
     call nuopc_compattributeset(gcomp, name="InitializeDataComplete", value="true", rc=rc)
     call esmf_logwrite("MOM6 - Initialize-Data-Dependency SATISFIED!!!", esmf_logmsg_info, rc=rc)
     if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
       line=__line__, &
       file=__file__)) &
       return  ! bail out
   endif
   if(write_diagnostics) then
     call nuopc_write(exportstate, filenameprefix='field_init_ocn_export_', &
       timeslice=import_slice, relaxedflag=.true., rc=rc)
     if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
       line=__line__, &
       file=__file__)) &
       return  ! bail out
   endif
References cesm_coupled, mom_ocean_model_nuopc::get_ocean_grid(), import_slice, mom_cap_methods::mom_export(), and write_diagnostics.
Referenced by setservices().
fld_list_add()
subroutine mom_cap_mod::fld_list_add (integer, intent(inout) num, type(fld_list_type), dimension(:), intent(inout) fldlist, character(len=*), intent(in) stdname, character(len=*), intent(in) transferOffer, character(len=*), intent(in), optional shortname) private
Set up list of field information.
Definition at line 2593 of file mom_cap.F90.
   integer,                    intent(inout) :: num
   type(fld_list_type),        intent(inout) :: fldlist(:)
   character(len=*),           intent(in)    :: stdname
   character(len=*),           intent(in)    :: transferOffer
   character(len=*), optional, intent(in)    :: shortname
   ! local variables
   integer :: rc
   character(len=*), parameter :: subname='(MOM_cap:fld_list_add)'
   ! fill in the new entry
   num = num + 1
   if (num > fldsmax) then
      call esmf_logseterror(esmf_rc_val_outofrange, &
           msg=trim(subname)//": ERROR number of field exceeded fldsMax: "//trim(stdname), &
           line=__line__, file=__file__, rctoreturn=rc)
      return
   endif
   fldlist(num)%stdname        = trim(stdname)
   if (present(shortname)) then
      fldlist(num)%shortname   = trim(shortname)
   else
      fldlist(num)%shortname   = trim(stdname)
   endif
   fldlist(num)%transferOffer  = trim(transferoffer)
References fldsmax.
Referenced by initializeadvertise().
initializeadvertise()
subroutine mom_cap_mod::initializeadvertise (type(esmf_gridcomp) gcomp, type(esmf_state) importState, type(esmf_state) exportState, type(esmf_clock) clock, integer, intent(out) rc) private
Called by NUOPC to advertise import and export fields. "Advertise" simply means that the standard names of all import and export fields are supplied. The NUOPC layer uses these to match fields between components in the coupled system.
Parameters
gcomp an ESMF_GridComp object
importState an ESMF_State object for import fields
exportState an ESMF_State object for export fields
clock an ESMF_Clock object
rc return code
gcomp ESMF_GridComp object
exportstate ESMF_State object for import/export fields
clock ESMF_Clock object
[out] rc return code
Definition at line 726 of file mom_cap.F90.
   type(ESMF_GridComp)            :: gcomp                    !< ESMF_GridComp object
   type(ESMF_State)               :: importState, exportState !< ESMF_State object for
                                                              !! import/export fields
   type(ESMF_Clock)               :: clock                    !< ESMF_Clock object
   integer, intent(out)           :: rc                       !< return code
   ! local variables
   type(ESMF_VM)                          :: vm
   type(ESMF_Time)                        :: MyTime
   type(ESMF_TimeInterval)                :: TINT
   type (ocean_public_type),      pointer :: ocean_public => null()
   type (ocean_state_type),       pointer :: ocean_state => null()
   type(ice_ocean_boundary_type), pointer :: Ice_ocean_boundary => null()
   type(ocean_internalstate_wrapper)      :: ocean_internalstate
   type(ocean_grid_type),         pointer :: ocean_grid => null()
   type(time_type)                        :: Run_len      !< length of experiment
   type(time_type)                        :: time0        !< Start time of coupled model's calendar.
   type(time_type)                        :: time_start   !< The time at which to initialize the ocean model
   type(time_type)                        :: Time_restart
   type(time_type)                        :: DT
   integer                                :: DT_OCEAN
   integer                                :: isc,iec,jsc,jec
   integer                                :: year=0, month=0, day=0, hour=0, minute=0, second=0
   integer                                :: mpi_comm_mom
   integer                                :: i,n
   character(len=256)                     :: stdname, shortname
   character(len=32)                      :: starttype            ! model start type
   character(len=512)                     :: diro
   character(len=512)                     :: logfile
   character(ESMF_MAXSTR)                 :: cvalue
   logical                                :: isPresent, isPresentDiro, isPresentLogfile, isSet
   logical                                :: existflag
   integer                                :: userRc
   character(len=512)                     :: restartfile          ! Path/Name of restart file
   character(len=*), parameter            :: subname='(MOM_cap:InitializeAdvertise)'
   character(len=32)                      :: calendar
 !--------------------------------
   rc = esmf_success
   call esmf_logwrite(subname//' enter', esmf_logmsg_info, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
        line=__line__, &
        file=__file__)) &
        return
   allocate(ice_ocean_boundary)
   !allocate(ocean_state) ! ocean_model_init allocate this pointer
   allocate(ocean_public)
   allocate(ocean_internalstate%ptr)
   ocean_internalstate%ptr%ice_ocean_boundary_type_ptr => ice_ocean_boundary
   ocean_internalstate%ptr%ocean_public_type_ptr       => ocean_public
   ocean_internalstate%ptr%ocean_state_type_ptr        => ocean_state
   call esmf_vmgetcurrent(vm, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   call esmf_vmget(vm, mpicommunicator=mpi_comm_mom, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   call esmf_clockget(clock, currtime=mytime, timestep=tint,  rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   call esmf_timeget (mytime, yy=year, mm=month, dd=day, h=hour, m=minute, s=second, rc=rc )
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   CALL esmf_timeintervalget(tint, s=dt_ocean, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   call fms_init(mpi_comm_mom)
   call constants_init
   call field_manager_init
   ! determine the calendar
   if (cesm_coupled) then
      call nuopc_compattributeget(gcomp, name="calendar", value=cvalue, &
           ispresent=ispresent, isset=isset, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
           line=__line__, &
           file=__file__)) &
           return  ! bail out
      if (ispresent .and. isset) then
         read(cvalue,*) calendar
         select case (trim(calendar))
            case ("NO_LEAP")
               call set_calendar_type (noleap)
            case ("GREGORIAN")
               call set_calendar_type (gregorian)
            case default
               call esmf_logseterror(esmf_rc_arg_bad, &
                  msg=subname//": Calendar not supported in MOM6: "//trim(calendar), &
                  line=__line__, file=__file__, rctoreturn=rc)
            end select
      else
         call set_calendar_type (noleap)
      endif
   else
      call set_calendar_type (julian)
   endif
   call diag_manager_init
   ! this ocean connector will be driven at set interval
   dt = set_time(dt_ocean, 0)
   ! get current time
   time_start = set_date(year,month,day,hour,minute,second)
   if (is_root_pe()) then
     write(logunit,*) subname//'current time: y,m,d-',year,month,day,'h,m,s=',hour,minute,second
   endif
   ! get start/reference time
   call esmf_clockget(clock, reftime=mytime, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   call esmf_timeget (mytime, yy=year, mm=month, dd=day, h=hour, m=minute, s=second, rc=rc )
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   time0 = set_date(year,month,day,hour,minute,second)
   if (is_root_pe()) then
     write(logunit,*) subname//'start time: y,m,d-',year,month,day,'h,m,s=',hour,minute,second
   endif
   ! rsd need to figure out how to get this without share code
   !call shr_nuopc_get_component_instance(gcomp, inst_suffix, inst_index)
   !inst_name = "OCN"//trim(inst_suffix)
   ! reset shr logging to my log file
   if (is_root_pe()) then
      call nuopc_compattributeget(gcomp, name="diro", &
           ispresent=ispresentdiro, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return
      call nuopc_compattributeget(gcomp, name="logfile", &
           ispresent=ispresentlogfile, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return
      if (ispresentdiro .and. ispresentlogfile) then
           call nuopc_compattributeget(gcomp, name="diro", value=diro, rc=rc)
           if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
               line=__line__, &
               file=__file__)) &
               return
           call nuopc_compattributeget(gcomp, name="logfile", value=logfile, rc=rc)
           if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
               line=__line__, &
               file=__file__)) &
               return
         open(newunit=logunit,file=trim(diro)//"/"//trim(logfile))
      else
         logunit = output_unit
      endif
   else
      logunit = output_unit
   endif
   starttype = ""
   call nuopc_compattributeget(gcomp, name='start_type', value=cvalue, &
        ispresent=ispresent, isset=isset, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
        line=__line__, &
        file=__file__)) &
        return
   if (ispresent .and. isset) then
      read(cvalue,*) starttype
   else
      call esmf_logwrite('MOM_cap:start_type unset - using input.nml for restart option', &
           esmf_logmsg_info, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return
   endif
   runtype = ""
   if (trim(starttype) == trim('startup')) then
      runtype = "initial"
   else if (trim(starttype) == trim('continue') ) then
      runtype = "continue"
   else if (trim(starttype) == trim('branch')) then
      runtype = "continue"
   else if (len_trim(starttype) > 0) then
      call esmf_logseterror(esmf_rc_arg_bad, &
           msg=subname//": unknown starttype - "//trim(starttype), &
           line=__line__, file=__file__, rctoreturn=rc)
      return
   endif
   if (len_trim(runtype) > 0) then
      call esmf_logwrite('MOM_cap:startup = '//trim(runtype), esmf_logmsg_info, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return
   endif
   restartfile = ""
   if (runtype == "initial") then
      ! startup (new run) - 'n' is needed below if we don't specify input_filename in input.nml
      restartfile = "n"
   else if (runtype == "continue") then ! hybrid or branch or continuos runs
      ! optionally call into system-specific implementation to get restart file name
      call esmf_methodexecute(gcomp, label="GetRestartFileToRead", &
           existflag=existflag, userrc=userrc, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg="Error executing user method to get restart filename", &
          line=__line__, &
          file=__file__)) &
          return  ! bail out
      if (esmf_logfounderror(rctocheck=userrc, msg="Error in method to get restart filename", &
          line=__line__, &
          file=__file__)) &
          return  ! bail out
      if (existflag) then
         call esmf_logwrite('MOM_cap: called user GetRestartFileToRead', esmf_logmsg_info, rc=rc)
         if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
             line=__line__, &
             file=__file__)) &
             return
      endif
      call nuopc_compattributeget(gcomp, name='RestartFileToRead', &
           value=cvalue, ispresent=ispresent, isset=isset, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return
      if (ispresent .and. isset) then
         restartfile = trim(cvalue)
         call esmf_logwrite('MOM_cap: RestartFileToRead = '//trim(restartfile), esmf_logmsg_info, rc=rc)
         if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
             line=__line__, &
             file=__file__)) &
             return
      else
         call esmf_logwrite('MOM_cap: restart requested, no RestartFileToRead attribute provided-will use input.nml',&
              esmf_logmsg_warning, rc=rc)
         if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
             line=__line__, &
             file=__file__)) &
             return
      endif
   endif
   ocean_public%is_ocean_pe = .true.
   call ocean_model_init(ocean_public, ocean_state, time0, time_start, input_restart_file=trim(restartfile))
   call ocean_model_init_sfc(ocean_state, ocean_public)
   call mpp_get_compute_domain(ocean_public%domain, isc, iec, jsc, jec)
   allocate ( ice_ocean_boundary% u_flux (isc:iec,jsc:jec),          &
              ice_ocean_boundary% v_flux (isc:iec,jsc:jec),          &
              ice_ocean_boundary% t_flux (isc:iec,jsc:jec),          &
              ice_ocean_boundary% q_flux (isc:iec,jsc:jec),          &
              ice_ocean_boundary% salt_flux (isc:iec,jsc:jec),       &
              ice_ocean_boundary% lw_flux (isc:iec,jsc:jec),         &
              ice_ocean_boundary% sw_flux_vis_dir (isc:iec,jsc:jec), &
              ice_ocean_boundary% sw_flux_vis_dif (isc:iec,jsc:jec), &
              ice_ocean_boundary% sw_flux_nir_dir (isc:iec,jsc:jec), &
              ice_ocean_boundary% sw_flux_nir_dif (isc:iec,jsc:jec), &
              ice_ocean_boundary% lprec (isc:iec,jsc:jec),           &
              ice_ocean_boundary% fprec (isc:iec,jsc:jec),           &
              ice_ocean_boundary% seaice_melt_heat (isc:iec,jsc:jec),&
              ice_ocean_boundary% seaice_melt (isc:iec,jsc:jec),     &
              ice_ocean_boundary% mi (isc:iec,jsc:jec),              &
              ice_ocean_boundary% p (isc:iec,jsc:jec),               &
              ice_ocean_boundary% runoff (isc:iec,jsc:jec),          &
              ice_ocean_boundary% calving (isc:iec,jsc:jec),         &
              ice_ocean_boundary% runoff_hflx (isc:iec,jsc:jec),     &
              ice_ocean_boundary% calving_hflx (isc:iec,jsc:jec),    &
              ice_ocean_boundary% rofl_flux (isc:iec,jsc:jec),       &
              ice_ocean_boundary% rofi_flux (isc:iec,jsc:jec))
   ice_ocean_boundary%u_flux          = 0.0
   ice_ocean_boundary%v_flux          = 0.0
   ice_ocean_boundary%t_flux          = 0.0
   ice_ocean_boundary%q_flux          = 0.0
   ice_ocean_boundary%salt_flux       = 0.0
   ice_ocean_boundary%lw_flux         = 0.0
   ice_ocean_boundary%sw_flux_vis_dir = 0.0
   ice_ocean_boundary%sw_flux_vis_dif = 0.0
   ice_ocean_boundary%sw_flux_nir_dir = 0.0
   ice_ocean_boundary%sw_flux_nir_dif = 0.0
   ice_ocean_boundary%lprec           = 0.0
   ice_ocean_boundary%fprec           = 0.0
   ice_ocean_boundary%seaice_melt     = 0.0
   ice_ocean_boundary%seaice_melt_heat= 0.0
   ice_ocean_boundary%mi              = 0.0
   ice_ocean_boundary%p               = 0.0
   ice_ocean_boundary%runoff          = 0.0
   ice_ocean_boundary%calving         = 0.0
   ice_ocean_boundary%runoff_hflx     = 0.0
   ice_ocean_boundary%calving_hflx    = 0.0
   ice_ocean_boundary%rofl_flux       = 0.0
   ice_ocean_boundary%rofi_flux       = 0.0
   ocean_internalstate%ptr%ocean_state_type_ptr => ocean_state
   call esmf_gridcompsetinternalstate(gcomp, ocean_internalstate, rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   if (cesm_coupled) then
      if (len_trim(scalar_field_name) > 0) then
         call fld_list_add(fldstoocn_num, fldstoocn, trim(scalar_field_name), "will_provide")
         call fld_list_add(fldsfrocn_num, fldsfrocn, trim(scalar_field_name), "will_provide")
      endif
     !call fld_list_add(fldsToOcn_num, fldsToOcn, "Sw_lamult"                 , "will provide")
     !call fld_list_add(fldsToOcn_num, fldsToOcn, "Sw_ustokes"                , "will provide")
     !call fld_list_add(fldsToOcn_num, fldsToOcn, "Sw_vstokes"                , "will provide")
     !call fld_list_add(fldsToOcn_num, fldsToOcn, "Sw_hstokes"                , "will provide")
     !call fld_list_add(fldsToOcn_num, fldsToOcn, "Fioi_melth"                , "will provide")
     !call fld_list_add(fldsToOcn_num, fldsToOcn, "Fioi_meltw"                , "will provide")
     !call fld_list_add(fldsFrOcn_num, fldsFrOcn, "So_fswpen"                 , "will provide")
   else
     !call fld_list_add(fldsToOcn_num, fldsToOcn, "mass_of_overlying_sea_ice" , "will provide")
     !call fld_list_add(fldsFrOcn_num, fldsFrOcn, "sea_lev"                   , "will provide")
   endif
   !--------- import fields -------------
   call fld_list_add(fldstoocn_num, fldstoocn, "mean_salt_rate"             , "will provide") ! from ice
   call fld_list_add(fldstoocn_num, fldstoocn, "mean_zonal_moment_flx"      , "will provide")
   call fld_list_add(fldstoocn_num, fldstoocn, "mean_merid_moment_flx"      , "will provide")
   call fld_list_add(fldstoocn_num, fldstoocn, "mean_sensi_heat_flx"        , "will provide")
   call fld_list_add(fldstoocn_num, fldstoocn, "mean_evap_rate"             , "will provide")
   call fld_list_add(fldstoocn_num, fldstoocn, "mean_net_lw_flx"            , "will provide")
   call fld_list_add(fldstoocn_num, fldstoocn, "mean_net_sw_vis_dir_flx"    , "will provide")
   call fld_list_add(fldstoocn_num, fldstoocn, "mean_net_sw_vis_dif_flx"    , "will provide")
   call fld_list_add(fldstoocn_num, fldstoocn, "mean_net_sw_ir_dir_flx"     , "will provide")
   call fld_list_add(fldstoocn_num, fldstoocn, "mean_net_sw_ir_dif_flx"     , "will provide")
   call fld_list_add(fldstoocn_num, fldstoocn, "mean_prec_rate"             , "will provide")
   call fld_list_add(fldstoocn_num, fldstoocn, "mean_fprec_rate"            , "will provide")
   call fld_list_add(fldstoocn_num, fldstoocn, "inst_pres_height_surface"   , "will provide")
   call fld_list_add(fldstoocn_num, fldstoocn, "Foxx_rofl"                  , "will provide") !-> liquid runoff
   call fld_list_add(fldstoocn_num, fldstoocn, "Foxx_rofi"                  , "will provide") !-> ice runoff
   call fld_list_add(fldstoocn_num, fldstoocn, "mean_fresh_water_to_ocean_rate", "will provide")
   call fld_list_add(fldstoocn_num, fldstoocn, "net_heat_flx_to_ocn"        , "will provide")
  !call fld_list_add(fldsToOcn_num, fldsToOcn, "mean_runoff_rate"           , "will provide")
  !call fld_list_add(fldsToOcn_num, fldsToOcn, "mean_calving_rate"          , "will provide")
  !call fld_list_add(fldsToOcn_num, fldsToOcn, "mean_runoff_heat_flx"       , "will provide")
  !call fld_list_add(fldsToOcn_num, fldsToOcn, "mean_calving_heat_flx"      , "will provide")
   !--------- export fields -------------
   call fld_list_add(fldsfrocn_num, fldsfrocn, "ocean_mask"                 , "will provide")
   call fld_list_add(fldsfrocn_num, fldsfrocn, "sea_surface_temperature"    , "will provide")
   call fld_list_add(fldsfrocn_num, fldsfrocn, "s_surf"                     , "will provide")
   call fld_list_add(fldsfrocn_num, fldsfrocn, "ocn_current_zonal"          , "will provide")
   call fld_list_add(fldsfrocn_num, fldsfrocn, "ocn_current_merid"          , "will provide")
   call fld_list_add(fldsfrocn_num, fldsfrocn, "sea_surface_slope_zonal"    , "will provide")
   call fld_list_add(fldsfrocn_num, fldsfrocn, "sea_surface_slope_merid"    , "will provide")
   call fld_list_add(fldsfrocn_num, fldsfrocn, "freezing_melting_potential" , "will provide")
   call fld_list_add(fldsfrocn_num, fldsfrocn, "So_bldepth"                 , "will provide")
   do n = 1,fldstoocn_num
     call nuopc_advertise(importstate, standardname=fldstoocn(n)%stdname, name=fldstoocn(n)%shortname, rc=rc)
     if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
       line=__line__, &
       file=__file__)) &
       return  ! bail out
   enddo
   do n = 1,fldsfrocn_num
     call nuopc_advertise(exportstate, standardname=fldsfrocn(n)%stdname, name=fldsfrocn(n)%shortname, rc=rc)
     if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
       line=__line__, &
       file=__file__)) &
       return  ! bail out
   enddo
References cesm_coupled, fld_list_add(), fldsfrocn, fldsfrocn_num, fldstoocn, fldstoocn_num, mom_error_handler::is_root_pe(), logunit, runtype, and scalar_field_name.
Referenced by setservices().
initializep0()
subroutine mom_cap_mod::initializep0 (type(esmf_gridcomp) gcomp, type(esmf_state) importState, type(esmf_state) exportState, type(esmf_clock) clock, integer, intent(out) rc) private
First initialize subroutine called by NUOPC. The purpose is to set which version of the Initialize Phase Definition (IPD) to use.
For this MOM cap, we are using IPDv01.
Parameters
gcomp an ESMF_GridComp object
importState an ESMF_State object for import fields
exportState an ESMF_State object for export fields
clock an ESMF_Clock object
rc return code
gcomp ESMF_GridComp object
exportstate ESMF_State object for import/export fields
clock ESMF_Clock object
[out] rc return code
Definition at line 553 of file mom_cap.F90.
   type(ESMF_GridComp)   :: gcomp                    !< ESMF_GridComp object
   type(ESMF_State)      :: importState, exportState !< ESMF_State object for
                                                     !! import/export fields
   type(ESMF_Clock)      :: clock                    !< ESMF_Clock object
   integer, intent(out)  :: rc                       !< return code
   ! local variables
   logical                     :: isPresent, isSet
   integer                     :: iostat
   character(len=64)           :: value, logmsg
   character(len=*),parameter  :: subname='(MOM_cap:InitializeP0)'
   rc = esmf_success
   ! Switch to IPDv03 by filtering all other phaseMap entries
   call nuopc_compfilterphasemap(gcomp, esmf_method_initialize, &
        acceptstringlist=(/"IPDv03p"/), rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
        line=__line__, &
        file=__file__)) &
        return
   write_diagnostics = .false.
   call nuopc_compattributeget(gcomp, name="DumpFields", value=value, &
        ispresent=ispresent, isset=isset, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
        line=__line__, &
        file=__file__)) &
        return
   if (ispresent .and. isset) write_diagnostics=(trim(value)=="true")
   write(logmsg,*) write_diagnostics
   call esmf_logwrite('MOM_cap:DumpFields = '//trim(logmsg), esmf_logmsg_info, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
        line=__line__, &
        file=__file__)) &
        return
   profile_memory = .false.
   call nuopc_compattributeget(gcomp, name="ProfileMemory", value=value, &
        ispresent=ispresent, isset=isset, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
        line=__line__, &
        file=__file__)) &
        return
   if (ispresent .and. isset) profile_memory=(trim(value)=="true")
   write(logmsg,*) profile_memory
   call esmf_logwrite('MOM_cap:ProfileMemory = '//trim(logmsg), esmf_logmsg_info, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
        line=__line__, &
        file=__file__)) &
        return
   grid_attach_area = .false.
   call nuopc_compattributeget(gcomp, name="GridAttachArea", value=value, &
        ispresent=ispresent, isset=isset, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
        line=__line__, &
        file=__file__)) &
        return
   if (ispresent .and. isset) grid_attach_area=(trim(value)=="true")
   write(logmsg,*) grid_attach_area
   call esmf_logwrite('MOM_cap:GridAttachArea = '//trim(logmsg), esmf_logmsg_info, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
        line=__line__, &
        file=__file__)) &
        return
   scalar_field_name = ""
   call nuopc_compattributeget(gcomp, name="ScalarFieldName", value=value, &
        ispresent=ispresent, isset=isset, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
        line=__line__, &
        file=__file__)) &
        return
   if (ispresent .and. isset) then
      scalar_field_name = trim(value)
      call esmf_logwrite('MOM_cap:ScalarFieldName = '//trim(scalar_field_name), esmf_logmsg_info, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
         line=__line__, &
         file=__file__)) &
         return
   endif
   scalar_field_count = 0
   call nuopc_compattributeget(gcomp, name="ScalarFieldCount", value=value, &
        ispresent=ispresent, isset=isset, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
        line=__line__, &
        file=__file__)) &
        return
   if (ispresent .and. isset) then
      read(value, '(i)', iostat=iostat) scalar_field_count
      if (iostat /= 0) then
        call esmf_logseterror(esmf_rc_arg_bad, &
             msg=subname//": ScalarFieldCount not an integer: "//trim(value), &
             line=__line__, file=__file__, rctoreturn=rc)
        return
      endif
      write(logmsg,*) scalar_field_count
      call esmf_logwrite('MOM_cap:ScalarFieldCount = '//trim(logmsg), esmf_logmsg_info, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return
   endif
   scalar_field_idx_grid_nx = 0
   call nuopc_compattributeget(gcomp, name="ScalarFieldIdxGridNX", value=value, &
        ispresent=ispresent, isset=isset, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
        line=__line__, &
        file=__file__)) &
        return
   if (ispresent .and. isset) then
      read(value, '(i)', iostat=iostat) scalar_field_idx_grid_nx
      if (iostat /= 0) then
         call esmf_logseterror(esmf_rc_arg_bad, &
              msg=subname//": ScalarFieldIdxGridNX not an integer: "//trim(value), &
              line=__line__, file=__file__, rctoreturn=rc)
         return
      endif
      write(logmsg,*) scalar_field_idx_grid_nx
      call esmf_logwrite('MOM_cap:ScalarFieldIdxGridNX = '//trim(logmsg), esmf_logmsg_info, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return
   endif
   scalar_field_idx_grid_ny = 0
   call nuopc_compattributeget(gcomp, name="ScalarFieldIdxGridNY", value=value, &
        ispresent=ispresent, isset=isset, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
        line=__line__, &
        file=__file__)) &
        return
   if (ispresent .and. isset) then
      read(value, '(i)', iostat=iostat) scalar_field_idx_grid_ny
      if (iostat /= 0) then
         call esmf_logseterror(esmf_rc_arg_bad, &
              msg=subname//": ScalarFieldIdxGridNY not an integer: "//trim(value), &
              line=__line__, file=__file__, rctoreturn=rc)
         return
      endif
      write(logmsg,*) scalar_field_idx_grid_ny
      call esmf_logwrite('MOM_cap:ScalarFieldIdxGridNY = '//trim(logmsg), esmf_logmsg_info, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
           line=__line__, &
           file=__file__)) &
           return
   endif
   call nuopc_compattributeadd(gcomp, &
        attrlist=(/'RestartFileToRead', 'RestartFileToWrite'/), rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
        line=__line__, &
        file=__file__)) &
        return
References grid_attach_area, profile_memory, scalar_field_count, scalar_field_idx_grid_nx, scalar_field_idx_grid_ny, scalar_field_name, and write_diagnostics.
Referenced by setservices().
initializerealize()
subroutine mom_cap_mod::initializerealize (type(esmf_gridcomp) gcomp, type(esmf_state) importState, type(esmf_state) exportState, type(esmf_clock) clock, integer, intent(out) rc) private
Called by NUOPC to realize import and export fields. "Realizing" a field means that its grid has been defined and an ESMF_Field object has been created and put into the import or export State.
Parameters
gcomp an ESMF_GridComp object
importState an ESMF_State object for import fields
exportState an ESMF_State object for export fields
clock an ESMF_Clock object
rc return code
gcomp ESMF_GridComp object
exportstate ESMF_State object for import/export fields
clock ESMF_Clock object
[out] rc return code
Definition at line 1138 of file mom_cap.F90.
   type(ESMF_GridComp)  :: gcomp                    !< ESMF_GridComp object
   type(ESMF_State)     :: importState, exportState !< ESMF_State object for
                                                    !! import/export fields
   type(ESMF_Clock)     :: clock                    !< ESMF_Clock object
   integer, intent(out) :: rc                       !< return code
   ! Local Variables
   type(ESMF_VM)                              :: vm
   type(ESMF_Grid)                            :: gridIn, gridOut
   type(ESMF_Mesh)                            :: Emesh, EmeshTemp
   type(ESMF_DeLayout)                        :: delayout
   type(ESMF_Distgrid)                        :: Distgrid
   type(ESMF_DistGridConnection), allocatable :: connectionList(:)
   type(ESMF_StateItem_Flag)                  :: itemFlag
   type (ocean_public_type),      pointer     :: ocean_public   => null()
   type (ocean_state_type),       pointer     :: ocean_state => null()
   type(ice_ocean_boundary_type), pointer     :: Ice_ocean_boundary => null()
   type(ocean_grid_type)        , pointer     :: ocean_grid
   type(ocean_internalstate_wrapper)          :: ocean_internalstate
   integer                                    :: npet, ntiles
   integer                                    :: nxg, nyg, cnt
   integer                                    :: isc,iec,jsc,jec
   integer, allocatable                       :: xb(:),xe(:),yb(:),ye(:),pe(:)
   integer, allocatable                       :: deBlockList(:,:,:)
   integer, allocatable                       :: petMap(:)
   integer, allocatable                       :: deLabelList(:)
   integer, allocatable                       :: indexList(:)
   integer                                    :: ioff, joff
   integer                                    :: i, j, n, i1, j1, n1, jlast
   integer                                    :: lbnd1,ubnd1,lbnd2,ubnd2
   integer                                    :: lbnd3,ubnd3,lbnd4,ubnd4
   integer                                    :: nblocks_tot
   logical                                    :: found
   integer(ESMF_KIND_I4), pointer             :: dataPtr_mask(:,:)
   real(ESMF_KIND_R8), pointer                :: dataPtr_area(:,:)
   real(ESMF_KIND_R8), pointer                :: dataPtr_xcen(:,:)
   real(ESMF_KIND_R8), pointer                :: dataPtr_ycen(:,:)
   real(ESMF_KIND_R8), pointer                :: dataPtr_xcor(:,:)
   real(ESMF_KIND_R8), pointer                :: dataPtr_ycor(:,:)
   integer                                    :: mpicom
   integer                                    :: localPet
   integer                                    :: lsize
   integer                                    :: ig,jg, ni,nj,k
   integer, allocatable                       :: gindex(:) ! global index space
   character(len=128)                         :: fldname
   character(len=256)                         :: cvalue
   character(len=256)                         :: frmt    ! format specifier for several error msgs
   character(len=512)                         :: err_msg ! error messages
   character(len=*), parameter                :: subname='(MOM_cap:InitializeRealize)'
   integer                         :: spatialDim
   integer                         :: numOwnedElements
   type(ESMF_Array)                :: elemMaskArray
   real(ESMF_KIND_R8)    , pointer :: ownedElemCoords(:)
   real(ESMF_KIND_R8)    , pointer :: lat(:), latMesh(:)
   real(ESMF_KIND_R8)    , pointer :: lon(:), lonMesh(:)
   integer(ESMF_KIND_I4) , pointer :: mask(:), maskMesh(:)
   real(ESMF_KIND_R8)              :: diff_lon, diff_lat
   real                            :: eps_omesh
   !--------------------------------
   rc = esmf_success
   call shr_file_setlogunit (logunit)
   !----------------------------------------------------------------------------
   ! Get pointers to ocean internal state
   !----------------------------------------------------------------------------
   call esmf_gridcompgetinternalstate(gcomp, ocean_internalstate, rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   ice_ocean_boundary => ocean_internalstate%ptr%ice_ocean_boundary_type_ptr
   ocean_public       => ocean_internalstate%ptr%ocean_public_type_ptr
   ocean_state        => ocean_internalstate%ptr%ocean_state_type_ptr
   !----------------------------------------------------------------------------
   ! Get mpi information
   !----------------------------------------------------------------------------
   call esmf_vmgetcurrent(vm, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   call esmf_vmget(vm, petcount=npet, mpicommunicator=mpicom, localpet=localpet, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   !---------------------------------
   ! global mom grid size
   !---------------------------------
   call mpp_get_global_domain(ocean_public%domain, xsize=nxg, ysize=nyg)
   write(tmpstr,'(a,2i6)') subname//' nxg,nyg = ',nxg,nyg
   call esmf_logwrite(trim(tmpstr), esmf_logmsg_info, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
        line=__line__, &
        file=__file__)) &
        return  ! bail out
   !---------------------------------
   ! number of tiles per PET, assumed to be 1, and number of pes (tiles) total
   !---------------------------------
   ntiles=mpp_get_ntile_count(ocean_public%domain) ! this is tiles on this pe
   if (ntiles /= 1) then
     rc = esmf_failure
     call esmf_logwrite(subname//' ntiles must be 1', esmf_logmsg_error, rc=rc)
     if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
         line=__line__, &
         file=__file__)) &
         return
   endif
   ntiles=mpp_get_domain_npes(ocean_public%domain)
   write(tmpstr,'(a,1i6)') subname//' ntiles = ',ntiles
   call esmf_logwrite(trim(tmpstr), esmf_logmsg_info, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
        line=__line__, &
        file=__file__)) &
        return
   !---------------------------------
   ! get start and end indices of each tile and their PET
   !---------------------------------
   allocate(xb(ntiles),xe(ntiles),yb(ntiles),ye(ntiles),pe(ntiles))
   call mpp_get_compute_domains(ocean_public%domain, xbegin=xb, xend=xe, ybegin=yb, yend=ye)
   call mpp_get_pelist(ocean_public%domain, pe)
   if (debug > 0) then
      do n = 1,ntiles
         write(tmpstr,'(a,6i6)') subname//' tiles ',n,pe(n),xb(n),xe(n),yb(n),ye(n)
         call esmf_logwrite(trim(tmpstr), esmf_logmsg_info, rc=rc)
         if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
             line=__line__, &
             file=__file__)) &
             return
      enddo
   endif
   !---------------------------------
   ! Create either a grid or a mesh
   !---------------------------------
    !Get the ocean grid and sizes of global and computational domains
    call get_ocean_grid(ocean_state, ocean_grid)
   if (geomtype == esmf_geomtype_mesh) then
      !---------------------------------
      ! Create a MOM6 mesh
      !---------------------------------
      call get_global_grid_size(ocean_grid, ni, nj)
      lsize = ( ocean_grid%iec - ocean_grid%isc + 1 ) * ( ocean_grid%jec - ocean_grid%jsc + 1 )
      ! Create the global index space for the computational domain
      allocate(gindex(lsize))
      k = 0
      do j = ocean_grid%jsc, ocean_grid%jec
         jg = j + ocean_grid%jdg_offset
         do i = ocean_grid%isc, ocean_grid%iec
            ig = i + ocean_grid%idg_offset
            k = k + 1 ! Increment position within gindex
            gindex(k) = ni * (jg - 1) + ig
         enddo
      enddo
      distgrid = esmf_distgridcreate(arbseqindexlist=gindex, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return
      ! read in the mesh
      call nuopc_compattributeget(gcomp, name='mesh_ocn', value=cvalue, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return
      emeshtemp = esmf_meshcreate(filename=trim(cvalue), fileformat=esmf_fileformat_esmfmesh, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return
      if (localpet == 0) then
         write(logunit,*)'mesh file for mom6 domain is ',trim(cvalue)
      endif
      ! recreate the mesh using the above distGrid
      emesh = esmf_meshcreate(emeshtemp, elementdistgrid=distgrid, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return
      ! Check for consistency of lat, lon and mask between mesh and mom6 grid
      call esmf_meshget(emesh, spatialdim=spatialdim, numownedelements=numownedelements, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
           line=__line__, &
           file=__file__)) &
           return
      allocate(ownedelemcoords(spatialdim*numownedelements))
      allocate(lonmesh(numownedelements), lon(numownedelements))
      allocate(latmesh(numownedelements), lat(numownedelements))
      allocate(maskmesh(numownedelements), mask(numownedelements))
      call esmf_meshget(emesh, ownedelemcoords=ownedelemcoords, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
           line=__line__, &
           file=__file__)) &
           return
      do n = 1,numownedelements
         lonmesh(n) = ownedelemcoords(2*n-1)
         latmesh(n) = ownedelemcoords(2*n)
      end do
      elemmaskarray = esmf_arraycreate(distgrid, maskmesh, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
           line=__line__, &
           file=__file__)) &
           return
      call esmf_meshget(emesh, elemmaskarray=elemmaskarray, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
           line=__line__, &
           file=__file__)) &
           return
      call mpp_get_compute_domain(ocean_public%domain, isc, iec, jsc, jec)
      n = 0
      do j = jsc, jec
        jg = j + ocean_grid%jsc - jsc
        do i = isc, iec
          ig = i + ocean_grid%isc - isc
          n = n+1
          mask(n) = ocean_grid%mask2dT(ig,jg)
          lon(n)  = ocean_grid%geolonT(ig,jg)
          lat(n)  = ocean_grid%geolatT(ig,jg)
        end do
      end do
      eps_omesh = get_eps_omesh(ocean_state)
      do n = 1,numownedelements
        diff_lon = abs(mod(lonmesh(n) - lon(n),360.0))
        if (diff_lon > eps_omesh) then
          frmt = "('ERROR: Difference between ESMF Mesh and MOM6 domain coords is "//&
                 "greater than parameter EPS_OMESH. n, lonMesh(n), lon(n), diff_lon, "//&
                 "EPS_OMESH= ',i8,2(f21.13,3x),2(d21.5))"
          write(err_msg, frmt)n,lonmesh(n),lon(n), diff_lon, eps_omesh
          call mom_error(fatal, err_msg)
        end if
        diff_lat = abs(latmesh(n) - lat(n))
        if (diff_lat > eps_omesh) then
          frmt = "('ERROR: Difference between ESMF Mesh and MOM6 domain coords is"//&
                 "greater than parameter EPS_OMESH. n, latMesh(n), lat(n), diff_lat, "//&
                 "EPS_OMESH= ',i8,2(f21.13,3x),2(d21.5))"
          write(err_msg, frmt)n,latmesh(n),lat(n), diff_lat, eps_omesh
          call mom_error(fatal, err_msg)
         end if
         if (abs(maskmesh(n) - mask(n)) > 0) then
           frmt = "('ERROR: ESMF mesh and MOM6 domain masks are inconsistent! - "//&
                  "MOM n, maskMesh(n), mask(n) = ',3(i8,2x))"
           write(err_msg, frmt)n,maskmesh(n),mask(n)
           call mom_error(fatal, err_msg)
         end if
      end do
      deallocate(ownedelemcoords)
      deallocate(lonmesh , lon )
      deallocate(latmesh , lat )
      deallocate(maskmesh, mask)
      ! realize the import and export fields using the mesh
      call mom_realizefields(importstate, fldstoocn_num, fldstoocn, "Ocn import", mesh=emesh, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return
      call mom_realizefields(exportstate, fldsfrocn_num, fldsfrocn, "Ocn export", mesh=emesh, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return
   else if (geomtype == esmf_geomtype_grid) then
      !---------------------------------
      ! create a MOM6 grid
      !---------------------------------
      ! generate delayout and dist_grid
      allocate(deblocklist(2,2,ntiles))
      allocate(petmap(ntiles))
      allocate(delabellist(ntiles))
      do n = 1, ntiles
        delabellist(n) = n
        deblocklist(1,1,n) = xb(n)
        deblocklist(1,2,n) = xe(n)
        deblocklist(2,1,n) = yb(n)
        deblocklist(2,2,n) = ye(n)
        petmap(n) = pe(n)
        ! write(tmpstr,'(a,3i8)') subname//' iglo = ',n,deBlockList(1,1,n),deBlockList(1,2,n)
        ! call ESMF_LogWrite(trim(tmpstr), ESMF_LOGMSG_INFO, rc=rc)
        ! write(tmpstr,'(a,3i8)') subname//' jglo = ',n,deBlockList(2,1,n),deBlockList(2,2,n)
        ! call ESMF_LogWrite(trim(tmpstr), ESMF_LOGMSG_INFO, rc=rc)
        ! write(tmpstr,'(a,2i8)') subname//' pe  = ',n,petMap(n)
        ! call ESMF_LogWrite(trim(tmpstr), ESMF_LOGMSG_INFO, rc=rc)
        !--- assume a tile with starting index of 1 has an equivalent wraparound tile on the other side
      enddo
      delayout = esmf_delayoutcreate(petmap, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return  ! bail out
      ! rsd this assumes tripole grid, but sometimes in CESM a bipole
      ! grid is used -- need to introduce conditional logic here
      allocate(connectionlist(2))
      ! bipolar boundary condition at top row: nyg
      call esmf_distgridconnectionset(connectionlist(1), tileindexa=1, &
           tileindexb=1, positionvector=(/nxg+1, 2*nyg+1/), &
           orientationvector=(/-1, -2/), rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return  ! bail out
      ! periodic boundary condition along first dimension
      call esmf_distgridconnectionset(connectionlist(2), tileindexa=1, &
           tileindexb=1, positionvector=(/nxg, 0/), rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return
      distgrid = esmf_distgridcreate(minindex=(/1,1/), maxindex=(/nxg,nyg/), &
           !        indexflag = ESMF_INDEX_DELOCAL, &
           deblocklist=deblocklist, &
           !        deLabelList=deLabelList, &
           delayout=delayout, &
           connectionlist=connectionlist, &
           rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return
      deallocate(xb,xe,yb,ye,pe)
      deallocate(connectionlist)
      deallocate(delabellist)
      deallocate(deblocklist)
      deallocate(petmap)
      call esmf_distgridget(distgrid=distgrid, localde=0, elementcount=cnt, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return
      allocate(indexlist(cnt))
      write(tmpstr,'(a,i8)') subname//' distgrid cnt= ',cnt
      call esmf_logwrite(trim(tmpstr), esmf_logmsg_info, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return
      call esmf_distgridget(distgrid=distgrid, localde=0, seqindexlist=indexlist, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return
      write(tmpstr,'(a,4i8)') subname//' distgrid list= ',&
           indexlist(1),indexlist(cnt),minval(indexlist), maxval(indexlist)
      call esmf_logwrite(trim(tmpstr), esmf_logmsg_info, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return
      deallocate(indexlist)
      ! create grid
      gridin = esmf_gridcreate(distgrid=distgrid, &
           gridedgelwidth=(/0,0/), gridedgeuwidth=(/0,1/), &
           coordsys = esmf_coordsys_sph_deg, &
           rc = rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return
      call esmf_gridaddcoord(gridin, staggerloc=esmf_staggerloc_center, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return
      call esmf_gridaddcoord(gridin, staggerloc=esmf_staggerloc_corner, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return
      call esmf_gridadditem(gridin, itemflag=esmf_griditem_mask, itemtypekind=esmf_typekind_i4, &
           staggerloc=esmf_staggerloc_center, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return
      ! Attach area to the Grid optionally. By default the cell areas are computed.
      if(grid_attach_area) then
         call esmf_gridadditem(gridin, itemflag=esmf_griditem_area, itemtypekind=esmf_typekind_r8, &
              staggerloc=esmf_staggerloc_center, rc=rc)
         if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
            line=__line__, &
            file=__file__)) &
            return
      endif
      call esmf_gridgetcoord(gridin, coorddim=1, &
           staggerloc=esmf_staggerloc_center, &
           farrayptr=dataptr_xcen, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return
      call esmf_gridgetcoord(gridin, coorddim=2, &
           staggerloc=esmf_staggerloc_center, &
           farrayptr=dataptr_ycen, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return
      call esmf_gridgetcoord(gridin, coorddim=1, &
           staggerloc=esmf_staggerloc_corner, &
           farrayptr=dataptr_xcor, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return
      call esmf_gridgetcoord(gridin, coorddim=2, &
           staggerloc=esmf_staggerloc_corner, &
           farrayptr=dataptr_ycor, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return
      call esmf_gridgetitem(gridin, itemflag=esmf_griditem_mask, &
           staggerloc=esmf_staggerloc_center, &
           farrayptr=dataptr_mask, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return
      if(grid_attach_area) then
        call esmf_gridgetitem(gridin, itemflag=esmf_griditem_area, &
              staggerloc=esmf_staggerloc_center, &
              farrayptr=dataptr_area, rc=rc)
        if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return
      endif
      ! load up area, mask, center and corner values
      ! area, mask, and centers should be same size in mom and esmf grid
      ! corner points may not be, need to offset corner points by 1 in i and j
      ! retrieve these values directly from ocean_grid, which contains halo
      ! values for j=0 and wrap-around in i. on tripole seam, decomposition
      ! domains are 1 larger in j; to load corner values need to loop one extra row
      call mpp_get_compute_domain(ocean_public%domain, isc, iec, jsc, jec)
      lbnd1 = lbound(dataptr_mask,1)
      ubnd1 = ubound(dataptr_mask,1)
      lbnd2 = lbound(dataptr_mask,2)
      ubnd2 = ubound(dataptr_mask,2)
      lbnd3 = lbound(dataptr_xcor,1)
      ubnd3 = ubound(dataptr_xcor,1)
      lbnd4 = lbound(dataptr_xcor,2)
      ubnd4 = ubound(dataptr_xcor,2)
      write(tmpstr,*) subname//' iscjsc = ',isc,iec,jsc,jec
      call esmf_logwrite(trim(tmpstr), esmf_logmsg_info, rc=rc)
      write(tmpstr,*) subname//' lbub12 = ',lbnd1,ubnd1,lbnd2,ubnd2
      call esmf_logwrite(trim(tmpstr), esmf_logmsg_info, rc=rc)
      write(tmpstr,*) subname//' lbub34 = ',lbnd3,ubnd3,lbnd4,ubnd4
      call esmf_logwrite(trim(tmpstr), esmf_logmsg_info, rc=rc)
      if (iec-isc /= ubnd1-lbnd1 .or. jec-jsc /= ubnd2-lbnd2) then
         call esmf_logseterror(esmf_rc_arg_bad, &
              msg=subname//": fld and grid do not have the same size.", &
              line=__line__, file=__file__, rctoreturn=rc)
         return
      endif
      do j = jsc, jec
        j1 = j + lbnd2 - jsc
        jg = j + ocean_grid%jsc - jsc
        do i = isc, iec
          i1 = i + lbnd1 - isc
          ig = i + ocean_grid%isc - isc
          dataptr_mask(i1,j1)  = ocean_grid%mask2dT(ig,jg)
          dataptr_xcen(i1,j1)  = ocean_grid%geolonT(ig,jg)
          dataptr_ycen(i1,j1)  = ocean_grid%geolatT(ig,jg)
          if(grid_attach_area) then
            dataptr_area(i1,j1)  = ocean_grid%areaT(ig,jg)
          endif
        enddo
      enddo
      jlast = jec
      if(jec == nyg)jlast = jec+1
      do j = jsc, jlast
        j1 = j + lbnd4 - jsc
        jg = j + ocean_grid%jsc - jsc - 1
        do i = isc, iec
          i1 = i + lbnd3 - isc
          ig = i + ocean_grid%isc - isc - 1
          dataptr_xcor(i1,j1)  = ocean_grid%geolonBu(ig,jg)
          dataptr_ycor(i1,j1)  = ocean_grid%geolatBu(ig,jg)
        enddo
      enddo
      write(tmpstr,*) subname//' mask = ',minval(dataptr_mask),maxval(dataptr_mask)
      call esmf_logwrite(trim(tmpstr), esmf_logmsg_info, rc=rc)
      if(grid_attach_area) then
         write(tmpstr,*) subname//' area = ',minval(dataptr_area),maxval(dataptr_area)
         call esmf_logwrite(trim(tmpstr), esmf_logmsg_info, rc=rc)
      endif
      write(tmpstr,*) subname//' xcen = ',minval(dataptr_xcen),maxval(dataptr_xcen)
      call esmf_logwrite(trim(tmpstr), esmf_logmsg_info, rc=rc)
      write(tmpstr,*) subname//' ycen = ',minval(dataptr_ycen),maxval(dataptr_ycen)
      call esmf_logwrite(trim(tmpstr), esmf_logmsg_info, rc=rc)
      write(tmpstr,*) subname//' xcor = ',minval(dataptr_xcor),maxval(dataptr_xcor)
      call esmf_logwrite(trim(tmpstr), esmf_logmsg_info, rc=rc)
      write(tmpstr,*) subname//' ycor = ',minval(dataptr_ycor),maxval(dataptr_ycor)
      call esmf_logwrite(trim(tmpstr), esmf_logmsg_info, rc=rc)
      gridout = gridin ! for now out same as in
      call mom_realizefields(importstate, fldstoocn_num, fldstoocn, "Ocn import", grid=gridin, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return
      call mom_realizefields(exportstate, fldsfrocn_num, fldsfrocn, "Ocn export", grid=gridout, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return
   endif
   !---------------------------------
   ! set scalar data in export state
   !---------------------------------
   if (len_trim(scalar_field_name) > 0) then
      call state_setscalar(dble(nxg),scalar_field_idx_grid_nx, exportstate, localpet, &
          scalar_field_name, scalar_field_count, rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return
      call state_setscalar(dble(nyg),scalar_field_idx_grid_ny, exportstate, localpet, &
           scalar_field_name, scalar_field_count, rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return
   endif
   !---------------------------------
   ! Set module variable geomtype in MOM_cap_methods
   !---------------------------------
   call mom_set_geomtype(geomtype)
   !---------------------------------
   ! write out diagnostics
   !---------------------------------
   !call NUOPC_Write(exportState, fileNamePrefix='post_realize_field_ocn_export_', &
   !     timeslice=1, relaxedFlag=.true., rc=rc)
   !if (ESMF_LogFoundError(rcToCheck=rc, msg=ESMF_LOGERR_PASSTHRU, &
   !     line=__LINE__, &
   !     file=__FILE__)) &
   !     return  ! bail out
References debug, fldsfrocn, fldsfrocn_num, fldstoocn, fldstoocn_num, geomtype, mom_ocean_model_nuopc::get_eps_omesh(), mom_grid::get_global_grid_size(), mom_ocean_model_nuopc::get_ocean_grid(), grid_attach_area, logunit, mom_error_handler::mom_error(), mom_realizefields(), mom_cap_methods::mom_set_geomtype(), scalar_field_count, scalar_field_idx_grid_nx, scalar_field_idx_grid_ny, scalar_field_name, shr_file_setlogunit(), state_setscalar(), and tmpstr.
Referenced by setservices().
modeladvance()
subroutine mom_cap_mod::modeladvance (type(esmf_gridcomp) gcomp, integer, intent(out) rc) private
Called by NUOPC to advance the model a single timestep.
Parameters
gcomp an ESMF_GridComp object
rc return code
gcomp ESMF_GridComp object
[out] rc return code
Definition at line 1870 of file mom_cap.F90.
   type(ESMF_GridComp)                    :: gcomp !< ESMF_GridComp object
   integer, intent(out)                   :: rc    !< return code
   ! local variables
   integer                                :: userRc
   logical                                :: existflag, isPresent, isSet
   logical                                :: do_advance = .true.
   type(ESMF_Clock)                       :: clock!< ESMF Clock class definition
   type(ESMF_Alarm)                       :: alarm
   type(ESMF_State)                       :: importState, exportState
   type(ESMF_Time)                        :: currTime
   type(ESMF_TimeInterval)                :: timeStep
   type(ESMF_Time)                        :: startTime
   type(ESMF_TimeInterval)                :: time_elapsed
   integer(ESMF_KIND_I8)                  :: n_interval, time_elapsed_sec
   character(len=64)                      :: timestamp
   type (ocean_public_type),      pointer :: ocean_public       => null()
   type (ocean_state_type),       pointer :: ocean_state        => null()
   type(ice_ocean_boundary_type), pointer :: Ice_ocean_boundary => null()
   type(ocean_internalstate_wrapper)      :: ocean_internalstate
   type(ocean_grid_type)        , pointer :: ocean_grid
   type(time_type)                        :: Time
   type(time_type)                        :: Time_step_coupled
   type(time_type)                        :: Time_restart_current
   integer                                :: dth, dtm, dts
   integer                                :: nc
   type(ESMF_Time)                        :: MyTime
   integer                                :: seconds, day, year, month, hour, minute
   character(ESMF_MAXSTR)                 :: restartname, cvalue
   character(240)                         :: msgString
   character(len=*),parameter             :: subname='(MOM_cap:ModelAdvance)'
   rc = esmf_success
   if(profile_memory) call esmf_vmlogmeminfo("Entering MOM Model_ADVANCE: ")
   call shr_file_setlogunit (logunit)
   ! query the Component for its clock, importState and exportState
   call esmf_gridcompget(gcomp, clock=clock, importstate=importstate, &
     exportstate=exportstate, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   ! HERE THE MODEL ADVANCES: currTime -> currTime + timeStep
   call esmf_clockprint(clock, options="currTime", &
     prestring="------>Advancing OCN from: ", unit=msgstring, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   call esmf_logwrite(subname//trim(msgstring), esmf_logmsg_info, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   call esmf_clockget(clock, starttime=starttime, currtime=currtime, &
     timestep=timestep, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   call esmf_timeprint(currtime + timestep, &
     prestring="--------------------------------> to: ", unit=msgstring, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   call esmf_logwrite(trim(msgstring), esmf_logmsg_info, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   time_step_coupled = esmf2fms_time(timestep)
   time = esmf2fms_time(currtime)
   !---------------
   ! Apply ocean lag for startup runs:
   !---------------
   if (cesm_coupled) then
     if (trim(runtype) == "initial") then
       ! Do not call MOM6 timestepping routine if the first cpl tstep of a startup run
       if (currtime == starttime) then
         call esmf_logwrite("MOM6 - Skipping the first coupling timestep", esmf_logmsg_info, rc=rc)
         if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
           line=__line__, &
           file=__file__)) &
           return  ! bail out
         do_advance = .false.
       else
         do_advance = .true.
       endif
       if (do_advance) then
          ! If the second cpl tstep of a startup run, step back a cpl tstep and advance for two cpl tsteps
          if (currtime == starttime + timestep) then
             call esmf_logwrite("MOM6 - Stepping back one coupling timestep", esmf_logmsg_info, rc=rc)
             if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
                  line=__line__, &
                  file=__file__)) &
                  return  ! bail out
             time = esmf2fms_time(currtime-timestep) ! i.e., startTime
             call esmf_logwrite("MOM6 - doubling the coupling timestep", esmf_logmsg_info, rc=rc)
             if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
                  line=__line__, &
                  file=__file__)) &
                  return  ! bail out
             time_step_coupled = 2 * esmf2fms_time(timestep)
          endif
       end if
     endif
   endif
   if (do_advance) then
      call esmf_gridcompgetinternalstate(gcomp, ocean_internalstate, rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
           line=__line__, &
           file=__file__)) &
           return  ! bail out
      ice_ocean_boundary => ocean_internalstate%ptr%ice_ocean_boundary_type_ptr
      ocean_public       => ocean_internalstate%ptr%ocean_public_type_ptr
      ocean_state        => ocean_internalstate%ptr%ocean_state_type_ptr
      !---------------
      ! Write diagnostics for import
      !---------------
      if (write_diagnostics) then
         call nuopc_write(importstate, filenameprefix='field_ocn_import_', &
              timeslice=import_slice, relaxedflag=.true., rc=rc)
         if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
              line=__line__, &
              file=__file__)) &
              return  ! bail out
         import_slice = import_slice + 1
      endif
      !---------------
      ! Get ocean grid
      !---------------
      call get_ocean_grid(ocean_state, ocean_grid)
      !---------------
      ! Import data
      !---------------
      call mom_import(ocean_public, ocean_grid, importstate, ice_ocean_boundary, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
           line=__line__, &
           file=__file__)) &
           return  ! bail out
      !---------------
      ! Update MOM6
      !---------------
      if(profile_memory) call esmf_vmlogmeminfo("Entering MOM update_ocean_model: ")
      call update_ocean_model(ice_ocean_boundary, ocean_state, ocean_public, time, time_step_coupled)
      if(profile_memory) call esmf_vmlogmeminfo("Leaving MOM update_ocean_model: ")
      !---------------
      ! Export Data
      !---------------
      call mom_export(ocean_public, ocean_grid, ocean_state, exportstate, clock, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
           line=__line__, &
           file=__file__)) &
           return  ! bail out
   endif
   !---------------
   ! If restart alarm is ringing - write restart file
   !---------------
   call esmf_clockgetalarm(clock, alarmname='alarm_restart', alarm=alarm, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
       line=__line__, &
       file=__file__)) &
       return  ! bail out
   if (esmf_alarmisringing(alarm, rc=rc)) then
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return  ! bail out
      call esmf_alarmringeroff(alarm, rc=rc )
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return  ! bail out
      ! call into system specific method to get desired restart filename
      restartname = ""
      call esmf_methodexecute(gcomp, label="GetRestartFileToWrite", &
           existflag=existflag, userrc=userrc, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg="Error executing user method to get restart filename", &
          line=__line__, &
          file=__file__)) &
          return  ! bail out
      if (esmf_logfounderror(rctocheck=userrc, msg="Error in method to get restart filename", &
           line=__line__, &
           file=__file__)) &
           return  ! bail out
      if (existflag) then
         call esmf_logwrite("MOM_cap: called user GetRestartFileToWrite method", esmf_logmsg_info, rc=rc)
         if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
             line=__line__, &
             file=__file__)) &
             return  ! bail out
         call nuopc_compattributeget(gcomp, name='RestartFileToWrite', &
              ispresent=ispresent, isset=isset, value=cvalue, rc=rc)
         if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
             line=__line__, &
             file=__file__)) &
             return  ! bail out
         if (ispresent .and. isset) then
            restartname = trim(cvalue)
            call esmf_logwrite("MOM_cap: User RestartFileToWrite: "//trim(restartname), esmf_logmsg_info, rc=rc)
            if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
                line=__line__, &
                file=__file__)) &
                return  ! bail out
         endif
      endif
      if (len_trim(restartname) == 0) then
         ! none provided, so use a default restart filename
         call esmf_clockgetnexttime(clock, mytime, rc=rc)
         if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
             line=__line__, &
             file=__file__)) &
             return  ! bail out
         call esmf_timeget (mytime, yy=year, mm=month, dd=day, &
              h=hour, m=minute, s=seconds, rc=rc )
         if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
             line=__line__, &
             file=__file__)) &
             return  ! bail out
         write(restartname,'(A,".mom6.r.",I4.4,"-",I2.2,"-",I2.2,"-",I2.2,"-",I2.2,"-",I2.2)') &
               "ocn", year, month, day, hour, minute, seconds
         call esmf_logwrite("MOM_cap: Using default restart filename:  "//trim(restartname), esmf_logmsg_info, rc=rc)
         if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
             line=__line__, &
             file=__file__)) &
             return  ! bail out
      endif
      ! TODO: address if this requirement is being met for the DA group
      ! Optionally write restart files when currTime-startTime is integer multiples of restart_interval
      ! if (restart_interval > 0 ) then
      !   time_elapsed = currTime - startTime
      !   call ESMF_TimeIntervalGet(time_elapsed, s_i8=time_elapsed_sec, rc=rc)
      !   if (ESMF_LogFoundError(rcToCheck=rc, msg=ESMF_LOGERR_PASSTHRU, &
      !     line=__LINE__, &
      !     file=__FILE__)) &
      !     return  ! bail out
      !   n_interval = time_elapsed_sec / restart_interval
      !   if ((n_interval .gt. 0) .and. (n_interval*restart_interval == time_elapsed_sec)) then
      !       time_restart_current = esmf2fms_time(currTime)
      !       timestamp = date_to_string(time_restart_current)
      !       call ESMF_LogWrite("MOM: Writing restart at "//trim(timestamp), ESMF_LOGMSG_INFO, rc=rc)
      !       write(*,*) 'calling ocean_model_restart'
      !       call ocean_model_restart(ocean_state, timestamp)
      !   endif
      ! endif
      ! write restart file(s)
      call ocean_model_restart(ocean_state, restartname=restartname)
      if (is_root_pe()) then
        write(logunit,*) subname//' writing restart file ',trim(restartname)
      endif
   endif
   !---------------
   ! Write diagnostics
   !---------------
   if (write_diagnostics) then
      call nuopc_write(exportstate, filenameprefix='field_ocn_export_', &
           timeslice=export_slice, relaxedflag=.true., rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
          line=__line__, &
          file=__file__)) &
          return  ! bail out
      export_slice = export_slice + 1
   endif
   if(profile_memory) call esmf_vmlogmeminfo("Leaving MOM Model_ADVANCE: ")
References cesm_coupled, export_slice, mom_ocean_model_nuopc::get_ocean_grid(), import_slice, mom_error_handler::is_root_pe(), logunit, mom_cap_methods::mom_export(), mom_cap_methods::mom_import(), profile_memory, runtype, shr_file_setlogunit(), and write_diagnostics.
Referenced by setservices().
modelsetrunclock()
subroutine mom_cap_mod::modelsetrunclock (type(esmf_gridcomp) gcomp, integer, intent(out) rc) private
Definition at line 2180 of file mom_cap.F90.
   type(ESMF_GridComp)  :: gcomp
   integer, intent(out) :: rc
   ! local variables
   type(ESMF_Clock)         :: mclock, dclock
   type(ESMF_Time)          :: mcurrtime, dcurrtime
   type(ESMF_Time)          :: mstoptime
   type(ESMF_TimeInterval)  :: mtimestep, dtimestep
   character(len=128)       :: mtimestring, dtimestring
   character(len=256)       :: cvalue
   character(len=256)       :: restart_option ! Restart option units
   integer                  :: restart_n      ! Number until restart interval
   integer                  :: restart_ymd    ! Restart date (YYYYMMDD)
   type(ESMF_ALARM)         :: restart_alarm
   logical                  :: isPresent, isSet
   logical                  :: first_time = .true.
   character(len=*),parameter :: subname='MOM_cap:(ModelSetRunClock) '
   !--------------------------------
   rc = esmf_success
   ! query the Component for its clock, importState and exportState
   call nuopc_modelget(gcomp, driverclock=dclock, modelclock=mclock, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   call esmf_clockget(dclock, currtime=dcurrtime, timestep=dtimestep, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   call esmf_clockget(mclock, currtime=mcurrtime, timestep=mtimestep, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   !--------------------------------
   ! check that the current time in the model and driver are the same
   !--------------------------------
   if (mcurrtime /= dcurrtime) then
     call esmf_timeget(dcurrtime, timestring=dtimestring, rc=rc)
     if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
       line=__line__, &
       file=__file__)) &
       return  ! bail out
     call esmf_timeget(mcurrtime, timestring=mtimestring, rc=rc)
     if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
       line=__line__, &
       file=__file__)) &
       return  ! bail out
     call esmf_logseterror(esmf_rc_val_wrong, &
          msg=subname//": ERROR in time consistency: "//trim(dtimestring)//" != "//trim(mtimestring),  &
          line=__line__, file=__file__, rctoreturn=rc)
     return
   endif
   !--------------------------------
   ! force model clock currtime and timestep to match driver and set stoptime
   !--------------------------------
   mstoptime = mcurrtime + dtimestep
   call esmf_clockset(mclock, currtime=dcurrtime, timestep=dtimestep, stoptime=mstoptime, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   if (first_time) then
      !--------------------------------
      ! set restart alarm
      !--------------------------------
      ! defaults
      restart_n = 0
      restart_ymd = 0
      call nuopc_compattributeget(gcomp, name="restart_option", ispresent=ispresent, &
           isset=isset, value=restart_option, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
           line=__line__, &
           file=__file__)) &
           return  ! bail out
      if (ispresent .and. isset) then
         call nuopc_compattributeget(gcomp,  name="restart_n", value=cvalue, &
              ispresent=ispresent, isset=isset, rc=rc)
         if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
              line=__line__, &
              file=__file__)) &
              return  ! bail out
         if (ispresent .and. isset) then
            read(cvalue,*) restart_n
         endif
         call nuopc_compattributeget(gcomp, name="restart_ymd", value=cvalue, &
              ispresent=ispresent, isset=isset, rc=rc)
         if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
              line=__line__, &
              file=__file__)) &
              return  ! bail out
         if (ispresent .and. isset) then
            read(cvalue,*) restart_ymd
         endif
      else
         restart_option = "none"
      endif
      call alarminit(mclock, &
           alarm   = restart_alarm,         &
           option  = trim(restart_option),  &
           opt_n   = restart_n,             &
           opt_ymd = restart_ymd,           &
           reftime = mcurrtime,             &
           alarmname = 'alarm_restart', rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
           line=__line__, &
           file=__file__)) &
           return  ! bail out
      call esmf_alarmset(restart_alarm, clock=mclock, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
           line=__line__, &
           file=__file__)) &
           return  ! bail out
      first_time = .false.
      call esmf_logwrite(subname//" Set restart option = "//restart_option, &
           esmf_logmsg_info, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
           line=__line__, &
           file=__file__)) &
           return  ! bail out
   endif
   !--------------------------------
   ! Advance model clock to trigger alarms then reset model clock back to currtime
   !--------------------------------
   call esmf_clockadvance(mclock,rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   call esmf_clockset(mclock, currtime=dcurrtime, timestep=dtimestep, stoptime=mstoptime, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
References mom_cap_time::alarminit().
Referenced by setservices().
mom_realizefields()
subroutine mom_cap_mod::mom_realizefields (type(esmf_state), intent(inout) state, integer, intent(in) nfields, type(fld_list_type), dimension(:), intent(inout) field_defs, character(len=*), intent(in) tag, type(esmf_grid), intent(in), optional grid, type(esmf_mesh), intent(in), optional mesh, integer, intent(inout) rc) private
Realize the import and export fields using either a grid or a mesh.
Parameters
[in,out] state ESMF_State object for import/export fields.
[in] nfields Number of fields.
[in,out] field_defs Structure with field's information.
[in] tag Import or export.
[in] grid ESMF grid.
[in] mesh ESMF mesh.
[in,out] rc Return code.
Definition at line 2440 of file mom_cap.F90.
   type(ESMF_State)    , intent(inout)        :: state !< ESMF_State object for
                                                       !! import/export fields.
   integer             , intent(in)           :: nfields !< Number of fields.
   type(fld_list_type) , intent(inout)        :: field_defs(:) !< Structure with field's
                                                               !! information.
   character(len=*)    , intent(in)           :: tag !< Import or export.
   type(ESMF_Grid)     , intent(in), optional :: grid!< ESMF grid.
   type(ESMF_Mesh)     , intent(in), optional :: mesh!< ESMF mesh.
   integer             , intent(inout)        :: rc  !< Return code.
   ! local variables
   integer                     :: i
   type(ESMF_Field)            :: field
   real(ESMF_KIND_R8), pointer :: fldptr1d(:)   ! for mesh
   real(ESMF_KIND_R8), pointer :: fldptr2d(:,:) ! for grid
   character(len=*),parameter  :: subname='(MOM_cap:MOM_RealizeFields)'
   !--------------------------------------------------------
   rc = esmf_success
   do i = 1, nfields
     if (nuopc_isconnected(state, fieldname=field_defs(i)%shortname)) then
       if (field_defs(i)%shortname == scalar_field_name) then
         call esmf_logwrite(subname // tag // " Field "// trim(field_defs(i)%stdname) // " is connected on root pe.", &
           esmf_logmsg_info, &
           line=__line__, &
           file=__file__, &
           rc=rc)
         call setscalarfield(field, rc)
         if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
           line=__line__, &
           file=__file__)) &
           return  ! bail out
       else
         call esmf_logwrite(subname // tag // " Field "// trim(field_defs(i)%stdname) // " is connected.", &
           esmf_logmsg_info, &
           line=__line__, &
           file=__file__, &
           rc=rc)
         if (present(grid)) then
            field = esmf_fieldcreate(grid, esmf_typekind_r8, indexflag=esmf_index_delocal, &
                 name=field_defs(i)%shortname, rc=rc)
            if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
                 line=__line__, &
                 file=__file__)) &
                 return  ! bail out
            ! initialize fldptr to zero
            call esmf_fieldget(field, farrayptr=fldptr2d, rc=rc)
            if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
                 line=__line__, &
                 file=__file__)) &
                 return  ! bail out
            fldptr2d(:,:) = 0.0
         else if (present(mesh)) then
            field = esmf_fieldcreate(mesh=mesh, typekind=esmf_typekind_r8, meshloc=esmf_meshloc_element, &
                 name=field_defs(i)%shortname, rc=rc)
            if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
                 line=__line__, &
                 file=__file__)) &
                 return  ! bail out
            ! initialize fldptr to zero
            call esmf_fieldget(field, farrayptr=fldptr1d, rc=rc)
            if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
                 line=__line__, &
                 file=__file__)) &
                 return  ! bail out
            fldptr1d(:) = 0.0
         endif
       endif
       ! Realize connected field
       call nuopc_realize(state, field=field, rc=rc)
       if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
         line=__line__, &
         file=__file__)) &
         return  ! bail out
     else ! field is not connected
       call esmf_logwrite(subname // tag // " Field "// trim(field_defs(i)%stdname) // " is not connected.", &
         esmf_logmsg_info, &
         line=__line__, &
         file=__file__, &
         rc=rc)
       ! remove a not connected Field from State
       call esmf_stateremove(state, (/field_defs(i)%shortname/), rc=rc)
       if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
         line=__line__, &
         file=__file__)) &
         return  ! bail out
     endif
   enddo
 contains  !- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   subroutine setscalarfield(field, rc)
     ! create a field with scalar data on the root pe
     type(ESMF_Field), intent(inout)  :: field
     integer,          intent(inout)  :: rc
     ! local variables
     type(ESMF_Distgrid) :: distgrid
     type(ESMF_Grid)     :: grid
     character(len=*), parameter :: subname='(MOM_cap:SetScalarField)'
     rc = esmf_success
     ! create a DistGrid with a single index space element, which gets mapped onto DE 0.
     distgrid = esmf_distgridcreate(minindex=(/1/), maxindex=(/1/), rc=rc)
     if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
         line=__line__, &
         file=__file__)) &
         return  ! bail out
     grid = esmf_gridcreate(distgrid, rc=rc)
     if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
         line=__line__, &
         file=__file__)) &
         return  ! bail out
     ! num of scalar values
     field = esmf_fieldcreate(name=trim(scalar_field_name), grid=grid, typekind=esmf_typekind_r8, &
          ungriddedlbound=(/1/), ungriddedubound=(/scalar_field_count/), gridtofieldmap=(/2/), rc=rc)
     if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
         line=__line__, &
         file=__file__)) &
         return  ! bail out
   end subroutine setscalarfield
References scalar_field_name, and setscalarfield().
Referenced by initializerealize().
ocean_model_finalize()
subroutine mom_cap_mod::ocean_model_finalize (type(esmf_gridcomp) gcomp, integer, intent(out) rc) private
Called by NUOPC at the end of the run to clean up.
Parameters
gcomp an ESMF_GridComp object
rc return code
gcomp ESMF_GridComp object
[out] rc return code
Definition at line 2347 of file mom_cap.F90.
   type(ESMF_GridComp)  :: gcomp !< ESMF_GridComp object
   integer, intent(out) :: rc    !< return code
   ! local variables
   type (ocean_public_type),      pointer :: ocean_public
   type (ocean_state_type),       pointer :: ocean_state
   type(ocean_internalstate_wrapper)      :: ocean_internalstate
   type(TIME_TYPE)                        :: Time
   type(ESMF_Clock)                       :: clock
   type(ESMF_Time)                        :: currTime
   character(len=64)                      :: timestamp
   character(len=*),parameter  :: subname='(MOM_cap:ocean_model_finalize)'
   write(*,*) 'MOM: --- finalize called ---'
   rc = esmf_success
   call esmf_gridcompgetinternalstate(gcomp, ocean_internalstate, rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   ocean_public => ocean_internalstate%ptr%ocean_public_type_ptr
   ocean_state  => ocean_internalstate%ptr%ocean_state_type_ptr
   call nuopc_modelget(gcomp, modelclock=clock, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   call esmf_clockget(clock, currtime=currtime, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   time = esmf2fms_time(currtime)
   if (cesm_coupled) then
      call ocean_model_end(ocean_public, ocean_state, time, write_restart=.false.)
   else
      call ocean_model_end(ocean_public, ocean_state, time, write_restart=.true.)
   endif
   call field_manager_end()
   call fms_io_exit()
   call fms_end()
   write(*,*) 'MOM: --- completed ---'
References cesm_coupled.
Referenced by setservices().
setservices()
subroutine, public mom_cap_mod::setservices (type(esmf_gridcomp) gcomp, integer, intent(out) rc)
NUOPC SetService method is the only public entry point. SetServices registers all of the user-provided subroutines in the module with the NUOPC layer.
Parameters
gcomp an ESMF_GridComp object
rc return code
gcomp an ESMF_GridComp object
[out] rc return code
Definition at line 464 of file mom_cap.F90.
   type(ESMF_GridComp)  :: gcomp !< an ESMF_GridComp object
   integer, intent(out) :: rc    !< return code
   ! local variables
   character(len=*),parameter  :: subname='(MOM_cap:SetServices)'
   rc = esmf_success
   ! the NUOPC model component will register the generic methods
   call nuopc_compderive(gcomp, model_routine_ss, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   ! switching to IPD versions
   call esmf_gridcompsetentrypoint(gcomp, esmf_method_initialize, &
     userroutine=initializep0, phase=0, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   ! set entry point for methods that require specific implementation
   call nuopc_compsetentrypoint(gcomp, esmf_method_initialize, &
     phaselabellist=(/"IPDv03p1"/), userroutine=initializeadvertise, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   call nuopc_compsetentrypoint(gcomp, esmf_method_initialize, &
     phaselabellist=(/"IPDv03p3"/), userroutine=initializerealize, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   !------------------
   ! attach specializing method(s)
   !------------------
   call nuopc_compspecialize(gcomp, speclabel=model_label_datainitialize, &
     specroutine=datainitialize, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   call nuopc_compspecialize(gcomp, speclabel=model_label_advance, &
     specroutine=modeladvance, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   call esmf_methodremove(gcomp, label=model_label_setrunclock, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   call nuopc_compspecialize(gcomp, speclabel=model_label_setrunclock, &
        specroutine=modelsetrunclock, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
   call nuopc_compspecialize(gcomp, speclabel=model_label_finalize, &
     specroutine=ocean_model_finalize, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return  ! bail out
References datainitialize(), initializeadvertise(), initializep0(), initializerealize(), modeladvance(), modelsetrunclock(), and ocean_model_finalize().
shr_file_getlogunit()
subroutine mom_cap_mod::shr_file_getlogunit (integer, intent(in) nunit) private
Definition at line 2631 of file mom_cap.F90.
   integer, intent(in) :: nunit
   ! do nothing for this stub - its just here to replace
   ! having cppdefs in the main program
shr_file_setlogunit()
subroutine mom_cap_mod::shr_file_setlogunit (integer, intent(in) nunit) private
Definition at line 2625 of file mom_cap.F90.
   integer, intent(in) :: nunit
   ! do nothing for this stub - its just here to replace
   ! having cppdefs in the main program
Referenced by initializerealize(), and modeladvance().
state_setscalar()
subroutine mom_cap_mod::state_setscalar (real(esmf_kind_r8), intent(in) value, integer, intent(in) scalar_id, type(esmf_state), intent(inout) State, integer, intent(in) mytask, character(len=*), intent(in) scalar_name, integer, intent(in) scalar_count, integer, intent(inout) rc) private
Set scalar data from state for a particula name.
Parameters
[in,out] rc return code
Definition at line 2403 of file mom_cap.F90.
   real(ESMF_KIND_R8),intent(in)     :: value
   integer,           intent(in)     :: scalar_id
   type(ESMF_State),  intent(inout)  :: State
   integer,           intent(in)     :: mytask
   character(len=*),  intent(in)     :: scalar_name
   integer,           intent(in)     :: scalar_count
   integer,           intent(inout)  :: rc           !< return code
   ! local variables
   type(ESMF_Field)                :: field
   real(ESMF_KIND_R8), pointer     :: farrayptr(:,:)
   character(len=*), parameter     :: subname='(MOM_cap:State_SetScalar)'
   !--------------------------------------------------------
   rc = esmf_success
   call esmf_stateget(state, itemname=trim(scalar_name), field=field, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, line=__line__, file=u_file_u)) return
   if (mytask == 0) then
     call esmf_fieldget(field, farrayptr=farrayptr, rc=rc)
     if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, line=__line__, file=u_file_u)) return
     if (scalar_id < 0 .or. scalar_id > scalar_count) then
        call esmf_logseterror(esmf_rc_arg_bad, &
             msg=subname//": ERROR in scalar_id", &
             line=__line__, file=__file__, rctoreturn=rc)
        return
     endif
     farrayptr(scalar_id,1) = value
   endif
References u_file_u.
Referenced by initializerealize().
Variable Documentation
cesm_coupled
logical mom_cap_mod::cesm_coupled = .true. private
Definition at line 448 of file mom_cap.F90.
 logical :: cesm_coupled = .true.
Referenced by datainitialize(), initializeadvertise(), modeladvance(), and ocean_model_finalize().
debug
integer mom_cap_mod::debug = 0 private
Definition at line 431 of file mom_cap.F90.
 integer              :: debug = 0
Referenced by initializerealize().
export_slice
integer mom_cap_mod::export_slice = 1 private
Definition at line 433 of file mom_cap.F90.
 integer              :: export_slice = 1
Referenced by modeladvance().
fldsfrocn
type (fld_list_type), dimension(fldsmax) mom_cap_mod::fldsfrocn private
Definition at line 429 of file mom_cap.F90.
 type (fld_list_type) :: fldsFrOcn(fldsMax)
Referenced by initializeadvertise(), and initializerealize().
fldsfrocn_num
integer mom_cap_mod::fldsfrocn_num = 0 private
Definition at line 428 of file mom_cap.F90.
 integer              :: fldsFrOcn_num = 0
Referenced by initializeadvertise(), and initializerealize().
fldsmax
integer, parameter mom_cap_mod::fldsmax = 100 private
Definition at line 425 of file mom_cap.F90.
 integer,parameter    :: fldsMax = 100
Referenced by fld_list_add().
fldstoocn
type (fld_list_type), dimension(fldsmax) mom_cap_mod::fldstoocn private
Definition at line 427 of file mom_cap.F90.
 type (fld_list_type) :: fldsToOcn(fldsMax)
Referenced by initializeadvertise(), and initializerealize().
fldstoocn_num
integer mom_cap_mod::fldstoocn_num = 0 private
Definition at line 426 of file mom_cap.F90.
 integer              :: fldsToOcn_num = 0
Referenced by initializeadvertise(), and initializerealize().
geomtype
type(esmf_geomtype_flag) mom_cap_mod::geomtype = ESMF_GEOMTYPE_MESH private
Definition at line 449 of file mom_cap.F90.
 type(ESMF_GeomType_Flag) :: geomtype = esmf_geomtype_mesh
Referenced by initializerealize().
grid_attach_area
logical mom_cap_mod::grid_attach_area = .false. private
Definition at line 439 of file mom_cap.F90.
 logical              :: grid_attach_area = .false.
Referenced by initializep0(), and initializerealize().
import_slice
integer mom_cap_mod::import_slice = 1 private
Definition at line 432 of file mom_cap.F90.
 integer              :: import_slice = 1
Referenced by datainitialize(), and modeladvance().
logunit
integer mom_cap_mod::logunit private
stdout logging unit number
Definition at line 437 of file mom_cap.F90.
 integer              :: logunit  !< stdout logging unit number
Referenced by initializeadvertise(), initializerealize(), and modeladvance().
profile_memory
logical mom_cap_mod::profile_memory = .true. private
Definition at line 438 of file mom_cap.F90.
 logical              :: profile_memory = .true.
Referenced by initializep0(), and modeladvance().
runtype
character(len=32) mom_cap_mod::runtype private
run type
Definition at line 436 of file mom_cap.F90.
 character(len=32)    :: runtype  !< run type
Referenced by initializeadvertise(), and modeladvance().
scalar_field_count
integer mom_cap_mod::scalar_field_count = 0 private
Definition at line 441 of file mom_cap.F90.
 integer              :: scalar_field_count = 0
Referenced by initializep0(), initializerealize(), and setscalarfield().
scalar_field_idx_grid_nx
integer mom_cap_mod::scalar_field_idx_grid_nx = 0 private
Definition at line 442 of file mom_cap.F90.
 integer              :: scalar_field_idx_grid_nx = 0
Referenced by initializep0(), and initializerealize().
scalar_field_idx_grid_ny
integer mom_cap_mod::scalar_field_idx_grid_ny = 0 private
Definition at line 443 of file mom_cap.F90.
 integer              :: scalar_field_idx_grid_ny = 0
Referenced by initializep0(), and initializerealize().
scalar_field_name
character(len=128) mom_cap_mod::scalar_field_name = '' private
Definition at line 440 of file mom_cap.F90.
 character(len=128)   :: scalar_field_name = ''
Referenced by initializeadvertise(), initializep0(), initializerealize(), mom_realizefields(), and setscalarfield().
tmpstr
character(len=256) mom_cap_mod::tmpstr private
Definition at line 434 of file mom_cap.F90.
 character(len=256)   :: tmpstr
Referenced by initializerealize().
u_file_u
character(len=*), parameter mom_cap_mod::u_file_u = __FILE__ private
Definition at line 444 of file mom_cap.F90.
 character(len=*),parameter :: u_file_u = &
      __file__
Referenced by state_setscalar().
write_diagnostics
logical mom_cap_mod::write_diagnostics = .false. private
Definition at line 435 of file mom_cap.F90.
 logical              :: write_diagnostics = .false.
Referenced by datainitialize(), initializep0(), and modeladvance().