MOM6: mom_verticalgrid Module Reference
mom_verticalgrid Module Reference
Detailed Description
Provides a transparent vertical ocean grid type and supporting routines.
Data Types
type verticalgrid_type
Describes the vertical ocean grid, including unit conversion factors.
Functions/Subroutines
subroutine, public verticalgridinit (param_file, GV, US)
Allocates and initializes the ocean model vertical grid structure.
subroutine, public fix_restart_scaling (GV)
Set the scaling factors for restart files to the scaling factors for this run.
character(len=48) function, public get_thickness_units (GV)
Returns the model's thickness units, usually m or kg/m^2.
character(len=48) function, public get_flux_units (GV)
Returns the model's thickness flux units, usually m^3/s or kg/s.
character(len=48) function, public get_tr_flux_units (GV, tr_units, tr_vol_conc_units, tr_mass_conc_units)
Returns the model's tracer flux units.
subroutine, public setverticalgridaxes (Rlay, GV, scale)
This sets the coordinate data for the "layer mode" of the isopycnal model.
subroutine, public verticalgridend (GV)
Deallocates the model's vertical grid structure.
Function/Subroutine Documentation
fix_restart_scaling()
subroutine, public mom_verticalgrid::fix_restart_scaling (type(verticalgrid_type), intent(inout) GV)
Set the scaling factors for restart files to the scaling factors for this run.
Parameters
[in,out] gv The ocean's vertical grid structure
Definition at line 183 of file MOM_verticalGrid.F90.
   type(verticalGrid_type), intent(inout) :: GV   !< The ocean's vertical grid structure
   gv%m_to_H_restart = gv%m_to_H
get_flux_units()
character(len=48) function, public mom_verticalgrid::get_flux_units (type(verticalgrid_type), intent(in) GV)
Returns the model's thickness flux units, usually m^3/s or kg/s.
Returns
The thickness flux units
Parameters
[in] gv The ocean's vertical grid structure
Definition at line 205 of file MOM_verticalGrid.F90.
   character(len=48)                   :: get_flux_units !< The thickness flux units
   type(verticalGrid_type), intent(in) :: GV   !< The ocean's vertical grid structure
   !   This subroutine returns the appropriate units for thickness fluxes,
   ! depending on whether the model is Boussinesq or not and the scaling for
   ! the vertical thickness.
   if (gv%Boussinesq) then
     get_flux_units = "m3 s-1"
   else
     get_flux_units = "kg s-1"
   endif
Referenced by mom_dynamics_split_rk2::initialize_dyn_split_rk2(), mom_dynamics_unsplit::initialize_dyn_unsplit(), mom_dynamics_unsplit_rk2::initialize_dyn_unsplit_rk2(), mom_dynamics_split_rk2::register_restarts_dyn_split_rk2(), mom_dynamics_unsplit::register_restarts_dyn_unsplit(), mom_dynamics_unsplit_rk2::register_restarts_dyn_unsplit_rk2(), and mom::set_restart_fields().
get_thickness_units()
character(len=48) function, public mom_verticalgrid::get_thickness_units (type(verticalgrid_type), intent(in) GV)
Returns the model's thickness units, usually m or kg/m^2.
Returns
The vertical thickness units
Parameters
[in] gv The ocean's vertical grid structure
Definition at line 190 of file MOM_verticalGrid.F90.
   character(len=48)                   :: get_thickness_units !< The vertical thickness units
   type(verticalGrid_type), intent(in) :: GV   !< The ocean's vertical grid structure
   !   This subroutine returns the appropriate units for thicknesses,
   ! depending on whether the model is Boussinesq or not and the scaling for
   ! the vertical thickness.
   if (gv%Boussinesq) then
     get_thickness_units = "m"
   else
     get_thickness_units = "kg m-2"
   endif
Referenced by mom_ale::ale_register_diags(), mom_diabatic_driver::diabatic_driver_init(), mom_geothermal::geothermal_init(), mom::register_diags(), mom_diagnostics::register_transport_diags(), and mom::set_restart_fields().
get_tr_flux_units()
character(len=48) function, public mom_verticalgrid::get_tr_flux_units (type(verticalgrid_type), intent(in) GV, character(len=*), intent(in), optional tr_units, character(len=*), intent(in), optional tr_vol_conc_units, character(len=*), intent(in), optional tr_mass_conc_units)
Returns the model's tracer flux units.
Returns
The model's flux units for a tracer.
Parameters
[in] gv The ocean's vertical grid structure.
[in] tr_units Units for a tracer, for example Celsius or PSU.
[in] tr_vol_conc_units The concentration units per unit volume, for example if the units are umol m-3, tr_vol_conc_units would be umol.
[in] tr_mass_conc_units The concentration units per unit mass of sea water, for example if the units are mol kg-1, tr_vol_conc_units would be mol.
Definition at line 220 of file MOM_verticalGrid.F90.
   character(len=48)                      :: get_tr_flux_units !< The model's flux units
                                                               !! for a tracer.
   type(verticalGrid_type),    intent(in) :: GV                !< The ocean's vertical
                                                               !! grid structure.
   character(len=*), optional, intent(in) :: tr_units          !< Units for a tracer, for example
                                                               !! Celsius or PSU.
   character(len=*), optional, intent(in) :: tr_vol_conc_units !< The concentration units per unit
                                                               !! volume, for example if the units are
                                                               !! umol m-3, tr_vol_conc_units would
                                                               !! be umol.
   character(len=*), optional, intent(in) :: tr_mass_conc_units !< The concentration units per unit
                                                               !! mass of sea water, for example if
                                                               !! the units are mol kg-1,
                                                               !! tr_vol_conc_units would be mol.
   !   This subroutine returns the appropriate units for thicknesses and fluxes,
   ! depending on whether the model is Boussinesq or not and the scaling for
   ! the vertical thickness.
   integer :: cnt
   cnt = 0
   if (present(tr_units)) cnt = cnt+1
   if (present(tr_vol_conc_units)) cnt = cnt+1
   if (present(tr_mass_conc_units)) cnt = cnt+1
   if (cnt == 0) call mom_error(fatal, "get_tr_flux_units: One of the three "//&
     "arguments tr_units, tr_vol_conc_units, or tr_mass_conc_units "//&
     "must be present.")
   if (cnt > 1) call mom_error(fatal, "get_tr_flux_units: Only one of "//&
     "tr_units, tr_vol_conc_units, and tr_mass_conc_units may be present.")
   if (present(tr_units)) then
     if (gv%Boussinesq) then
       get_tr_flux_units = trim(tr_units)//" m3 s-1"
     else
       get_tr_flux_units = trim(tr_units)//" kg s-1"
     endif
   endif
   if (present(tr_vol_conc_units)) then
     if (gv%Boussinesq) then
       get_tr_flux_units = trim(tr_vol_conc_units)//" s-1"
     else
       get_tr_flux_units = trim(tr_vol_conc_units)//" m-3 kg s-1"
     endif
   endif
   if (present(tr_mass_conc_units)) then
     if (gv%Boussinesq) then
       get_tr_flux_units = trim(tr_mass_conc_units)//" kg-1 m3 s-1"
     else
       get_tr_flux_units = trim(tr_mass_conc_units)//" s-1"
     endif
   endif
References mom_error_handler::mom_error().
Referenced by mom::initialize_mom().
setverticalgridaxes()
subroutine, public mom_verticalgrid::setverticalgridaxes (real, dimension(gv%ke), intent(in) Rlay, type(verticalgrid_type), intent(inout) GV, real, intent(in) scale)
This sets the coordinate data for the "layer mode" of the isopycnal model.
Parameters
[in,out] gv The container for vertical grid data
[in] rlay The layer target density [R ~> kg m-3]
[in] scale A unit scaling factor for Rlay
Definition at line 276 of file MOM_verticalGrid.F90.
   type(verticalGrid_type), intent(inout) :: GV   !< The container for vertical grid data
   real, dimension(GV%ke),  intent(in)    :: Rlay !< The layer target density [R ~> kg m-3]
   real,                    intent(in)    :: scale !< A unit scaling factor for Rlay
   ! Local variables
   integer :: k, nk
   nk = gv%ke
   gv%zAxisLongName = 'Target Potential Density'
   gv%zAxisUnits = 'kg m-3'
   do k=1,nk ; gv%sLayer(k) = scale*rlay(k) ; enddo
   if (nk > 1) then
     gv%sInterface(1) = scale * (1.5*rlay(1) - 0.5*rlay(2))
     do k=2,nk ; gv%sInterface(k) = scale * 0.5*( rlay(k-1) + rlay(k) ) ; enddo
     gv%sInterface(nk+1) = scale * (1.5*rlay(nk) - 0.5*rlay(nk-1))
   else
     gv%sInterface(1) = 0.0 ; gv%sInterface(nk+1) = 2.0*scale*rlay(nk)
   endif
Referenced by mom_coord_initialization::mom_initialize_coord().
verticalgridend()
subroutine, public mom_verticalgrid::verticalgridend (type(verticalgrid_type), pointer GV)
Deallocates the model's vertical grid structure.
Parameters
gv The ocean's vertical grid structure
Definition at line 299 of file MOM_verticalGrid.F90.
   type(verticalGrid_type), pointer :: GV !< The ocean's vertical grid structure
   deallocate( gv%g_prime, gv%Rlay )
   deallocate( gv%sInterface , gv%sLayer )
   deallocate( gv )
verticalgridinit()
subroutine, public mom_verticalgrid::verticalgridinit (type(param_file_type), intent(in) param_file, type(verticalgrid_type), pointer GV, type(unit_scale_type), intent(in) US)
Allocates and initializes the ocean model vertical grid structure.
Parameters
[in] param_file Parameter file handle/type
gv The container for vertical grid data
[in] us A dimensional unit scaling type
Definition at line 76 of file MOM_verticalGrid.F90.
   type(param_file_type),   intent(in) :: param_file !< Parameter file handle/type
   type(verticalGrid_type), pointer    :: GV         !< The container for vertical grid data
   type(unit_scale_type),   intent(in) :: US         !< A dimensional unit scaling type
   ! This routine initializes the verticalGrid_type structure (GV).
   ! All memory is allocated but not necessarily set to meaningful values until later.
   ! Local variables
   integer :: nk, H_power
   real    :: H_rescale_factor
   ! This include declares and sets the variable "version".
 # include "version_variable.h"
   character(len=16) :: mdl = 'MOM_verticalGrid'
   if (associated(gv)) call mom_error(fatal, &
      'verticalGridInit: called with an associated GV pointer.')
   allocate(gv)
   ! Read all relevant parameters and write them to the model log.
   call log_version(param_file, mdl, version, &
                    "Parameters providing information about the vertical grid.")
   call get_param(param_file, mdl, "G_EARTH", gv%mks_g_Earth, &
                  "The gravitational acceleration of the Earth.", &
                  units="m s-2", default = 9.80)
   call get_param(param_file, mdl, "RHO_0", gv%Rho0, &
                  "The mean ocean density used with BOUSSINESQ true to "//&
                  "calculate accelerations and the mass for conservation "//&
                  "properties, or with BOUSSINSEQ false to convert some "//&
                  "parameters from vertical units of m to kg m-2.", &
                  units="kg m-3", default=1035.0, scale=us%kg_m3_to_R)
   call get_param(param_file, mdl, "BOUSSINESQ", gv%Boussinesq, &
                  "If true, make the Boussinesq approximation.", default=.true.)
   call get_param(param_file, mdl, "ANGSTROM", gv%Angstrom_m, &
                  "The minimum layer thickness, usually one-Angstrom.", &
                  units="m", default=1.0e-10)
   call get_param(param_file, mdl, "H_RESCALE_POWER", h_power, &
                  "An integer power of 2 that is used to rescale the model's "//&
                  "intenal units of thickness.  Valid values range from -300 to 300.", &
                  units="nondim", default=0, debuggingparam=.true.)
   if (abs(h_power) > 300) call mom_error(fatal, "verticalGridInit: "//&
                  "H_RESCALE_POWER is outside of the valid range of -300 to 300.")
   h_rescale_factor = 1.0
   if (h_power /= 0) h_rescale_factor = 2.0**h_power
   if (.not.gv%Boussinesq) then
     call get_param(param_file, mdl, "H_TO_KG_M2", gv%H_to_kg_m2,&
                  "A constant that translates thicknesses from the model's "//&
                  "internal units of thickness to kg m-2.", units="kg m-2 H-1", &
                  default=1.0)
     gv%H_to_kg_m2 = gv%H_to_kg_m2 * h_rescale_factor
   else
     call get_param(param_file, mdl, "H_TO_M", gv%H_to_m, &
                  "A constant that translates the model's internal "//&
                  "units of thickness into m.", units="m H-1", default=1.0)
     gv%H_to_m = gv%H_to_m * h_rescale_factor
   endif
   gv%g_Earth = us%m_to_L**2*us%Z_to_m*us%T_to_s**2 * gv%mks_g_Earth
 #ifdef STATIC_MEMORY_
   ! Here NK_ is a macro, while nk is a variable.
   call get_param(param_file, mdl, "NK", nk, &
                  "The number of model layers.", units="nondim", &
                  static_value=nk_)
   if (nk /= nk_) call mom_error(fatal, "verticalGridInit: " // &
        "Mismatched number of layers NK_ between MOM_memory.h and param_file")
 #else
   call get_param(param_file, mdl, "NK", nk, &
                  "The number of model layers.", units="nondim", fail_if_missing=.true.)
 #endif
   gv%ke = nk
   if (gv%Boussinesq) then
     gv%H_to_kg_m2 = us%R_to_kg_m3*gv%Rho0 * gv%H_to_m
     gv%kg_m2_to_H = 1.0 / gv%H_to_kg_m2
     gv%m_to_H = 1.0 / gv%H_to_m
     gv%Angstrom_H = gv%m_to_H * gv%Angstrom_m
     gv%H_to_MKS = gv%H_to_m
   else
     gv%kg_m2_to_H = 1.0 / gv%H_to_kg_m2
     gv%m_to_H = us%R_to_kg_m3*gv%Rho0 * gv%kg_m2_to_H
     gv%H_to_m = gv%H_to_kg_m2 / (us%R_to_kg_m3*gv%Rho0)
     gv%Angstrom_H = gv%Angstrom_m*1000.0*gv%kg_m2_to_H
     gv%H_to_MKS = gv%H_to_kg_m2
   endif
   gv%H_subroundoff = 1e-20 * max(gv%Angstrom_H,gv%m_to_H*1e-17)
   gv%H_to_Pa = gv%mks_g_Earth * gv%H_to_kg_m2
   gv%H_to_Z = gv%H_to_m * us%m_to_Z
   gv%Z_to_H = us%Z_to_m * gv%m_to_H
   gv%Angstrom_Z = us%m_to_Z * gv%Angstrom_m
   gv%H_to_RZ = gv%H_to_kg_m2 * us%kg_m3_to_R * us%m_to_Z
   gv%RZ_to_H = gv%kg_m2_to_H * us%R_to_kg_m3 * us%Z_to_m
 ! Log derivative values.
   call log_param(param_file, mdl, "M to THICKNESS", gv%m_to_H*h_rescale_factor)
   call log_param(param_file, mdl, "M to THICKNESS rescaled by 2^-n", gv%m_to_H)
   call log_param(param_file, mdl, "THICKNESS to M rescaled by 2^n", gv%H_to_m)
   allocate( gv%sInterface(nk+1) )
   allocate( gv%sLayer(nk) )
   allocate( gv%g_prime(nk+1) ) ; gv%g_prime(:) = 0.0
   ! The extent of Rlay should be changed to nk?
   allocate( gv%Rlay(nk+1) )    ; gv%Rlay(:) = 0.0
References mom_error_handler::mom_error().
Referenced by mom_oda_driver_mod::init_oda().