MOM6: polynomial_functions Module Reference
polynomial_functions Module Reference
Detailed Description
Polynomial functions.
Date of creation: 2008.06.12 L. White
This module contains routines that handle polynomials.
Functions/Subroutines
real function, public evaluation_polynomial (coeff, ncoef, x)
Pointwise evaluation of a polynomial at x.
real function, public first_derivative_polynomial (coeff, ncoef, x)
Calculates the first derivative of a polynomial evaluated at a point x.
real function, public integration_polynomial (xi0, xi1, Coeff, npoly)
Exact integration of polynomial of degree npoly.
Function/Subroutine Documentation
evaluation_polynomial()
real function, public polynomial_functions::evaluation_polynomial (real, dimension(:), intent(in) coeff, integer, intent(in) ncoef, real, intent(in) x)
Pointwise evaluation of a polynomial at x.
The polynomial is defined by the coefficients contained in the array of the same name, as follows: C(1) + C(2)x + C(3)x^2 + C(4)x^3 + ... where C refers to the array 'coeff'. The number of coefficients is given by ncoef and x is the coordinate where the polynomial is to be evaluated.
Parameters
[in] coeff The coefficients of the polynomial
[in] ncoef The number of polynomial coefficients
[in] x The position at which to evaluate the polynomial
Definition at line 20 of file polynomial_functions.F90.
   real, dimension(:), intent(in) :: coeff !< The coefficients of the polynomial
   integer,            intent(in) :: ncoef !< The number of polynomial coefficients
   real,               intent(in) :: x     !< The position at which to evaluate the polynomial
   ! Local variables
   integer :: k
   real    :: f    ! value of polynomial at x
   f = 0.0
   do k = 1,ncoef
     f = f + coeff(k) * ( x**(k-1) )
   enddo
   evaluation_polynomial = f
Referenced by mom_neutral_diffusion_aux::check_neutral_positions(), mom_neutral_diffusion_aux::drho_at_pos(), regrid_edge_slopes::edge_slopes_implicit_h3(), regrid_edge_slopes::edge_slopes_implicit_h5(), regrid_edge_values::edge_values_explicit_h4(), regrid_edge_values::edge_values_implicit_h4(), regrid_edge_values::edge_values_implicit_h6(), and mom_neutral_diffusion::neutral_surface_t_eval().
first_derivative_polynomial()
real function, public polynomial_functions::first_derivative_polynomial (real, dimension(:), intent(in) coeff, integer, intent(in) ncoef, real, intent(in) x)
Calculates the first derivative of a polynomial evaluated at a point x.
The polynomial is defined by the coefficients contained in the array of the same name, as follows: C(1) + C(2)x + C(3)x^2 + C(4)x^3 + ... where C refers to the array 'coeff'. The number of coefficients is given by ncoef and x is the coordinate where the polynomial's derivative is to be evaluated.
Parameters
[in] coeff The coefficients of the polynomial
[in] ncoef The number of polynomial coefficients
[in] x The position at which to evaluate the derivative
Definition at line 44 of file polynomial_functions.F90.
   real, dimension(:), intent(in) :: coeff !< The coefficients of the polynomial
   integer,            intent(in) :: ncoef !< The number of polynomial coefficients
   real, intent(in)               :: x     !< The position at which to evaluate the derivative
   ! Local variables
   integer                               :: k
   real                                  :: f    ! value of polynomial at x
   f = 0.0
   do k = 2,ncoef
     f = f + real(k-1)*coeff(k) * ( x**(k-2) )
   enddo
   first_derivative_polynomial = f
Referenced by mom_neutral_diffusion_aux::refine_nondim_position().
integration_polynomial()
real function, public polynomial_functions::integration_polynomial (real, intent(in) xi0, real, intent(in) xi1, real, dimension(:), intent(in) Coeff, integer, intent(in) npoly)
Exact integration of polynomial of degree npoly.
The array of coefficients (Coeff) must be of size npoly+1.
Parameters
[in] xi0 The lower bound of the integral
[in] xi1 The lower bound of the integral
[in] coeff The coefficients of the polynomial
[in] npoly The degree of the polynomial
Definition at line 64 of file polynomial_functions.F90.
   real,               intent(in) :: xi0   !< The lower bound of the integral
   real,               intent(in) :: xi1   !< The lower bound of the integral
   real, dimension(:), intent(in) :: Coeff !< The coefficients of the polynomial
   integer,            intent(in) :: npoly !< The degree of the polynomial
   ! Local variables
   integer                           :: k
   real                              :: integral
   integral = 0.0
   do k = 1,npoly+1
     integral = integral + coeff(k) * (xi1**k - xi0**k) / real(k)
   enddo
 !
 !One non-answer-changing way of unrolling the above is:
 !  k=1
 !  integral = integral + Coeff(k) * (xi1**k - xi0**k) / real(k)
 !  if (npoly>=1) then
 !    k=2
 !    integral = integral + Coeff(k) * (xi1**k - xi0**k) / real(k)
 !  endif
 !  if (npoly>=2) then
 !    k=3
 !    integral = integral + Coeff(k) * (xi1**k - xi0**k) / real(k)
 !  endif
 !  if (npoly>=3) then
 !    k=4
 !    integral = integral + Coeff(k) * (xi1**k - xi0**k) / real(k)
 !  endif
 !  if (npoly>=4) then
 !    k=5
 !    integral = integral + Coeff(k) * (xi1**k - xi0**k) / real(k)
 !  endif
 !
   integration_polynomial = integral