MOM6: dyed_channel_initialization Module Reference
dyed_channel_initialization Module Reference
Detailed Description
Initialization for the dyed_channel configuration.
Setting dyes, one for painting the inflow on each side.
Data Types
type dyed_channel_obc_cs
Control structure for dyed-channel open boundaries.
Functions/Subroutines
logical function, public register_dyed_channel_obc (param_file, CS, OBC_Reg)
Add dyed channel to OBC registry.
subroutine, public dyed_channel_obc_end (CS)
Clean up the dyed_channel OBC from registry.
subroutine, public dyed_channel_set_obc_tracer_data (OBC, G, GV, param_file, tr_Reg)
This subroutine sets the dye and flow properties at open boundary conditions.
subroutine, public dyed_channel_update_flow (OBC, CS, G, Time)
This subroutine updates the long-channel flow.
Variables
integer ntr = 0
Number of dye tracers.
Function/Subroutine Documentation
dyed_channel_obc_end()
subroutine, public dyed_channel_initialization::dyed_channel_obc_end (type(dyed_channel_obc_cs), pointer CS)
Clean up the dyed_channel OBC from registry.
Parameters
cs Dyed channel control structure.
Definition at line 74 of file dyed_channel_initialization.F90.
   type(dyed_channel_OBC_CS), pointer :: CS    !< Dyed channel control structure.
   if (associated(cs)) then
     deallocate(cs)
   endif
dyed_channel_set_obc_tracer_data()
subroutine, public dyed_channel_initialization::dyed_channel_set_obc_tracer_data (type(ocean_obc_type), pointer OBC, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, type(param_file_type), intent(in) param_file, type(tracer_registry_type), pointer tr_Reg)
This subroutine sets the dye and flow properties at open boundary conditions.
Parameters
obc This open boundary condition type specifies whether, where, and what open boundary conditions are used.
[in] g The ocean's grid structure.
[in] gv The ocean's vertical grid structure.
[in] param_file A structure indicating the open file to parse for model parameter values.
tr_reg Tracer registry.
Definition at line 83 of file dyed_channel_initialization.F90.
   type(ocean_OBC_type),       pointer    :: OBC !< This open boundary condition type specifies
                                                 !! whether, where, and what open boundary
                                                 !! conditions are used.
   type(ocean_grid_type),      intent(in) :: G   !< The ocean's grid structure.
   type(verticalGrid_type),    intent(in) :: GV  !< The ocean's vertical grid structure.
   type(param_file_type),      intent(in) :: param_file !< A structure indicating the open file
                                                 !! to parse for model parameter values.
   type(tracer_registry_type), pointer    :: tr_Reg !< Tracer registry.
   ! Local variables
   character(len=40)  :: mdl = "dyed_channel_set_OBC_tracer_data" ! This subroutine's name.
   character(len=80)  :: name, longname
   integer :: i, j, k, l, itt, isd, ied, jsd, jed, m, n
   integer :: IsdB, IedB, JsdB, JedB
   real :: dye
   type(OBC_segment_type), pointer :: segment => null()
   type(tracer_type), pointer      :: tr_ptr => null()
   if (.not.associated(obc)) call mom_error(fatal, 'dyed_channel_initialization.F90: '// &
         'dyed_channel_set_OBC_data() was called but OBC type was not initialized!')
   call get_param(param_file, mdl, "NUM_DYE_TRACERS", ntr, &
                  "The number of dye tracers in this run. Each tracer "//&
                  "should have a separate boundary segment.", default=0,   &
                  do_not_log=.true.)
   if (obc%number_of_segments < ntr) then
     call mom_error(warning, "Error in dyed_obc segment setup")
     return   !!! Need a better error message here
   endif
 ! ! Set the inflow values of the dyes, one per segment.
 ! ! We know the order: north, south, east, west
   do m=1,ntr
     write(name,'("dye_",I2.2)') m
     write(longname,'("Concentration of dyed_obc Tracer ",I2.2, " on segment ",I2.2)') m, m
     call tracer_name_lookup(tr_reg, tr_ptr, name)
     do n=1,obc%number_of_segments
       if (n == m) then
         dye = 1.0
       else
         dye = 0.0
       endif
       call register_segment_tracer(tr_ptr, param_file, gv, &
                                    obc%segment(n), obc_scalar=dye)
     enddo
   enddo
References mom_error_handler::mom_error(), and ntr.
Referenced by mom_state_initialization::mom_initialize_state().
dyed_channel_update_flow()
subroutine, public dyed_channel_initialization::dyed_channel_update_flow (type(ocean_obc_type), pointer OBC, type(dyed_channel_obc_cs), pointer CS, type(ocean_grid_type), intent(in) G, type(time_type), intent(in) Time)
This subroutine updates the long-channel flow.
Parameters
obc This open boundary condition type specifies whether, where, and what open boundary conditions are used.
cs Dyed channel control structure.
[in] g The ocean's grid structure.
[in] time model time.
Definition at line 135 of file dyed_channel_initialization.F90.
   type(ocean_OBC_type),       pointer    :: OBC !< This open boundary condition type specifies
                                                 !! whether, where, and what open boundary
                                                 !! conditions are used.
   type(dyed_channel_OBC_CS),  pointer    :: CS  !< Dyed channel control structure.
   type(ocean_grid_type),      intent(in) :: G   !< The ocean's grid structure.
   type(time_type),            intent(in) :: Time !< model time.
   ! Local variables
   character(len=40)  :: mdl = "dyed_channel_update_flow" ! This subroutine's name.
   character(len=80)  :: name
   real :: flow, time_sec, PI
   integer :: i, j, k, l, itt, isd, ied, jsd, jed, m, n
   integer :: IsdB, IedB, JsdB, JedB
   type(OBC_segment_type), pointer :: segment => null()
   if (.not.associated(obc)) call mom_error(fatal, 'dyed_channel_initialization.F90: '// &
         'dyed_channel_update_flow() was called but OBC type was not initialized!')
   time_sec = time_type_to_real(time)
   pi = 4.0*atan(1.0)
   do l=1, obc%number_of_segments
     segment => obc%segment(l)
     if (.not. segment%on_pe) cycle
     if (segment%gradient) cycle
     if (segment%oblique .and. .not. segment%nudged .and. .not. segment%Flather) cycle
     if (segment%is_E_or_W) then
       jsd = segment%HI%jsd ; jed = segment%HI%jed
       isdb = segment%HI%IsdB ; iedb = segment%HI%IedB
       if (cs%frequency == 0.0) then
         flow = g%US%m_s_to_L_T*cs%zonal_flow
       else
         flow = g%US%m_s_to_L_T*cs%zonal_flow + cs%tidal_amp * cos(2 * pi * cs%frequency * time_sec)
       endif
       do k=1,g%ke
         do j=jsd,jed ; do i=isdb,iedb
           if (segment%specified .or. segment%nudged) then
             segment%normal_vel(i,j,k) = flow
           endif
           if (segment%specified) then
             segment%normal_trans(i,j,k) = flow * g%dyCu(i,j)
           endif
         enddo ; enddo
       enddo
       do j=jsd,jed ; do i=isdb,iedb
         segment%normal_vel_bt(i,j) = flow
       enddo ; enddo
     else
       isd = segment%HI%isd ; ied = segment%HI%ied
       jsdb = segment%HI%JsdB ; jedb = segment%HI%JedB
       do j=jsdb,jedb ; do i=isd,ied
         segment%normal_vel_bt(i,j) = 0.0
       enddo ; enddo
     endif
   enddo
References mom_error_handler::mom_error().
register_dyed_channel_obc()
logical function, public dyed_channel_initialization::register_dyed_channel_obc (type(param_file_type), intent(in) param_file, type(dyed_channel_obc_cs), pointer CS, type(obc_registry_type), pointer OBC_Reg)
Add dyed channel to OBC registry.
Parameters
[in] param_file parameter file.
cs Dyed channel control structure.
obc_reg OBC registry.
Definition at line 41 of file dyed_channel_initialization.F90.
   type(param_file_type),     intent(in) :: param_file !< parameter file.
   type(dyed_channel_OBC_CS), pointer    :: CS         !< Dyed channel control structure.
   type(OBC_registry_type),   pointer    :: OBC_Reg    !< OBC registry.
   ! Local variables
   logical                               :: register_dyed_channel_OBC
   character(len=32)  :: casename = "dyed channel"     ! This case's name.
   character(len=40)  :: mdl = "register_dyed_channel_OBC" ! This subroutine's name.
   if (associated(cs)) then
     call mom_error(warning, "register_dyed_channel_OBC called with an "// &
                             "associated control structure.")
     return
   endif
   allocate(cs)
   call get_param(param_file, mdl, "CHANNEL_MEAN_FLOW", cs%zonal_flow, &
                  "Mean zonal flow imposed at upstream open boundary.", &
                  units="m/s", default=8.57)
   call get_param(param_file, mdl, "CHANNEL_TIDAL_AMP", cs%tidal_amp, &
                  "Sloshing amplitude imposed at upstream open boundary.", &
                  units="m/s", default=0.0)
   call get_param(param_file, mdl, "CHANNEL_FLOW_FREQUENCY", cs%frequency, &
                  "Frequency of oscillating zonal flow.", &
                  units="s-1", default=0.0)
   ! Register the open boundaries.
   call register_obc(casename, param_file, obc_reg)
   register_dyed_channel_obc = .true.
References mom_error_handler::mom_error(), and mom_open_boundary::register_obc().
Variable Documentation
ntr
integer dyed_channel_initialization::ntr = 0
Number of dye tracers.
Todo:
This is a module variable. Move this variable into the control structure.
Definition at line 34 of file dyed_channel_initialization.F90.
 integer :: ntr = 0 !< Number of dye tracers
Referenced by dyed_channel_set_obc_tracer_data().