MOM6: mom_pressureforce Module Reference
mom_pressureforce Module Reference
Detailed Description
A thin wrapper for Boussinesq/non-Boussinesq forms of the pressure force calculation.
This thin module provides a branch to two forms of the horizontal accelerations due to pressure gradients. The two options currently available are a Montgomery potential form (used in traditional isopycnal layer models), and the analytic finite volume form.
Data Types
type pressureforce_cs
Pressure force control structure.
Functions/Subroutines
subroutine, public pressureforce (h, tv, PFu, PFv, G, GV, US, CS, ALE_CSp, p_atm, pbce, eta)
A thin layer between the model and the Boussinesq and non-Boussinesq pressure force routines.
subroutine, public pressureforce_init (Time, G, GV, US, param_file, diag, CS, tides_CSp)
Initialize the pressure force control structure.
subroutine, public pressureforce_end (CS)
Deallocate the pressure force control structure.
Function/Subroutine Documentation
pressureforce()
subroutine, public mom_pressureforce::pressureforce (real, dimension(g %isd: g %ied, g %jsd: g %jed, g %ke), intent(in) h, type(thermo_var_ptrs), intent(in) tv, real, dimension(g %isdb: g %iedb, g %jsd: g %jed, g %ke), intent(out) PFu, real, dimension(g %isd: g %ied, g %jsdb: g %jedb, g %ke), intent(out) PFv, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, type(unit_scale_type), intent(in) US, type(pressureforce_cs), pointer CS, type(ale_cs), pointer ALE_CSp, real, dimension(:,:), optional, pointer p_atm, real, dimension(g %isd: g %ied, g %jsd: g %jed, g %ke), intent(out), optional pbce, real, dimension(g %isd: g %ied, g %jsd: g %jed), intent(out), optional eta)
A thin layer between the model and the Boussinesq and non-Boussinesq pressure force routines.
Parameters
[in] g The ocean's grid structure
[in] gv The ocean's vertical grid structure
[in] us A dimensional unit scaling type
[in] h Layer thicknesses [H ~> m or kg m-2]
[in] tv A structure pointing to various thermodynamic variables
[out] pfu Zonal pressure force acceleration [L T-2 ~> m s-2]
[out] pfv Meridional pressure force acceleration [L T-2 ~> m s-2]
cs Pressure force control structure
ale_csp ALE control structure
p_atm The pressure at the ice-ocean or
[out] pbce The baroclinic pressure anomaly in each layer
[out] eta The bottom mass used to calculate PFu and PFv,
Definition at line 48 of file MOM_PressureForce.F90.
   type(ocean_grid_type),   intent(in)  :: G    !< The ocean's grid structure
   type(verticalGrid_type), intent(in)  :: GV   !< The ocean's vertical grid structure
   type(unit_scale_type),   intent(in)  :: US   !< A dimensional unit scaling type
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)), &
                            intent(in)  :: h    !< Layer thicknesses [H ~> m or kg m-2]
   type(thermo_var_ptrs),   intent(in)  :: tv   !< A structure pointing to various thermodynamic variables
   real, dimension(SZIB_(G),SZJ_(G),SZK_(G)), &
                            intent(out) :: PFu  !< Zonal pressure force acceleration [L T-2 ~> m s-2]
   real, dimension(SZI_(G),SZJB_(G),SZK_(G)), &
                            intent(out) :: PFv  !< Meridional pressure force acceleration [L T-2 ~> m s-2]
   type(PressureForce_CS),  pointer     :: CS   !< Pressure force control structure
   type(ALE_CS),            pointer     :: ALE_CSp !< ALE control structure
   real, dimension(:,:), &
                  optional, pointer     :: p_atm !< The pressure at the ice-ocean or
                                                !! atmosphere-ocean interface [Pa].
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)), &
                  optional, intent(out) :: pbce !< The baroclinic pressure anomaly in each layer
                                                !! due to eta anomalies [m2 s-2 H-1 ~> m s-2 or m4 s-2 kg-1].
   real, dimension(SZI_(G),SZJ_(G)), &
                  optional, intent(out) :: eta  !< The bottom mass used to calculate PFu and PFv,
                                                !! [H ~> m or kg m-2], with any tidal contributions.
   if (cs%Analytic_FV_PGF .and. cs%blocked_AFV) then
     if (gv%Boussinesq) then
       call pressureforce_blk_afv_bouss(h, tv, pfu, pfv, g, gv, us, &
                cs%PressureForce_blk_AFV_CSp, ale_csp, p_atm, pbce, eta)
     else
       call pressureforce_blk_afv_nonbouss(h, tv, pfu, pfv, g, gv, us, &
                cs%PressureForce_blk_AFV_CSp, p_atm, pbce, eta)
     endif
   elseif (cs%Analytic_FV_PGF) then
     if (gv%Boussinesq) then
       call pressureforce_afv_bouss(h, tv, pfu, pfv, g, gv, us, cs%PressureForce_AFV_CSp, &
                                    ale_csp, p_atm, pbce, eta)
     else
       call pressureforce_afv_nonbouss(h, tv, pfu, pfv, g, gv, us, cs%PressureForce_AFV_CSp, &
                                       ale_csp, p_atm, pbce, eta)
     endif
   else
     if (gv%Boussinesq) then
       call pressureforce_mont_bouss(h, tv, pfu, pfv, g, gv, us, cs%PressureForce_Mont_CSp, &
                                     p_atm, pbce, eta)
     else
       call pressureforce_mont_nonbouss(h, tv, pfu, pfv, g, gv, us, cs%PressureForce_Mont_CSp, &
                                        p_atm, pbce, eta)
     endif
   endif
Referenced by mom_dynamics_split_rk2::step_mom_dyn_split_rk2(), mom_dynamics_unsplit::step_mom_dyn_unsplit(), and mom_dynamics_unsplit_rk2::step_mom_dyn_unsplit_rk2().
pressureforce_end()
subroutine, public mom_pressureforce::pressureforce_end (type(pressureforce_cs), pointer CS)
Deallocate the pressure force control structure.
Parameters
cs Pressure force control structure
Definition at line 145 of file MOM_PressureForce.F90.
   type(PressureForce_CS), pointer :: CS !< Pressure force control structure
   if (cs%Analytic_FV_PGF .and. cs%blocked_AFV) then
     call pressureforce_blk_afv_end(cs%PressureForce_blk_AFV_CSp)
   elseif (cs%Analytic_FV_PGF) then
     call pressureforce_afv_end(cs%PressureForce_AFV_CSp)
   else
     call pressureforce_mont_end(cs%PressureForce_Mont_CSp)
   endif
   if (associated(cs)) deallocate(cs)
pressureforce_init()
subroutine, public mom_pressureforce::pressureforce_init (type(time_type), intent(in), target Time, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, type(unit_scale_type), intent(in) US, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(pressureforce_cs), pointer CS, type(tidal_forcing_cs), optional, pointer tides_CSp)
Initialize the pressure force control structure.
Parameters
[in] time Current model time
[in] g Ocean grid structure
[in] gv Vertical grid structure
[in] us A dimensional unit scaling type
[in] param_file Parameter file handles
[in,out] diag Diagnostics control structure
cs Pressure force control structure
tides_csp Tide control structure
Definition at line 100 of file MOM_PressureForce.F90.
   type(time_type), target, intent(in)    :: Time !< Current model time
   type(ocean_grid_type),   intent(in)    :: G    !< Ocean grid structure
   type(verticalGrid_type), intent(in)    :: GV   !< Vertical grid structure
   type(unit_scale_type),   intent(in)    :: US   !< A dimensional unit scaling type
   type(param_file_type),   intent(in)    :: param_file !< Parameter file handles
   type(diag_ctrl), target, intent(inout) :: diag !< Diagnostics control structure
   type(PressureForce_CS),  pointer       :: CS   !< Pressure force control structure
   type(tidal_forcing_CS), optional, pointer :: tides_CSp !< Tide control structure
 #include "version_variable.h"
   character(len=40)  :: mdl = "MOM_PressureForce" ! This module's name.
   if (associated(cs)) then
     call mom_error(warning, "PressureForce_init called with an associated "// &
                             "control structure.")
     return
   else ; allocate(cs) ; endif
   ! Read all relevant parameters and write them to the model log.
   call log_version(param_file, mdl, version, "")
   call get_param(param_file, mdl, "ANALYTIC_FV_PGF", cs%Analytic_FV_PGF, &
                  "If true the pressure gradient forces are calculated "//&
                  "with a finite volume form that analytically integrates "//&
                  "the equations of state in pressure to avoid any "//&
                  "possibility of numerical thermobaric instability, as "//&
                  "described in Adcroft et al., O. Mod. (2008).", default=.true.)
   call get_param(param_file, mdl, "BLOCKED_ANALYTIC_FV_PGF", cs%blocked_AFV, &
                  "If true, used the blocked version of the ANALYTIC_FV_PGF "//&
                  "code.  The value of this parameter should not change answers.", &
                  default=.false., do_not_log=.true., debuggingparam=.true.)
   if (cs%Analytic_FV_PGF .and. cs%blocked_AFV) then
     call pressureforce_blk_afv_init(time, g, gv, us, param_file, diag, &
              cs%PressureForce_blk_AFV_CSp, tides_csp)
   elseif (cs%Analytic_FV_PGF) then
     call pressureforce_afv_init(time, g, gv, us, param_file, diag, &
              cs%PressureForce_AFV_CSp, tides_csp)
   else
     call pressureforce_mont_init(time, g, gv, us, param_file, diag, &
              cs%PressureForce_Mont_CSp, tides_csp)
   endif
References mom_error_handler::mom_error().
Referenced by mom_dynamics_split_rk2::initialize_dyn_split_rk2(), mom_dynamics_unsplit::initialize_dyn_unsplit(), and mom_dynamics_unsplit_rk2::initialize_dyn_unsplit_rk2().