MOM6: dyed_obcs_initialization Module Reference
dyed_obcs_initialization Module Reference
Detailed Description
Dyed open boundary conditions.
Setting dyes, one for painting the inflow on each side.
Functions/Subroutines
subroutine, public dyed_obcs_set_obc_data (OBC, G, GV, param_file, tr_Reg)
This subroutine sets the dye properties at open boundary conditions.
Variables
integer ntr = 0
Number of dye tracers.
Function/Subroutine Documentation
dyed_obcs_set_obc_data()
subroutine, public dyed_obcs_initialization::dyed_obcs_set_obc_data (type(ocean_obc_type), pointer OBC, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, type(param_file_type), intent(in) param_file, type(tracer_registry_type), pointer tr_Reg)
This subroutine sets the dye properties at open boundary conditions.
Parameters
obc This open boundary condition type specifies whether, where, and what open boundary conditions are used.
[in] g The ocean's grid structure.
[in] gv The ocean's vertical grid structure.
[in] param_file A structure indicating the open file to parse for model parameter values.
tr_reg Tracer registry.
Definition at line 31 of file dyed_obcs_initialization.F90.
   type(ocean_OBC_type),       pointer    :: OBC !< This open boundary condition type specifies
                                                 !! whether, where, and what open boundary
                                                 !! conditions are used.
   type(ocean_grid_type),      intent(in) :: G   !< The ocean's grid structure.
   type(verticalGrid_type),    intent(in) :: GV  !< The ocean's vertical grid structure.
   type(param_file_type),      intent(in) :: param_file !< A structure indicating the open file
                                                 !! to parse for model parameter values.
   type(tracer_registry_type), pointer    :: tr_Reg !< Tracer registry.
   ! Local variables
   character(len=40)  :: mdl = "dyed_obcs_set_OBC_data" ! This subroutine's name.
   character(len=80)  :: name, longname
   integer :: i, j, k, itt, is, ie, js, je, isd, ied, jsd, jed, m, n, nz
   integer :: IsdB, IedB, JsdB, JedB
   real :: dye
   type(OBC_segment_type), pointer :: segment => null()
   type(tracer_type), pointer      :: tr_ptr => null()
   is = g%isc ; ie = g%iec ; js = g%jsc ; je = g%jec ; nz = g%ke
   isd = g%isd ; ied = g%ied ; jsd = g%jsd ; jed = g%jed
   isdb = g%IsdB ; iedb = g%IedB ; jsdb = g%JsdB ; jedb = g%JedB
   if (.not.associated(obc)) return
   call get_param(param_file, mdl, "NUM_DYE_TRACERS", ntr, &
                  "The number of dye tracers in this run. Each tracer "//&
                  "should have a separate boundary segment.", default=0,   &
                  do_not_log=.true.)
   if (obc%number_of_segments < ntr) then
     call mom_error(warning, "Error in dyed_obc segment setup")
     return   !!! Need a better error message here
   endif
 ! ! Set the inflow values of the dyes, one per segment.
 ! ! We know the order: north, south, east, west
   do m=1,ntr
     write(name,'("dye_",I2.2)') m
     write(longname,'("Concentration of dyed_obc Tracer ",I2.2, " on segment ",I2.2)') m, m
     call tracer_name_lookup(tr_reg, tr_ptr, name)
     do n=1,obc%number_of_segments
       if (n == m) then
         dye = 1.0
       else
         dye = 0.0
       endif
       call register_segment_tracer(tr_ptr, param_file, gv, &
                                    obc%segment(n), obc_scalar=dye)
     enddo
   enddo
References mom_error_handler::mom_error(), ntr, and mom_open_boundary::register_segment_tracer().
Referenced by mom_state_initialization::mom_initialize_state().
Variable Documentation
ntr
integer dyed_obcs_initialization::ntr = 0 private
Number of dye tracers.
Todo:
This is a module variable. Move this variable into the control structure.
Definition at line 24 of file dyed_obcs_initialization.F90.
 integer :: ntr = 0 !< Number of dye tracers
Referenced by dyed_obcs_set_obc_data().