MOM6: mom_cap_time Module Reference
mom_cap_time Module Reference
Detailed Description
This was originally share code in CIME, but required CIME as a dependency to build the MOM cap. The options here for setting a restart alarm are useful for all caps, so a second step is to determine if/how these could be offered more generally in a shared library. For now we really want the MOM cap to only depend on MOM and ESMF/NUOPC.
Functions/Subroutines
subroutine, public alarminit (clock, alarm, option, opt_n, opt_ymd, opt_tod, RefTime, alarmname, rc)
Setup an alarm in a clock. The ringtime sent to AlarmCreate MUST be the next alarm time. If you send an arbitrary but proper ringtime from the past and the ring interval, the alarm will always go off on the next clock advance and this will cause serious problems. Even if it makes sense to initialize an alarm with some reference time and the alarm interval, that reference time has to be advance forward to be >= the current time. In the logic below we set an appropriate "NextAlarm" and then we make sure to advance it properly based on the ring interval.
subroutine, private timeinit (Time, ymd, cal, tod, desc, logunit, rc)
Creates the ESMF_Time object corresponding to the given input time, given in YMD (Year Month Day) and TOD (Time-of-day) format. Sets the time by an integer as YYYYMMDD and integer seconds in the day.
subroutine, private date2ymd (date, year, month, day)
Converts a coded-date (yyyymmdd) into calendar year,month,day.
Variables
character(len= *), parameter, private optnone = "none"
character(len= *), parameter, private optnever = "never"
character(len= *), parameter, private optnsteps = "nsteps"
character(len= *), parameter, private optnstep = "nstep"
character(len= *), parameter, private optnseconds = "nseconds"
character(len= *), parameter, private optnsecond = "nsecond"
character(len= *), parameter, private optnminutes = "nminutes"
character(len= *), parameter, private optnminute = "nminute"
character(len= *), parameter, private optnhours = "nhours"
character(len= *), parameter, private optnhour = "nhour"
character(len= *), parameter, private optndays = "ndays"
character(len= *), parameter, private optnday = "nday"
character(len= *), parameter, private optnmonths = "nmonths"
character(len= *), parameter, private optnmonth = "nmonth"
character(len= *), parameter, private optnyears = "nyears"
character(len= *), parameter, private optnyear = "nyear"
character(len= *), parameter, private optmonthly = "monthly"
character(len= *), parameter, private optyearly = "yearly"
character(len= *), parameter, private optdate = "date"
character(len= *), parameter, private optifdays0 = "ifdays0"
character(len= *), parameter, private optglccouplingperiod = "glc_coupling_period"
integer, parameter secperday = 86400
character(len= *), parameter u_file_u = __FILE__
Function/Subroutine Documentation
alarminit()
subroutine, public mom_cap_time::alarminit (type(esmf_clock), intent(inout) clock, type(esmf_alarm), intent(inout) alarm, character(len=*), intent(in) option, integer, intent(in), optional opt_n, integer, intent(in), optional opt_ymd, integer, intent(in), optional opt_tod, type(esmf_time), intent(in), optional RefTime, character(len=*), intent(in), optional alarmname, integer, intent(inout) rc)
Setup an alarm in a clock. The ringtime sent to AlarmCreate MUST be the next alarm time. If you send an arbitrary but proper ringtime from the past and the ring interval, the alarm will always go off on the next clock advance and this will cause serious problems. Even if it makes sense to initialize an alarm with some reference time and the alarm interval, that reference time has to be advance forward to be >= the current time. In the logic below we set an appropriate "NextAlarm" and then we make sure to advance it properly based on the ring interval.
Parameters
[in,out] clock ESMF clock
[in,out] alarm ESMF alarm
[in] option alarm option
[in] opt_n alarm freq
[in] opt_ymd alarm ymd
[in] opt_tod alarm tod (sec)
[in] reftime ref time
[in] alarmname alarm name
[in,out] rc Return code
Definition at line 69 of file mom_cap_time.F90.
   type(ESMF_Clock)            , intent(inout) :: clock     !< ESMF clock
   type(ESMF_Alarm)            , intent(inout) :: alarm     !< ESMF alarm
   character(len=*)            , intent(in)    :: option    !< alarm option
   integer          , optional , intent(in)    :: opt_n     !< alarm freq
   integer          , optional , intent(in)    :: opt_ymd   !< alarm ymd
   integer          , optional , intent(in)    :: opt_tod   !< alarm tod (sec)
   type(ESMF_Time)  , optional , intent(in)    :: RefTime   !< ref time
   character(len=*) , optional , intent(in)    :: alarmname !< alarm name
   integer                     , intent(inout) :: rc        !< Return code
   ! local variables
   type(ESMF_Calendar)     :: cal              ! calendar
   integer                 :: lymd             ! local ymd
   integer                 :: ltod             ! local tod
   integer                 :: cyy,cmm,cdd,csec ! time info
   integer                 :: nyy,nmm,ndd,nsec ! time info
   character(len=64)       :: lalarmname       ! local alarm name
   logical                 :: update_nextalarm ! update next alarm
   type(ESMF_Time)         :: CurrTime         ! Current Time
   type(ESMF_Time)         :: NextAlarm        ! Next restart alarm time
   type(ESMF_TimeInterval) :: AlarmInterval    ! Alarm interval
   character(len=*), parameter :: subname = '(AlarmInit): '
   !-------------------------------------------------------------------------------
   rc = esmf_success
   lalarmname = 'alarm_unknown'
   if (present(alarmname)) lalarmname = trim(alarmname)
   ltod = 0
   if (present(opt_tod)) ltod = opt_tod
   lymd = -1
   if (present(opt_ymd)) lymd = opt_ymd
   ! verify parameters
   if (trim(option) == optnsteps    .or. trim(option) == optnstep   .or. &
       trim(option) == optnseconds  .or. trim(option) == optnsecond .or. &
       trim(option) == optnminutes  .or. trim(option) == optnminute .or. &
       trim(option) == optnhours    .or. trim(option) == optnhour   .or. &
       trim(option) == optndays     .or. trim(option) == optnday    .or. &
       trim(option) == optnmonths   .or. trim(option) == optnmonth  .or. &
       trim(option) == optnyears    .or. trim(option) == optnyear   .or. &
       trim(option) == optifdays0) then
      if (.not. present(opt_n)) then
         call esmf_logseterror(esmf_rc_arg_bad, &
              msg=subname//trim(option)//' requires opt_n', &
              line=__line__, &
              file=__file__, rctoreturn=rc)
         return
      endif
      if (opt_n <= 0) then
         call esmf_logseterror(esmf_rc_arg_bad, &
              msg=subname//trim(option)//' invalid opt_n', &
              line=__line__, &
              file=__file__, rctoreturn=rc)
         return
      endif
   endif
   call esmf_clockget(clock, currtime=currtime, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
     line=__line__, &
     file=__file__)) &
     return
   call esmf_timeget(currtime, yy=cyy, mm=cmm, dd=cdd, s=csec, rc=rc )
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
        line=__line__, &
        file=__file__)) &
        return
   call esmf_timeget(currtime, yy=nyy, mm=nmm, dd=ndd, s=nsec, rc=rc )
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
        line=__line__, &
        file=__file__)) &
        return
   ! initial guess of next alarm, this will be updated below
   if (present(reftime)) then
      nextalarm = reftime
   else
      nextalarm = currtime
   endif
   ! Determine calendar
   call esmf_clockget(clock, calendar=cal, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
        line=__line__, &
        file=__file__)) &
        return
   ! Determine inputs for call to create alarm
   selectcase (trim(option))
   case (optnone, optnever)
      call esmf_timeintervalset(alarminterval, yy=9999, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
           line=__line__, &
           file=__file__)) &
           return
      call esmf_timeset( nextalarm, yy=9999, mm=12, dd=1, s=0, calendar=cal, rc=rc )
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
           line=__line__, &
           file=__file__)) &
           return
      update_nextalarm  = .false.
   case (optdate)
      if (.not. present(opt_ymd)) then
         call esmf_logseterror(esmf_rc_arg_bad, &
              msg=subname//trim(option)//' requires opt_ymd', &
              line=__line__, &
              file=__file__, rctoreturn=rc)
         return
      endif
      if (lymd < 0 .or. ltod < 0) then
         call esmf_logseterror(esmf_rc_arg_bad, &
              msg=subname//trim(option)//'opt_ymd, opt_tod invalid', &
              line=__line__, &
              file=__file__, rctoreturn=rc)
         return
      endif
      call esmf_timeintervalset(alarminterval, yy=9999, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
           line=__line__, &
           file=__file__)) &
           return
      call timeinit(nextalarm, lymd, cal, tod=ltod, desc="optDate", rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
           line=__line__, &
           file=__file__)) &
           return
      update_nextalarm  = .false.
   case (optifdays0)
      if (.not. present(opt_ymd)) then
         call esmf_logseterror(esmf_rc_arg_bad, &
              msg=subname//trim(option)//' requires opt_ymd', &
              line=__line__, &
              file=__file__, rctoreturn=rc)
         return
      endif
      call esmf_timeintervalset(alarminterval, mm=1, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
           line=__line__, &
           file=__file__)) &
           return
      call esmf_timeset( nextalarm, yy=cyy, mm=cmm, dd=opt_n, s=0, calendar=cal, rc=rc )
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
           line=__line__, &
           file=__file__)) &
           return
      update_nextalarm  = .true.
   case (optnsteps, optnstep)
      call esmf_clockget(clock, timestep=alarminterval, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
           line=__line__, &
           file=__file__)) &
           return
      alarminterval = alarminterval * opt_n
      update_nextalarm  = .true.
   case (optnseconds, optnsecond)
      call esmf_timeintervalset(alarminterval, s=1, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
           line=__line__, &
           file=__file__)) &
           return
      alarminterval = alarminterval * opt_n
      update_nextalarm  = .true.
   case (optnminutes, optnminute)
      call esmf_timeintervalset(alarminterval, s=60, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
           line=__line__, &
           file=__file__)) &
           return
      alarminterval = alarminterval * opt_n
      update_nextalarm  = .true.
   case (optnhours, optnhour)
      call esmf_timeintervalset(alarminterval, s=3600, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
           line=__line__, &
           file=__file__)) &
           return
      alarminterval = alarminterval * opt_n
      update_nextalarm  = .true.
   case (optndays, optnday)
      call esmf_timeintervalset(alarminterval, d=1, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
           line=__line__, &
           file=__file__)) &
           return
      alarminterval = alarminterval * opt_n
      update_nextalarm  = .true.
   case (optnmonths, optnmonth)
      call esmf_timeintervalset(alarminterval, mm=1, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
           line=__line__, &
           file=__file__)) &
           return
      alarminterval = alarminterval * opt_n
      update_nextalarm  = .true.
   case (optmonthly)
      call esmf_timeintervalset(alarminterval, mm=1, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
           line=__line__, &
           file=__file__)) &
           return
      call esmf_timeset( nextalarm, yy=cyy, mm=cmm, dd=1, s=0, calendar=cal, rc=rc )
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
           line=__line__, &
           file=__file__)) &
           return
      update_nextalarm  = .true.
   case (optnyears, optnyear)
      call esmf_timeintervalset(alarminterval, yy=1, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
           line=__line__, &
           file=__file__)) &
           return
      alarminterval = alarminterval * opt_n
      update_nextalarm  = .true.
   case (optyearly)
      call esmf_timeintervalset(alarminterval, yy=1, rc=rc)
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
           line=__line__, &
           file=__file__)) &
           return
      call esmf_timeset( nextalarm, yy=cyy, mm=1, dd=1, s=0, calendar=cal, rc=rc )
      if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
           line=__line__, &
           file=__file__)) &
           return
      update_nextalarm  = .true.
   case default
      call esmf_logseterror(esmf_rc_arg_bad, &
           msg=subname//' unknown option: '//trim(option), &
           line=__line__, &
           file=__file__, rctoreturn=rc)
      return
   end select
   ! --------------------------------------------------------------------------------
   ! --- AlarmInterval and NextAlarm should be set ---
   ! --------------------------------------------------------------------------------
   ! --- advance Next Alarm so it won't ring on first timestep for
   ! --- most options above. go back one alarminterval just to be careful
   if (update_nextalarm) then
      nextalarm = nextalarm - alarminterval
      do while (nextalarm <= currtime)
         nextalarm = nextalarm + alarminterval
      enddo
   endif
   alarm = esmf_alarmcreate( name=lalarmname, clock=clock, ringtime=nextalarm, ringinterval=alarminterval, rc=rc)
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
        line=__line__, &
        file=__file__)) &
        return
References optdate, optifdays0, optmonthly, optnday, optndays, optnever, optnhour, optnhours, optnminute, optnminutes, optnmonth, optnmonths, optnone, optnsecond, optnseconds, optnstep, optnsteps, optnyear, optnyears, optyearly, and timeinit().
Referenced by mom_cap_mod::modelsetrunclock().
date2ymd()
subroutine, private mom_cap_time::date2ymd (integer, intent(in) date, integer, intent(out) year, integer, intent(out) month, integer, intent(out) day) private
Converts a coded-date (yyyymmdd) into calendar year,month,day.
Parameters
[in] date coded-date (yyyymmdd)
[out] day calendar year,month,day
Definition at line 390 of file mom_cap_time.F90.
   integer, intent(in)  :: date             !< coded-date (yyyymmdd)
   integer, intent(out) :: year,month,day   !< calendar year,month,day
   ! local variables
   integer :: tdate   ! temporary date
   character(*),parameter :: subName = "(date2ymd)"
   !-------------------------------------------------------------------------------
   tdate = abs(date)
   year = int(tdate/10000)
   if (date < 0) then
      year = -year
   endif
   month = int( mod(tdate,10000)/  100)
   day = mod(tdate,  100)
Referenced by timeinit().
timeinit()
subroutine, private mom_cap_time::timeinit (type(esmf_time), intent(inout) Time, integer, intent(in) ymd, type(esmf_calendar), intent(in) cal, integer, intent(in), optional tod, character(len=*), intent(in), optional desc, integer, intent(in), optional logunit, integer, intent(out), optional rc) private
Creates the ESMF_Time object corresponding to the given input time, given in YMD (Year Month Day) and TOD (Time-of-day) format. Sets the time by an integer as YYYYMMDD and integer seconds in the day.
Parameters
[in,out] time ESMF time
[in] ymd year, month, day YYYYMMDD
[in] cal ESMF calendar
[in] tod time of day in [sec]
[in] desc description of time to set
[in] logunit Unit for stdout output
[out] rc Return code
Definition at line 346 of file mom_cap_time.F90.
   type(ESMF_Time)     , intent(inout)         :: Time !< ESMF time
   integer             , intent(in)            :: ymd  !< year, month, day YYYYMMDD
   type(ESMF_Calendar) , intent(in)            :: cal  !< ESMF calendar
   integer             , intent(in),  optional :: tod  !< time of day in [sec]
   character(len=*)    , intent(in),  optional :: desc !< description of time to set
   integer             , intent(in),  optional :: logunit!< Unit for stdout output
   integer             , intent(out), optional :: rc   !< Return code
   ! local varaibles
   integer                     :: yr, mon, day ! Year, month, day as integers
   integer                     :: ltod         ! local tod
   character(len=256)          :: ldesc        ! local desc
   character(len=*), parameter :: subname = '(TimeInit) '
   !-------------------------------------------------------------------------------
   ltod = 0
   if (present(tod)) ltod = tod
   ldesc = ''
   if (present(desc)) ldesc = desc
   if ( (ymd < 0) .or. (ltod < 0) .or. (ltod > secperday) )then
      if (present(logunit)) then
         write(logunit,*) subname//': ERROR yymmdd is a negative number or '// &
              'time-of-day out of bounds', ymd, ltod
      endif
      call esmf_logseterror(esmf_rc_arg_bad, &
           msg=subname//' yymmdd is negative or time-of-day out of bounds ', &
           line=__line__, &
           file=__file__, rctoreturn=rc)
      return
   endif
   call date2ymd (ymd,yr,mon,day)
   call esmf_timeset( time, yy=yr, mm=mon, dd=day, s=ltod, calendar=cal, rc=rc )
   if (esmf_logfounderror(rctocheck=rc, msg=esmf_logerr_passthru, &
        line=__line__, &
        file=__file__)) &
        return
References date2ymd(), and secperday.
Referenced by alarminit().
Variable Documentation
optdate
character(len=*), parameter, private mom_cap_time::optdate = "date" private
Definition at line 28 of file mom_cap_time.F90.
Referenced by alarminit().
optglccouplingperiod
character(len=*), parameter, private mom_cap_time::optglccouplingperiod = "glc_coupling_period" private
Definition at line 28 of file mom_cap_time.F90.
optifdays0
character(len=*), parameter, private mom_cap_time::optifdays0 = "ifdays0" private
Definition at line 28 of file mom_cap_time.F90.
Referenced by alarminit().
optmonthly
character(len=*), parameter, private mom_cap_time::optmonthly = "monthly" private
Definition at line 28 of file mom_cap_time.F90.
Referenced by alarminit().
optnday
character(len=*), parameter, private mom_cap_time::optnday = "nday" private
Definition at line 28 of file mom_cap_time.F90.
Referenced by alarminit().
optndays
character(len=*), parameter, private mom_cap_time::optndays = "ndays" private
Definition at line 28 of file mom_cap_time.F90.
Referenced by alarminit().
optnever
character(len=*), parameter, private mom_cap_time::optnever = "never" private
Definition at line 28 of file mom_cap_time.F90.
Referenced by alarminit().
optnhour
character(len=*), parameter, private mom_cap_time::optnhour = "nhour" private
Definition at line 28 of file mom_cap_time.F90.
Referenced by alarminit().
optnhours
character(len=*), parameter, private mom_cap_time::optnhours = "nhours" private
Definition at line 28 of file mom_cap_time.F90.
Referenced by alarminit().
optnminute
character(len=*), parameter, private mom_cap_time::optnminute = "nminute" private
Definition at line 28 of file mom_cap_time.F90.
Referenced by alarminit().
optnminutes
character(len=*), parameter, private mom_cap_time::optnminutes = "nminutes" private
Definition at line 28 of file mom_cap_time.F90.
Referenced by alarminit().
optnmonth
character(len=*), parameter, private mom_cap_time::optnmonth = "nmonth" private
Definition at line 28 of file mom_cap_time.F90.
Referenced by alarminit().
optnmonths
character(len=*), parameter, private mom_cap_time::optnmonths = "nmonths" private
Definition at line 28 of file mom_cap_time.F90.
Referenced by alarminit().
optnone
character(len=*), parameter, private mom_cap_time::optnone = "none" private
Definition at line 28 of file mom_cap_time.F90.
 character(len=*), private, parameter :: &
      optnone           = "none"      , &
      optnever          = "never"     , &
      optnsteps         = "nsteps"    , &
      optnstep          = "nstep"     , &
      optnseconds       = "nseconds"  , &
      optnsecond        = "nsecond"   , &
      optnminutes       = "nminutes"  , &
      optnminute        = "nminute"   , &
      optnhours         = "nhours"    , &
      optnhour          = "nhour"     , &
      optndays          = "ndays"     , &
      optnday           = "nday"      , &
      optnmonths        = "nmonths"   , &
      optnmonth         = "nmonth"    , &
      optnyears         = "nyears"    , &
      optnyear          = "nyear"     , &
      optmonthly        = "monthly"   , &
      optyearly         = "yearly"    , &
      optdate           = "date"      , &
      optifdays0        = "ifdays0"   , &
      optglccouplingperiod = "glc_coupling_period"
Referenced by alarminit().
optnsecond
character(len=*), parameter, private mom_cap_time::optnsecond = "nsecond" private
Definition at line 28 of file mom_cap_time.F90.
Referenced by alarminit().
optnseconds
character(len=*), parameter, private mom_cap_time::optnseconds = "nseconds" private
Definition at line 28 of file mom_cap_time.F90.
Referenced by alarminit().
optnstep
character(len=*), parameter, private mom_cap_time::optnstep = "nstep" private
Definition at line 28 of file mom_cap_time.F90.
Referenced by alarminit().
optnsteps
character(len=*), parameter, private mom_cap_time::optnsteps = "nsteps" private
Definition at line 28 of file mom_cap_time.F90.
Referenced by alarminit().
optnyear
character(len=*), parameter, private mom_cap_time::optnyear = "nyear" private
Definition at line 28 of file mom_cap_time.F90.
Referenced by alarminit().
optnyears
character(len=*), parameter, private mom_cap_time::optnyears = "nyears" private
Definition at line 28 of file mom_cap_time.F90.
Referenced by alarminit().
optyearly
character(len=*), parameter, private mom_cap_time::optyearly = "yearly" private
Definition at line 28 of file mom_cap_time.F90.
Referenced by alarminit().
secperday
integer, parameter mom_cap_time::secperday = 86400 private
Definition at line 52 of file mom_cap_time.F90.
 integer, parameter          :: SecPerDay = 86400 ! Seconds per day
Referenced by timeinit().
u_file_u
character(len=*), parameter mom_cap_time::u_file_u = __FILE__ private
Definition at line 53 of file mom_cap_time.F90.
 character(len=*), parameter :: u_FILE_u = &
      __file__