MOM6: mom_eos_teos10 Module Reference
mom_eos_teos10 Module Reference
Detailed Description
The equation of state using the TEOS10 expressions.
Data Types
interface calculate_density_derivs_teos10
For a given thermodynamic state, return the derivatives of density with conservative temperature and absolute salinity, using the TEOS10 expressions.
interface calculate_density_second_derivs_teos10
For a given thermodynamic state, return the second derivatives of density with various combinations of conservative temperature, absolute salinity, and pressure, using the TEOS10 expressions.
interface calculate_density_teos10
Compute the in situ density of sea water ([kg m-3]), or its anomaly with respect to a reference density, from absolute salinity (g/kg), conservative temperature (in deg C), and pressure [Pa], using the TEOS10 expressions.
interface calculate_spec_vol_teos10
Compute the in situ specific volume of sea water (in [m3 kg-1]), or an anomaly with respect to a reference specific volume, from absolute salinity (in g/kg), conservative temperature (in deg C), and pressure [Pa], using the TEOS10 expressions.
Functions/Subroutines
subroutine calculate_density_scalar_teos10 (T, S, pressure, rho, rho_ref)
This subroutine computes the in situ density of sea water (rho in [kg m-3]) from absolute salinity (S [g kg-1]), conservative temperature (T [degC]), and pressure [Pa]. It uses the expression from the TEOS10 website.
subroutine calculate_density_array_teos10 (T, S, pressure, rho, start, npts, rho_ref)
This subroutine computes the in situ density of sea water (rho in [kg m-3]) from absolute salinity (S [g kg-1]), conservative temperature (T [degC]), and pressure [Pa]. It uses the expression from the TEOS10 website.
subroutine calculate_spec_vol_scalar_teos10 (T, S, pressure, specvol, spv_ref)
This subroutine computes the in situ specific volume of sea water (specvol in [m3 kg-1]) from absolute salinity (S [g kg-1]), conservative temperature (T [degC]) and pressure [Pa], using the TEOS10 equation of state. If spv_ref is present, specvol is an anomaly from spv_ref.
subroutine calculate_spec_vol_array_teos10 (T, S, pressure, specvol, start, npts, spv_ref)
This subroutine computes the in situ specific volume of sea water (specvol in [m3 kg-1]) from absolute salinity (S [g kg-1]), conservative temperature (T [degC]) and pressure [Pa], using the TEOS10 equation of state. If spv_ref is present, specvol is an anomaly from spv_ref.
subroutine calculate_density_derivs_array_teos10 (T, S, pressure, drho_dT, drho_dS, start, npts)
For a given thermodynamic state, calculate the derivatives of density with conservative temperature and absolute salinity, using the TEOS10 expressions.
subroutine calculate_density_derivs_scalar_teos10 (T, S, pressure, drho_dT, drho_dS)
For a given thermodynamic state, calculate the derivatives of density with conservative temperature and absolute salinity, using the TEOS10 expressions.
subroutine, public calculate_specvol_derivs_teos10 (T, S, pressure, dSV_dT, dSV_dS, start, npts)
For a given thermodynamic state, calculate the derivatives of specific volume with conservative temperature and absolute salinity, using the TEOS10 expressions.
subroutine calculate_density_second_derivs_scalar_teos10 (T, S, pressure, drho_dS_dS, drho_dS_dT, drho_dT_dT, drho_dS_dP, drho_dT_dP)
Calculate the 5 second derivatives of the equation of state for scalar inputs.
subroutine calculate_density_second_derivs_array_teos10 (T, S, pressure, drho_dS_dS, drho_dS_dT, drho_dT_dT, drho_dS_dP, drho_dT_dP, start, npts)
Calculate the 5 second derivatives of the equation of state for scalar inputs.
subroutine, public calculate_compress_teos10 (T, S, pressure, rho, drho_dp, start, npts)
This subroutine computes the in situ density of sea water (rho in [kg m-3]) and the compressibility (drho/dp = C_sound^-2) (drho_dp [s2 m-2]) from absolute salinity (sal in g/kg), conservative temperature (T [degC]), and pressure [Pa]. It uses the subroutines from TEOS10 website.
Variables
real, parameter pa2db = 1.e-4
The conversion factor from Pa to dbar.
Function/Subroutine Documentation
calculate_compress_teos10()
subroutine, public mom_eos_teos10::calculate_compress_teos10 (real, dimension(:), intent(in) T, real, dimension(:), intent(in) S, real, dimension(:), intent(in) pressure, real, dimension(:), intent(out) rho, real, dimension(:), intent(out) drho_dp, integer, intent(in) start, integer, intent(in) npts)
This subroutine computes the in situ density of sea water (rho in [kg m-3]) and the compressibility (drho/dp = C_sound^-2) (drho_dp [s2 m-2]) from absolute salinity (sal in g/kg), conservative temperature (T [degC]), and pressure [Pa]. It uses the subroutines from TEOS10 website.
Parameters
[in] t Conservative temperature [degC].
[in] s Absolute salinity [g kg-1].
[in] pressure Pressure [Pa].
[out] rho In situ density [kg m-3].
[out] drho_dp The partial derivative of density with pressure (also the inverse of the square of sound speed) [s2 m-2].
[in] start The starting point in the arrays.
[in] npts The number of values to calculate.
Definition at line 314 of file MOM_EOS_TEOS10.F90.
   real,    intent(in),  dimension(:) :: T        !< Conservative temperature [degC].
   real,    intent(in),  dimension(:) :: S        !< Absolute salinity [g kg-1].
   real,    intent(in),  dimension(:) :: pressure !< Pressure [Pa].
   real,    intent(out), dimension(:) :: rho      !< In situ density [kg m-3].
   real,    intent(out), dimension(:) :: drho_dp  !< The partial derivative of density with pressure
                                                  !! (also the inverse of the square of sound speed)
                                                  !! [s2 m-2].
   integer, intent(in)                :: start    !< The starting point in the arrays.
   integer, intent(in)                :: npts     !< The number of values to calculate.
   ! Local variables
   real :: zs,zt,zp
   integer :: j
   do j=start,start+npts-1
     !Conversions
     zs = s(j) !gsw_sr_from_sp(S(j))       !Convert practical salinity to absolute salinity
     zt = t(j) !gsw_ct_from_pt(S(j),T(j))  !Convert potantial temp to conservative temp
     zp = pressure(j)* pa2db         !Convert pressure from Pascal to decibar
     if (s(j) < -1.0e-10) then ; !Can we assume safely that this is a missing value?
       rho(j) = 1000.0 ; drho_dp(j) = 0.0
     else
       rho(j) = gsw_rho(zs,zt,zp)
       call gsw_rho_first_derivatives(zs,zt,zp, drho_dp=drho_dp(j))
     endif
   enddo
References pa2db.
calculate_density_array_teos10()
subroutine mom_eos_teos10::calculate_density_array_teos10 (real, dimension(:), intent(in) T, real, dimension(:), intent(in) S, real, dimension(:), intent(in) pressure, real, dimension(:), intent(out) rho, integer, intent(in) start, integer, intent(in) npts, real, intent(in), optional rho_ref) private
This subroutine computes the in situ density of sea water (rho in [kg m-3]) from absolute salinity (S [g kg-1]), conservative temperature (T [degC]), and pressure [Pa]. It uses the expression from the TEOS10 website.
Parameters
[in] t Conservative temperature [degC].
[in] s Absolute salinity [g kg-1]
[in] pressure pressure [Pa].
[out] rho in situ density [kg m-3].
[in] start the starting point in the arrays.
[in] npts the number of values to calculate.
[in] rho_ref A reference density [kg m-3].
Definition at line 84 of file MOM_EOS_TEOS10.F90.
   real, dimension(:), intent(in)  :: T        !< Conservative temperature [degC].
   real, dimension(:), intent(in)  :: S        !< Absolute salinity [g kg-1]
   real, dimension(:), intent(in)  :: pressure !< pressure [Pa].
   real, dimension(:), intent(out) :: rho      !< in situ density [kg m-3].
   integer,            intent(in)  :: start    !< the starting point in the arrays.
   integer,            intent(in)  :: npts     !< the number of values to calculate.
   real,     optional, intent(in)  :: rho_ref  !< A reference density [kg m-3].
   ! Local variables
   real :: zs, zt, zp
   integer :: j
   do j=start,start+npts-1
     !Conversions
     zs = s(j) !gsw_sr_from_sp(S(j))       !Convert practical salinity to absolute salinity
     zt = t(j) !gsw_ct_from_pt(S(j),T(j))  !Convert potantial temp to conservative temp
     zp = pressure(j)* pa2db         !Convert pressure from Pascal to decibar
     if (s(j) < -1.0e-10) then !Can we assume safely that this is a missing value?
       rho(j) = 1000.0
     else
       rho(j) = gsw_rho(zs,zt,zp)
     endif
     if (present(rho_ref)) rho(j) = rho(j) - rho_ref
   enddo
References pa2db.
Referenced by calculate_density_scalar_teos10().
calculate_density_derivs_array_teos10()
subroutine mom_eos_teos10::calculate_density_derivs_array_teos10 (real, dimension(:), intent(in) T, real, dimension(:), intent(in) S, real, dimension(:), intent(in) pressure, real, dimension(:), intent(out) drho_dT, real, dimension(:), intent(out) drho_dS, integer, intent(in) start, integer, intent(in) npts) private
For a given thermodynamic state, calculate the derivatives of density with conservative temperature and absolute salinity, using the TEOS10 expressions.
Parameters
[in] t Conservative temperature [degC].
[in] s Absolute salinity [g kg-1].
[in] pressure pressure [Pa].
[out] drho_dt The partial derivative of density with conservative temperature [kg m-3 degC-1].
[out] drho_ds The partial derivative of density with absolute salinity, [kg m-3 (g/kg)-1].
[in] start The starting point in the arrays.
[in] npts The number of values to calculate.
Definition at line 169 of file MOM_EOS_TEOS10.F90.
   real,    intent(in),  dimension(:) :: T        !< Conservative temperature [degC].
   real,    intent(in),  dimension(:) :: S        !< Absolute salinity [g kg-1].
   real,    intent(in),  dimension(:) :: pressure !< pressure [Pa].
   real,    intent(out), dimension(:) :: drho_dT  !< The partial derivative of density with conservative
                                                  !! temperature [kg m-3 degC-1].
   real,    intent(out), dimension(:) :: drho_dS  !< The partial derivative of density with absolute salinity,
                                                  !! [kg m-3 (g/kg)-1].
   integer, intent(in)                :: start    !< The starting point in the arrays.
   integer, intent(in)                :: npts     !< The number of values to calculate.
   ! Local variables
   real :: zs, zt, zp
   integer :: j
   do j=start,start+npts-1
     !Conversions
     zs = s(j) !gsw_sr_from_sp(S(j))       !Convert practical salinity to absolute salinity
     zt = t(j) !gsw_ct_from_pt(S(j),T(j))  !Convert potantial temp to conservative temp
     zp = pressure(j)* pa2db         !Convert pressure from Pascal to decibar
     if (s(j) < -1.0e-10) then ; !Can we assume safely that this is a missing value?
       drho_dt(j) = 0.0 ; drho_ds(j) = 0.0
     else
       call gsw_rho_first_derivatives(zs, zt, zp, drho_dsa=drho_ds(j), drho_dct=drho_dt(j))
     endif
   enddo
References pa2db.
calculate_density_derivs_scalar_teos10()
subroutine mom_eos_teos10::calculate_density_derivs_scalar_teos10 (real, intent(in) T, real, intent(in) S, real, intent(in) pressure, real, intent(out) drho_dT, real, intent(out) drho_dS) private
For a given thermodynamic state, calculate the derivatives of density with conservative temperature and absolute salinity, using the TEOS10 expressions.
Parameters
[in] t Conservative temperature [degC]
[in] s Absolute Salinity [g kg-1]
[in] pressure pressure [Pa].
[out] drho_dt The partial derivative of density with conservative temperature [kg m-3 degC-1].
[out] drho_ds The partial derivative of density with absolute salinity, [kg m-3 (g/kg)-1].
Definition at line 200 of file MOM_EOS_TEOS10.F90.
   real,    intent(in)  :: T        !< Conservative temperature [degC]
   real,    intent(in)  :: S        !< Absolute Salinity [g kg-1]
   real,    intent(in)  :: pressure !< pressure [Pa].
   real,    intent(out) :: drho_dT  !< The partial derivative of density with conservative
                                    !! temperature [kg m-3 degC-1].
   real,    intent(out) :: drho_dS  !< The partial derivative of density with absolute salinity,
                                    !! [kg m-3 (g/kg)-1].
   ! Local variables
   real :: zs, zt, zp
   !Conversions
   zs = s !gsw_sr_from_sp(S)       !Convert practical salinity to absolute salinity
   zt = t !gsw_ct_from_pt(S,T)  !Convert potantial temp to conservative temp
   zp = pressure* pa2db         !Convert pressure from Pascal to decibar
   if (s < -1.0e-10) return !Can we assume safely that this is a missing value?
   call gsw_rho_first_derivatives(zs, zt, zp, drho_dsa=drho_ds, drho_dct=drho_dt)
References pa2db.
calculate_density_scalar_teos10()
subroutine mom_eos_teos10::calculate_density_scalar_teos10 (real, intent(in) T, real, intent(in) S, real, intent(in) pressure, real, intent(out) rho, real, intent(in), optional rho_ref) private
This subroutine computes the in situ density of sea water (rho in [kg m-3]) from absolute salinity (S [g kg-1]), conservative temperature (T [degC]), and pressure [Pa]. It uses the expression from the TEOS10 website.
Parameters
[in] t Conservative temperature [degC].
[in] s Absolute salinity [g kg-1].
[in] pressure pressure [Pa].
[out] rho In situ density [kg m-3].
[in] rho_ref A reference density [kg m-3].
Definition at line 60 of file MOM_EOS_TEOS10.F90.
   real,           intent(in)  :: T        !< Conservative temperature [degC].
   real,           intent(in)  :: S        !< Absolute salinity [g kg-1].
   real,           intent(in)  :: pressure !< pressure [Pa].
   real,           intent(out) :: rho      !< In situ density [kg m-3].
   real, optional, intent(in)  :: rho_ref  !< A reference density [kg m-3].
   ! Local variables
   real, dimension(1) :: T0, S0, pressure0
   real, dimension(1) :: rho0
   t0(1) = t
   s0(1) = s
   pressure0(1) = pressure
   call calculate_density_array_teos10(t0, s0, pressure0, rho0, 1, 1, rho_ref)
   rho = rho0(1)
References calculate_density_array_teos10().
calculate_density_second_derivs_array_teos10()
subroutine mom_eos_teos10::calculate_density_second_derivs_array_teos10 (real, dimension(:), intent(in) T, real, dimension(:), intent(in) S, real, dimension(:), intent(in) pressure, real, dimension(:), intent(out) drho_dS_dS, real, dimension(:), intent(out) drho_dS_dT, real, dimension(:), intent(out) drho_dT_dT, real, dimension(:), intent(out) drho_dS_dP, real, dimension(:), intent(out) drho_dT_dP, integer, intent(in) start, integer, intent(in) npts) private
Calculate the 5 second derivatives of the equation of state for scalar inputs.
Parameters
[in] t Conservative temperature [degC]
[in] s Absolute Salinity [g kg-1]
[in] pressure pressure [Pa].
[out] drho_ds_ds Partial derivative of beta with respect to S
[out] drho_ds_dt Partial derivative of beta with resepct to T
[out] drho_dt_dt Partial derivative of alpha with respect to T
[out] drho_ds_dp Partial derivative of beta with respect to pressure
[out] drho_dt_dp Partial derivative of alpha with respect to pressure
[in] start The starting point in the arrays.
[in] npts The number of values to calculate.
Definition at line 277 of file MOM_EOS_TEOS10.F90.
   real, dimension(:), intent(in)     :: T          !< Conservative temperature [degC]
   real, dimension(:), intent(in)     :: S          !< Absolute Salinity [g kg-1]
   real, dimension(:), intent(in)     :: pressure   !< pressure [Pa].
   real, dimension(:), intent(out)    :: drho_dS_dS !< Partial derivative of beta with respect to S
   real, dimension(:), intent(out)    :: drho_dS_dT !< Partial derivative of beta with resepct to T
   real, dimension(:), intent(out)    :: drho_dT_dT !< Partial derivative of alpha with respect to T
   real, dimension(:), intent(out)    :: drho_dS_dP !< Partial derivative of beta with respect to pressure
   real, dimension(:), intent(out)    :: drho_dT_dP !< Partial derivative of alpha with respect to pressure
   integer, intent(in)  :: start    !< The starting point in the arrays.
   integer, intent(in)  :: npts     !< The number of values to calculate.
   ! Local variables
   real :: zs, zt, zp
   integer :: j
   do j=start,start+npts-1
     !Conversions
     zs = s(j) !gsw_sr_from_sp(S)       !Convert practical salinity to absolute salinity
     zt = t(j) !gsw_ct_from_pt(S,T)  !Convert potantial temp to conservative temp
     zp = pressure(j)* pa2db         !Convert pressure from Pascal to decibar
     if (s(j) < -1.0e-10) then ; !Can we assume safely that this is a missing value?
       drho_ds_ds(j) = 0.0 ; drho_ds_dt(j) = 0.0 ; drho_dt_dt(j) = 0.0
       drho_ds_dp(j) = 0.0 ; drho_dt_dp(j) = 0.0
     else
       call gsw_rho_second_derivatives(zs, zt, zp, rho_sa_sa=drho_ds_ds(j), rho_sa_ct=drho_ds_dt(j), &
                                       rho_ct_ct=drho_dt_dt(j), rho_sa_p=drho_ds_dp(j), rho_ct_p=drho_dt_dp(j))
     endif
   enddo
References pa2db.
calculate_density_second_derivs_scalar_teos10()
subroutine mom_eos_teos10::calculate_density_second_derivs_scalar_teos10 (real, intent(in) T, real, intent(in) S, real, intent(in) pressure, real, intent(out) drho_dS_dS, real, intent(out) drho_dS_dT, real, intent(out) drho_dT_dT, real, intent(out) drho_dS_dP, real, intent(out) drho_dT_dP) private
Calculate the 5 second derivatives of the equation of state for scalar inputs.
Parameters
[in] t Conservative temperature [degC]
[in] s Absolute Salinity [g kg-1]
[in] pressure pressure [Pa].
[out] drho_ds_ds Partial derivative of beta with respect to S
[out] drho_ds_dt Partial derivative of beta with resepct to T
[out] drho_dt_dt Partial derivative of alpha with respect to T
[out] drho_ds_dp Partial derivative of beta with respect to pressure
[out] drho_dt_dp Partial derivative of alpha with respect to pressure
Definition at line 252 of file MOM_EOS_TEOS10.F90.
   real, intent(in)     :: T          !< Conservative temperature [degC]
   real, intent(in)     :: S          !< Absolute Salinity [g kg-1]
   real, intent(in)     :: pressure   !< pressure [Pa].
   real, intent(out)    :: drho_dS_dS !< Partial derivative of beta with respect to S
   real, intent(out)    :: drho_dS_dT !< Partial derivative of beta with resepct to T
   real, intent(out)    :: drho_dT_dT !< Partial derivative of alpha with respect to T
   real, intent(out)    :: drho_dS_dP !< Partial derivative of beta with respect to pressure
   real, intent(out)    :: drho_dT_dP !< Partial derivative of alpha with respect to pressure
   ! Local variables
   real :: zs, zt, zp
   !Conversions
   zs = s !gsw_sr_from_sp(S)       !Convert practical salinity to absolute salinity
   zt = t !gsw_ct_from_pt(S,T)  !Convert potantial temp to conservative temp
   zp = pressure* pa2db         !Convert pressure from Pascal to decibar
   if (s < -1.0e-10) return !Can we assume safely that this is a missing value?
   call gsw_rho_second_derivatives(zs, zt, zp, rho_sa_sa=drho_ds_ds, rho_sa_ct=drho_ds_dt, &
                                      rho_ct_ct=drho_dt_dt, rho_sa_p=drho_ds_dp, rho_ct_p=drho_dt_dp)
References pa2db.
calculate_spec_vol_array_teos10()
subroutine mom_eos_teos10::calculate_spec_vol_array_teos10 (real, dimension(:), intent(in) T, real, dimension(:), intent(in) S, real, dimension(:), intent(in) pressure, real, dimension(:), intent(out) specvol, integer, intent(in) start, integer, intent(in) npts, real, intent(in), optional spv_ref) private
This subroutine computes the in situ specific volume of sea water (specvol in [m3 kg-1]) from absolute salinity (S [g kg-1]), conservative temperature (T [degC]) and pressure [Pa], using the TEOS10 equation of state. If spv_ref is present, specvol is an anomaly from spv_ref.
Parameters
[in] t Conservative temperature relative to the surface [degC].
[in] s salinity [g kg-1].
[in] pressure pressure [Pa].
[out] specvol in situ specific volume [m3 kg-1].
[in] start the starting point in the arrays.
[in] npts the number of values to calculate.
[in] spv_ref A reference specific volume [m3 kg-1].
Definition at line 137 of file MOM_EOS_TEOS10.F90.
   real, dimension(:), intent(in)  :: T        !< Conservative temperature relative to the surface
                                               !! [degC].
   real, dimension(:), intent(in)  :: S        !< salinity [g kg-1].
   real, dimension(:), intent(in)  :: pressure !< pressure [Pa].
   real, dimension(:), intent(out) :: specvol  !< in situ specific volume [m3 kg-1].
   integer,            intent(in)  :: start    !< the starting point in the arrays.
   integer,            intent(in)  :: npts     !< the number of values to calculate.
   real,     optional, intent(in)  :: spv_ref  !< A reference specific volume [m3 kg-1].
   ! Local variables
   real :: zs, zt, zp
   integer :: j
   do j=start,start+npts-1
     !Conversions
     zs = s(j) !gsw_sr_from_sp(S(j))       !Convert practical salinity to absolute salinity
     zt = t(j) !gsw_ct_from_pt(S(j),T(j))  !Convert potantial temp to conservative temp
     zp = pressure(j)* pa2db         !Convert pressure from Pascal to decibar
     if (s(j) < -1.0e-10) then
       specvol(j) = 0.001 !Can we assume safely that this is a missing value?
     else
       specvol(j) = gsw_specvol(zs,zt,zp)
     endif
     if (present(spv_ref)) specvol(j) = specvol(j) - spv_ref
   enddo
References pa2db.
Referenced by calculate_spec_vol_scalar_teos10().
calculate_spec_vol_scalar_teos10()
subroutine mom_eos_teos10::calculate_spec_vol_scalar_teos10 (real, intent(in) T, real, intent(in) S, real, intent(in) pressure, real, intent(out) specvol, real, intent(in), optional spv_ref) private
This subroutine computes the in situ specific volume of sea water (specvol in [m3 kg-1]) from absolute salinity (S [g kg-1]), conservative temperature (T [degC]) and pressure [Pa], using the TEOS10 equation of state. If spv_ref is present, specvol is an anomaly from spv_ref.
Parameters
[in] t Conservative temperature [degC].
[in] s Absolute salinity [g kg-1]
[in] pressure pressure [Pa].
[out] specvol in situ specific volume [m3 kg-1].
[in] spv_ref A reference specific volume [m3 kg-1].
Definition at line 116 of file MOM_EOS_TEOS10.F90.
   real,           intent(in)  :: T        !< Conservative temperature [degC].
   real,           intent(in)  :: S        !< Absolute salinity [g kg-1]
   real,           intent(in)  :: pressure !< pressure [Pa].
   real,           intent(out) :: specvol  !< in situ specific volume [m3 kg-1].
   real, optional, intent(in)  :: spv_ref  !< A reference specific volume [m3 kg-1].
   ! Local variables
   real, dimension(1) :: T0, S0, pressure0, spv0
   t0(1) = t ; s0(1) = s ; pressure0(1) = pressure
   call calculate_spec_vol_array_teos10(t0, s0, pressure0, spv0, 1, 1, spv_ref)
   specvol = spv0(1)
References calculate_spec_vol_array_teos10().
calculate_specvol_derivs_teos10()
subroutine, public mom_eos_teos10::calculate_specvol_derivs_teos10 (real, dimension(:), intent(in) T, real, dimension(:), intent(in) S, real, dimension(:), intent(in) pressure, real, dimension(:), intent(out) dSV_dT, real, dimension(:), intent(out) dSV_dS, integer, intent(in) start, integer, intent(in) npts)
For a given thermodynamic state, calculate the derivatives of specific volume with conservative temperature and absolute salinity, using the TEOS10 expressions.
Parameters
[in] t Conservative temperature [degC].
[in] s Absolute salinity [g kg-1].
[in] pressure pressure [Pa].
[out] dsv_dt The partial derivative of specific volume with conservative temperature [m3 kg-1 degC-1].
[out] dsv_ds The partial derivative of specific volume with absolute salinity [m3 kg-1 (g/kg)-1].
[in] start The starting point in the arrays.
[in] npts The number of values to calculate.
Definition at line 221 of file MOM_EOS_TEOS10.F90.
   real,    intent(in),  dimension(:) :: T        !< Conservative temperature [degC].
   real,    intent(in),  dimension(:) :: S        !< Absolute salinity [g kg-1].
   real,    intent(in),  dimension(:) :: pressure !< pressure [Pa].
   real,    intent(out), dimension(:) :: dSV_dT   !< The partial derivative of specific volume with
                                                  !! conservative temperature [m3 kg-1 degC-1].
   real,    intent(out), dimension(:) :: dSV_dS   !< The partial derivative of specific volume with
                                                  !! absolute salinity [m3 kg-1 (g/kg)-1].
   integer, intent(in)                :: start    !< The starting point in the arrays.
   integer, intent(in)                :: npts     !< The number of values to calculate.
   ! Local variables
   real :: zs, zt, zp
   integer :: j
   do j=start,start+npts-1
     !Conversions
     zs = s(j) !gsw_sr_from_sp(S(j))       !Convert practical salinity to absolute salinity
     zt = t(j) !gsw_ct_from_pt(S(j),T(j))  !Convert potantial temp to conservative temp
     zp = pressure(j)* pa2db         !Convert pressure from Pascal to decibar
     if (s(j) < -1.0e-10) then ; !Can we assume safely that this is a missing value?
       dsv_dt(j) = 0.0 ; dsv_ds(j) = 0.0
     else
       call gsw_specvol_first_derivatives(zs,zt,zp, v_sa=dsv_ds(j), v_ct=dsv_dt(j))
     endif
   enddo
References pa2db.
Variable Documentation
pa2db
real, parameter mom_eos_teos10::pa2db = 1.e-4 private
The conversion factor from Pa to dbar.
Definition at line 51 of file MOM_EOS_TEOS10.F90.
 real, parameter :: Pa2db  = 1.e-4  !< The conversion factor from Pa to dbar.
Referenced by calculate_compress_teos10(), calculate_density_array_teos10(), calculate_density_derivs_array_teos10(), calculate_density_derivs_scalar_teos10(), calculate_density_second_derivs_array_teos10(), calculate_density_second_derivs_scalar_teos10(), calculate_spec_vol_array_teos10(), and calculate_specvol_derivs_teos10().