MOM6: mom_surface_forcing_mct Module Reference
mom_surface_forcing_mct Module Reference
Data Types
type ice_ocean_boundary_type
Structure corresponding to forcing, but with the elements, units, and conventions that exactly conform to the use for MOM-based coupled models.
type surface_forcing_cs
Contains pointers to the forcing fields which may be used to drive MOM. All fluxes are positive downward.
Functions/Subroutines
subroutine, public convert_iob_to_fluxes (IOB, fluxes, index_bounds, Time, G, US, CS, sfc_state, restore_salt, restore_temp)
This subroutine translates the Ice_ocean_boundary_type into a MOM thermodynamic forcing type, including changes of units, sign conventions, and putting the fields into arrays with MOM-standard halos.
subroutine, public convert_iob_to_forces (IOB, forces, index_bounds, Time, G, US, CS)
This subroutine translates the Ice_ocean_boundary_type into a MOM mechanical forcing type, including changes of units, sign conventions, and putting the fields into arrays with MOM-standard halos.
subroutine, private apply_flux_adjustments (G, CS, Time, fluxes)
Adds thermodynamic flux adjustments obtained via data_override Component name is 'OCN' Available adjustments are:
subroutine, private apply_force_adjustments (G, CS, Time, forces)
Adds mechanical forcing adjustments obtained via data_override Component name is 'OCN' Available adjustments are:
subroutine, public forcing_save_restart (CS, G, Time, directory, time_stamped, filename_suffix)
Save any restart files associated with the surface forcing.
subroutine, public surface_forcing_init (Time, G, US, param_file, diag, CS, restore_salt, restore_temp)
Initialize the surface forcing, including setting parameters and allocating permanent memory.
subroutine, private surface_forcing_end (CS, fluxes)
Clean up and deallocate any memory associated with this module and its children.
subroutine, public ice_ocn_bnd_type_chksum (id, timestep, iobt)
Write out a set of messages with checksums of the fields in an ice_ocen_boundary type.
Variables
integer id_clock_forcing
Function/Subroutine Documentation
apply_flux_adjustments()
subroutine, private mom_surface_forcing_mct::apply_flux_adjustments (type(ocean_grid_type), intent(inout) G, type(surface_forcing_cs), pointer CS, type(time_type), intent(in) Time, type(forcing), intent(inout) fluxes) private
Adds thermodynamic flux adjustments obtained via data_override Component name is 'OCN' Available adjustments are:
hflx_adj (Heat flux into the ocean, in W m-2)
sflx_adj (Salt flux into the ocean, in kg salt m-2 s-1)
prcme_adj (Fresh water flux into the ocean, in kg m-2 s-1)
Parameters
[in,out] g Ocean grid structure
cs Surface forcing control structure
[in] time Model time structure
[in,out] fluxes Surface fluxes structure
Definition at line 869 of file mom_surface_forcing_mct.F90.
   type(ocean_grid_type),    intent(inout) :: G !< Ocean grid structure
   type(surface_forcing_CS), pointer       :: CS !< Surface forcing control structure
   type(time_type),          intent(in)    :: Time !< Model time structure
   type(forcing),            intent(inout) :: fluxes !< Surface fluxes structure
   ! Local variables
   real, dimension(SZI_(G),SZJ_(G)) :: temp_at_h !< Fluxes at h points [W m-2 or kg m-2 s-1]
   integer :: isc, iec, jsc, jec, i, j
   logical :: overrode_h
   isc = g%isc; iec = g%iec ; jsc = g%jsc; jec = g%jec
   overrode_h = .false.
   call data_override('OCN', 'hflx_adj', temp_at_h(isc:iec,jsc:jec), time, override=overrode_h)
   if (overrode_h) then ; do j=jsc,jec ; do i=isc,iec
     fluxes%heat_added(i,j) = fluxes%heat_added(i,j) + temp_at_h(i,j)* g%mask2dT(i,j)
   enddo ; enddo ; endif
   ! Not needed? ! if (overrode_h) call pass_var(fluxes%heat_added, G%Domain)
   overrode_h = .false.
   call data_override('OCN', 'sflx_adj', temp_at_h(isc:iec,jsc:jec), time, override=overrode_h)
   if (overrode_h) then ; do j=jsc,jec ; do i=isc,iec
     fluxes%salt_flux_added(i,j) = fluxes%salt_flux_added(i,j) + temp_at_h(i,j)* g%mask2dT(i,j)
   enddo ; enddo ; endif
   ! Not needed? ! if (overrode_h) call pass_var(fluxes%salt_flux_added, G%Domain)
   overrode_h = .false.
   call data_override('OCN', 'prcme_adj', temp_at_h(isc:iec,jsc:jec), time, override=overrode_h)
   if (overrode_h) then ; do j=jsc,jec ; do i=isc,iec
     fluxes%vprec(i,j) = fluxes%vprec(i,j) + temp_at_h(i,j)* g%mask2dT(i,j)
   enddo ; enddo ; endif
   ! Not needed? ! if (overrode_h) call pass_var(fluxes%vprec, G%Domain)
Referenced by convert_iob_to_fluxes().
apply_force_adjustments()
subroutine, private mom_surface_forcing_mct::apply_force_adjustments (type(ocean_grid_type), intent(inout) G, type(surface_forcing_cs), pointer CS, type(time_type), intent(in) Time, type(mech_forcing), intent(inout) forces) private
Adds mechanical forcing adjustments obtained via data_override Component name is 'OCN' Available adjustments are:
taux_adj (Zonal wind stress delta, positive to the east, in Pa)
tauy_adj (Meridional wind stress delta, positive to the north, in Pa)
Parameters
[in,out] g Ocean grid structure
cs Surface forcing control structure
[in] time Model time structure
[in,out] forces A structure with the driving mechanical forces
Definition at line 914 of file mom_surface_forcing_mct.F90.
   type(ocean_grid_type),    intent(inout) :: G  !< Ocean grid structure
   type(surface_forcing_CS), pointer       :: CS !< Surface forcing control structure
   type(time_type),          intent(in)    :: Time !< Model time structure
   type(mech_forcing),       intent(inout) :: forces !< A structure with the driving mechanical forces
   ! Local variables
   real, dimension(SZI_(G),SZJ_(G)) :: tempx_at_h !< Delta to zonal wind stress at h points [Pa]
   real, dimension(SZI_(G),SZJ_(G)) :: tempy_at_h !< Delta to meridional wind stress at h points [Pa]
   integer :: isc, iec, jsc, jec, i, j
   real :: dLonDx, dLonDy, rDlon, cosA, sinA, zonal_tau, merid_tau
   logical :: overrode_x, overrode_y
   isc = g%isc; iec = g%iec ; jsc = g%jsc; jec = g%jec
   tempx_at_h(:,:) = 0.0 ; tempy_at_h(:,:) = 0.0
   ! Either reads data or leaves contents unchanged
   overrode_x = .false. ; overrode_y = .false.
   call data_override('OCN', 'taux_adj', tempx_at_h(isc:iec,jsc:jec), time, override=overrode_x)
   call data_override('OCN', 'tauy_adj', tempy_at_h(isc:iec,jsc:jec), time, override=overrode_y)
   if (overrode_x .or. overrode_y) then
     if (.not. (overrode_x .and. overrode_y)) call mom_error(fatal,"apply_flux_adjustments: "//&
             "Both taux_adj and tauy_adj must be specified, or neither, in data_table")
     ! Rotate winds
     call pass_vector(tempx_at_h, tempy_at_h, g%Domain, to_all, agrid, halo=1)
     do j=jsc-1,jec+1 ; do i=isc-1,iec+1
       dlondx = g%geoLonCu(i,j) - g%geoLonCu(i-1,j)
       dlondy = g%geoLonCv(i,j) - g%geoLonCv(i,j-1)
       rdlon = sqrt( dlondx * dlondx + dlondy * dlondy )
       if (rdlon > 0.) rdlon = 1. / rdlon
       cosa = dlondx * rdlon
       sina = dlondy * rdlon
       zonal_tau = tempx_at_h(i,j)
       merid_tau = tempy_at_h(i,j)
       tempx_at_h(i,j) = cosa * zonal_tau - sina * merid_tau
       tempy_at_h(i,j) = sina * zonal_tau + cosa * merid_tau
     enddo ; enddo
     ! Average to C-grid locations
     do j=jsc,jec ; do i=isc-1,iec
       forces%taux(i,j) = forces%taux(i,j) + 0.5 * ( tempx_at_h(i,j) + tempx_at_h(i+1,j) )
     enddo ; enddo
     do j=jsc-1,jec ; do i=isc,iec
       forces%tauy(i,j) = forces%tauy(i,j) + 0.5 * ( tempy_at_h(i,j) + tempy_at_h(i,j+1) )
     enddo ; enddo
   endif ! overrode_x .or. overrode_y
References mom_error_handler::mom_error().
Referenced by convert_iob_to_forces().
convert_iob_to_fluxes()
subroutine, public mom_surface_forcing_mct::convert_iob_to_fluxes (type(ice_ocean_boundary_type), intent(in), target IOB, type(forcing), intent(inout) fluxes, integer, dimension(4), intent(in) index_bounds, type(time_type), intent(in) Time, type(ocean_grid_type), intent(inout) G, type(unit_scale_type), intent(in) US, type(surface_forcing_cs), pointer CS, type(surface), intent(in) sfc_state, logical, intent(in), optional restore_salt, logical, intent(in), optional restore_temp)
This subroutine translates the Ice_ocean_boundary_type into a MOM thermodynamic forcing type, including changes of units, sign conventions, and putting the fields into arrays with MOM-standard halos.
Parameters
[in] iob An ice-ocean boundary type with fluxes to drive
[in,out] fluxes A structure containing pointers to all possible mass, heat or salt flux forcing fields. Unused fields have NULL ptrs.
[in] index_bounds The i- and j- size of the arrays in IOB.
[in] time The time of the fluxes, used for interpolating the salinity to the right time, when it is being restored.
[in,out] g The ocean's grid structure
[in] us A dimensional unit scaling type
cs A pointer to the control structure returned by a previous call to surface_forcing_init.
[in] sfc_state A structure containing fields that describe the surface state of the ocean.
[in] restore_salt If true, salinity is restored to a target value.
[in] restore_temp If true, temperature is restored to a target value.
Definition at line 202 of file mom_surface_forcing_mct.F90.
   type(ice_ocean_boundary_type), &
                  target, intent(in)    :: IOB    !< An ice-ocean boundary type with fluxes to drive
                                                  !! the ocean in a coupled model
   type(forcing),           intent(inout) :: fluxes !< A structure containing pointers to all
                                                    !! possible mass, heat or salt flux forcing fields.
                                                    !!  Unused fields have NULL ptrs.
   integer, dimension(4),   intent(in)    :: index_bounds !< The i- and j- size of the arrays in IOB.
   type(time_type),         intent(in)    :: Time   !< The time of the fluxes, used for interpolating the
                                                    !! salinity to the right time, when it is being restored.
   type(ocean_grid_type),   intent(inout) :: G      !< The ocean's grid structure
   type(unit_scale_type),   intent(in)    :: US     !< A dimensional unit scaling type
   type(surface_forcing_CS),pointer       :: CS     !< A pointer to the control structure returned by a
                                                    !! previous call to surface_forcing_init.
   type(surface),           intent(in)    :: sfc_state !< A structure containing fields that describe the
                                                       !! surface state of the ocean.
   logical,       optional, intent(in)    :: restore_salt !< If true, salinity is restored to a target value.
   logical,       optional, intent(in)    :: restore_temp !< If true, temperature is restored to a target value.
   ! local variables
   real, dimension(SZI_(G),SZJ_(G)) :: &
     data_restore,  & !< The surface value toward which to restore [g/kg or degC]
     SST_anom,      & !< Instantaneous sea surface temperature anomalies from a target value [deg C]
     SSS_anom,      & !< Instantaneous sea surface salinity anomalies from a target value [g/kg]
     SSS_mean,      & !< A (mean?) salinity about which to normalize local salinity
                      !! anomalies when calculating restorative precipitation anomalies [g/kg]
     pme_adj,       & !< The adjustment to PminusE that will cause the salinity
                      !! to be restored toward its target value [kg/(m^2 * s)]
     net_fw,        & !< The area integrated net freshwater flux into the ocean [kg/s]
     net_fw2,       & !< The area integrated net freshwater flux into the ocean [kg/s]
     work_sum,      & !< A 2-d array that is used as the work space for a global
                      !! sum, used with units of m2 or [kg/s]
     open_ocn_mask    !< a binary field indicating where ice is present based on frazil criteria
   integer :: i, j, is, ie, js, je, Isq, Ieq, Jsq, Jeq, i0, j0
   integer :: isd, ied, jsd, jed, IsdB, IedB, JsdB, JedB, isr, ier, jsr, jer
   integer :: isc_bnd, iec_bnd, jsc_bnd, jec_bnd
   logical :: restore_salinity !< local copy of the argument restore_salt, if it
                               !! is present, or false (no restoring) otherwise.
   logical :: restore_sst      !< local copy of the argument restore_temp, if it
                               !! is present, or false (no restoring) otherwise.
   real :: delta_sss           !< temporary storage for sss diff from restoring value
   real :: delta_sst           !< temporary storage for sst diff from restoring value
   real :: C_p                 !< heat capacity of seawater ( J/(K kg) )
   real :: sign_for_net_FW_bug !< Should be +1. but an old bug can be recovered by using -1.
   call cpu_clock_begin(id_clock_forcing)
   isc_bnd = index_bounds(1) ; iec_bnd = index_bounds(2)
   jsc_bnd = index_bounds(3) ; jec_bnd = index_bounds(4)
   is   = g%isc   ; ie   = g%iec    ; js   = g%jsc   ; je   = g%jec
   isq  = g%IscB  ; ieq  = g%IecB   ; jsq  = g%JscB  ; jeq  = g%JecB
   isd  = g%isd   ; ied  = g%ied    ; jsd  = g%jsd   ; jed  = g%jed
   isdb = g%IsdB  ; iedb = g%IedB   ; jsdb = g%JsdB  ; jedb = g%JedB
   isr = is-isd+1 ; ier  = ie-isd+1 ; jsr = js-jsd+1 ; jer = je-jsd+1
   c_p                    = fluxes%C_p
   open_ocn_mask(:,:)     = 1.0
   pme_adj(:,:)           = 0.0
   fluxes%vPrecGlobalAdj  = 0.0
   fluxes%vPrecGlobalScl  = 0.0
   fluxes%saltFluxGlobalAdj = 0.0
   fluxes%saltFluxGlobalScl = 0.0
   fluxes%netFWGlobalAdj = 0.0
   fluxes%netFWGlobalScl = 0.0
   restore_salinity = .false.
   if (present(restore_salt)) restore_salinity = restore_salt
   restore_sst = .false.
   if (present(restore_temp)) restore_sst = restore_temp
   ! allocation and initialization if this is the first time that this
   ! flux type has been used.
   if (fluxes%dt_buoy_accum < 0) then
     call allocate_forcing_type(g, fluxes, water=.true., heat=.true., &
                                ustar=.true., press=.true.)
     call safe_alloc_ptr(fluxes%sw_vis_dir,isd,ied,jsd,jed)
     call safe_alloc_ptr(fluxes%sw_vis_dif,isd,ied,jsd,jed)
     call safe_alloc_ptr(fluxes%sw_nir_dir,isd,ied,jsd,jed)
     call safe_alloc_ptr(fluxes%sw_nir_dif,isd,ied,jsd,jed)
     call safe_alloc_ptr(fluxes%p_surf,isd,ied,jsd,jed)
     call safe_alloc_ptr(fluxes%p_surf_full,isd,ied,jsd,jed)
     if (cs%use_limited_P_SSH) then
        fluxes%p_surf_SSH => fluxes%p_surf
     else
        fluxes%p_surf_SSH => fluxes%p_surf_full
     endif
     call safe_alloc_ptr(fluxes%salt_flux,isd,ied,jsd,jed)
     call safe_alloc_ptr(fluxes%salt_flux_in,isd,ied,jsd,jed)
     call safe_alloc_ptr(fluxes%salt_flux_added,isd,ied,jsd,jed)
     call safe_alloc_ptr(fluxes%TKE_tidal,isd,ied,jsd,jed)
     call safe_alloc_ptr(fluxes%ustar_tidal,isd,ied,jsd,jed)
     if (cs%allow_flux_adjustments) then
       call safe_alloc_ptr(fluxes%heat_added,isd,ied,jsd,jed)
       call safe_alloc_ptr(fluxes%salt_flux_added,isd,ied,jsd,jed)
     endif
     do j=js-2,je+2 ; do i=is-2,ie+2
       fluxes%TKE_tidal(i,j)   = cs%TKE_tidal(i,j)
       fluxes%ustar_tidal(i,j) = cs%ustar_tidal(i,j)
     enddo; enddo
     if (restore_temp) call safe_alloc_ptr(fluxes%heat_added,isd,ied,jsd,jed)
     fluxes%dt_buoy_accum = 0.0
   endif   ! endif for allocation and initialization
   if (((associated(iob%ustar_berg) .and. (.not.associated(fluxes%ustar_berg))) &
     .or. (associated(iob%area_berg) .and. (.not.associated(fluxes%area_berg)))) &
     .or. (associated(iob%mass_berg) .and. (.not.associated(fluxes%mass_berg)))) &
     call allocate_forcing_type(g, fluxes, iceberg=.true.)
   if ((.not.coupler_type_initialized(fluxes%tr_fluxes)) .and. &
       coupler_type_initialized(iob%fluxes)) &
     call coupler_type_spawn(iob%fluxes, fluxes%tr_fluxes, &
                             (/is,is,ie,ie/), (/js,js,je,je/))
   !   It might prove valuable to use the same array extents as the rest of the
   ! ocean model, rather than using haloless arrays, in which case the last line
   ! would be: (             (/isd,is,ie,ied/), (/jsd,js,je,jed/))
   if (cs%allow_flux_adjustments) then
     fluxes%heat_added(:,:)=0.0
     fluxes%salt_flux_added(:,:)=0.0
   endif
   ! allocation and initialization on first call to this routine
   if (cs%area_surf < 0.0) then
     do j=js,je ; do i=is,ie
       work_sum(i,j) = g%areaT(i,j) * g%mask2dT(i,j)
     enddo; enddo
     cs%area_surf = reproducing_sum(work_sum, isr, ier, jsr, jer)
   endif    ! endif for allocation and initialization
   do j=js,je ; do i=is,ie
     fluxes%salt_flux(i,j) = 0.0
     fluxes%vprec(i,j) = 0.0
   enddo; enddo
   ! Salinity restoring logic
   if (restore_salinity) then
     call time_interp_external(cs%id_srestore,time,data_restore)
     ! open_ocn_mask indicates where to restore salinity (1 means restore, 0 does not)
     open_ocn_mask(:,:) = 1.0
     if (cs%mask_srestore_under_ice) then ! Do not restore under sea-ice
       do j=js,je ; do i=is,ie
         if (sfc_state%SST(i,j) <= -0.0539*sfc_state%SSS(i,j)) open_ocn_mask(i,j)=0.0
       enddo; enddo
     endif
     if (cs%salt_restore_as_sflux) then
       do j=js,je ; do i=is,ie
         delta_sss = data_restore(i,j)- sfc_state%SSS(i,j)
         delta_sss = sign(1.0,delta_sss)*min(abs(delta_sss),cs%max_delta_srestore)
         fluxes%salt_flux(i,j) = 1.e-3*g%mask2dT(i,j) * (cs%Rho0*cs%Flux_const)* &
              (cs%basin_mask(i,j)*open_ocn_mask(i,j)*cs%srestore_mask(i,j)) *delta_sss  ! kg Salt m-2 s-1
       enddo; enddo
       if (cs%adjust_net_srestore_to_zero) then
         if (cs%adjust_net_srestore_by_scaling) then
           call adjust_area_mean_to_zero(fluxes%salt_flux, g, fluxes%saltFluxGlobalScl)
           fluxes%saltFluxGlobalAdj = 0.
         else
           work_sum(is:ie,js:je) = g%areaT(is:ie,js:je)*fluxes%salt_flux(is:ie,js:je)
           fluxes%saltFluxGlobalAdj = reproducing_sum(work_sum(:,:), isr,ier, jsr,jer)/cs%area_surf
           fluxes%salt_flux(is:ie,js:je) = fluxes%salt_flux(is:ie,js:je) - fluxes%saltFluxGlobalAdj
         endif
       endif
       fluxes%salt_flux_added(is:ie,js:je) = fluxes%salt_flux(is:ie,js:je) ! Diagnostic
     else
       do j=js,je ; do i=is,ie
         if (g%mask2dT(i,j) > 0.5) then
           delta_sss = sfc_state%SSS(i,j) - data_restore(i,j)
           delta_sss = sign(1.0,delta_sss)*min(abs(delta_sss),cs%max_delta_srestore)
           fluxes%vprec(i,j) = (cs%basin_mask(i,j)*open_ocn_mask(i,j)*cs%srestore_mask(i,j))* &
                (cs%Rho0*cs%Flux_const) * &
                delta_sss / (0.5*(sfc_state%SSS(i,j) + data_restore(i,j)))
         endif
       enddo; enddo
       if (cs%adjust_net_srestore_to_zero) then
         if (cs%adjust_net_srestore_by_scaling) then
           call adjust_area_mean_to_zero(fluxes%vprec, g, fluxes%vPrecGlobalScl)
           fluxes%vPrecGlobalAdj = 0.
         else
           work_sum(is:ie,js:je) = g%areaT(is:ie,js:je)*fluxes%vprec(is:ie,js:je)
           fluxes%vPrecGlobalAdj = reproducing_sum(work_sum(:,:), isr, ier, jsr, jer) / cs%area_surf
           do j=js,je ; do i=is,ie
             fluxes%vprec(i,j) = ( fluxes%vprec(i,j) - fluxes%vPrecGlobalAdj ) * g%mask2dT(i,j)
           enddo; enddo
         endif
       endif
     endif
   endif
   ! SST restoring logic
   if (restore_sst) then
     call time_interp_external(cs%id_trestore,time,data_restore)
     do j=js,je ; do i=is,ie
       delta_sst = data_restore(i,j)- sfc_state%SST(i,j)
       delta_sst = sign(1.0,delta_sst)*min(abs(delta_sst),cs%max_delta_trestore)
       fluxes%heat_added(i,j) = g%mask2dT(i,j) * cs%trestore_mask(i,j) * &
                       (cs%Rho0*fluxes%C_p) * delta_sst * cs%Flux_const   ! W m-2
     enddo; enddo
   endif
   ! obtain fluxes from IOB; note the staggering of indices
   i0 = 0; j0 = 0
   do j=js,je ; do i=is,ie
     ! liquid precipitation (rain)
     if (associated(iob%lprec)) &
       fluxes%lprec(i,j) =  iob%lprec(i-i0,j-j0) * g%mask2dT(i,j)
     ! frozen precipitation (snow)
     if (associated(iob%fprec)) &
       fluxes%fprec(i,j) = iob%fprec(i-i0,j-j0) * g%mask2dT(i,j)
     ! evaporation
     if (associated(iob%q_flux)) &
       fluxes%evap(i,j) = iob%q_flux(i-i0,j-j0) * g%mask2dT(i,j)
     ! liquid runoff flux
     if (associated(iob%rofl_flux)) then
        fluxes%lrunoff(i,j) = iob%rofl_flux(i-i0,j-j0) * g%mask2dT(i,j)
     else if (associated(iob%runoff)) then
        fluxes%lrunoff(i,j) = iob%runoff(i-i0,j-j0) * g%mask2dT(i,j)
     end if
     ! ice runoff flux
     if (associated(iob%rofi_flux)) then
        fluxes%frunoff(i,j) = iob%rofi_flux(i-i0,j-j0) * g%mask2dT(i,j)
     else if (associated(iob%calving)) then
        fluxes%frunoff(i,j) = iob%calving(i-i0,j-j0) * g%mask2dT(i,j)
     end if
     if (associated(iob%ustar_berg)) &
          fluxes%ustar_berg(i,j) = us%m_to_Z * iob%ustar_berg(i-i0,j-j0) * g%mask2dT(i,j)
     if (associated(iob%area_berg)) &
          fluxes%area_berg(i,j) = iob%area_berg(i-i0,j-j0) * g%mask2dT(i,j)
     if (associated(iob%mass_berg)) &
          fluxes%mass_berg(i,j) = iob%mass_berg(i-i0,j-j0) * g%mask2dT(i,j)
     ! GMM, cime does not not have an equivalent for heat_content_lrunoff and
     ! heat_content_frunoff. I am seeting these to zero for now.
     if (associated(fluxes%heat_content_lrunoff)) &
       fluxes%heat_content_lrunoff(i,j) = 0.0 * g%mask2dT(i,j)
     if (associated(fluxes%heat_content_frunoff)) &
       fluxes%heat_content_frunoff(i,j) = 0.0 * g%mask2dT(i,j)
     if (associated(iob%calving_hflx)) &
          fluxes%heat_content_frunoff(i,j) = iob%calving_hflx(i-i0,j-j0) * g%mask2dT(i,j)
     ! longwave radiation, sum up and down (W/m2)
     if (associated(iob%lw_flux)) &
          fluxes%LW(i,j) = iob%lw_flux(i-i0,j-j0) * g%mask2dT(i,j)
     ! sensible heat flux (W/m2)
     if (associated(iob%t_flux)) &
          fluxes%sens(i,j) = iob%t_flux(i-i0,j-j0) * g%mask2dT(i,j)
     ! sea ice and snow melt heat flux [W/m2]
     if (associated(iob%seaice_melt_heat)) &
          fluxes%seaice_melt_heat(i,j) = g%mask2dT(i,j) * iob%seaice_melt_heat(i-i0,j-j0)
     ! water flux due to sea ice and snow melt [kg/m2/s]
     if (associated(iob%seaice_melt)) &
          fluxes%seaice_melt(i,j) = g%mask2dT(i,j) * iob%seaice_melt(i-i0,j-j0)
     ! latent heat flux (W/m^2)
     fluxes%latent(i,j) = 0.0
     ! contribution from frozen ppt
     if (associated(iob%fprec)) then
       fluxes%latent(i,j)              = fluxes%latent(i,j) + iob%fprec(i-i0,j-j0)*cs%latent_heat_fusion
       fluxes%latent_fprec_diag(i,j)   = g%mask2dT(i,j) * iob%fprec(i-i0,j-j0)*cs%latent_heat_fusion
     endif
     ! contribution from frozen runoff
     if (associated(fluxes%frunoff)) then
       fluxes%latent(i,j)              = fluxes%latent(i,j) + iob%rofi_flux(i-i0,j-j0)*cs%latent_heat_fusion
       fluxes%latent_frunoff_diag(i,j) = g%mask2dT(i,j) * iob%rofi_flux(i-i0,j-j0)*cs%latent_heat_fusion
     endif
     ! contribution from evaporation
     if (associated(iob%q_flux)) then
       fluxes%latent(i,j)             = fluxes%latent(i,j) + iob%q_flux(i-i0,j-j0)*cs%latent_heat_vapor
       fluxes%latent_evap_diag(i,j)  = g%mask2dT(i,j) * iob%q_flux(i-i0,j-j0)*cs%latent_heat_vapor
     endif
     fluxes%latent(i,j) = g%mask2dT(i,j) * fluxes%latent(i,j)
     if (associated(iob%sw_flux_vis_dir)) &
       fluxes%sw_vis_dir(i,j) = g%mask2dT(i,j) * iob%sw_flux_vis_dir(i-i0,j-j0)
     if (associated(iob%sw_flux_vis_dif)) &
       fluxes%sw_vis_dif(i,j) = g%mask2dT(i,j) * iob%sw_flux_vis_dif(i-i0,j-j0)
     if (associated(iob%sw_flux_nir_dir)) &
       fluxes%sw_nir_dir(i,j) = g%mask2dT(i,j) * iob%sw_flux_nir_dir(i-i0,j-j0)
     if (associated(iob%sw_flux_nir_dif)) &
       fluxes%sw_nir_dif(i,j) = g%mask2dT(i,j) * iob%sw_flux_nir_dif(i-i0,j-j0)
     fluxes%sw(i,j) = fluxes%sw_vis_dir(i,j) + fluxes%sw_vis_dif(i,j) + &
                      fluxes%sw_nir_dir(i,j) + fluxes%sw_nir_dif(i,j)
   enddo; enddo
   ! applied surface pressure from atmosphere and cryosphere
   if (associated(iob%p)) then
      if (cs%max_p_surf >= 0.0) then
         do j=js,je ; do i=is,ie
            fluxes%p_surf_full(i,j) = g%mask2dT(i,j) * iob%p(i-i0,j-j0)
            fluxes%p_surf(i,j) = min(fluxes%p_surf_full(i,j),cs%max_p_surf)
         enddo; enddo
      else
         do j=js,je ; do i=is,ie
            fluxes%p_surf_full(i,j) = g%mask2dT(i,j) * iob%p(i-i0,j-j0)
            fluxes%p_surf(i,j) = fluxes%p_surf_full(i,j)
         enddo; enddo
      endif
      fluxes%accumulate_p_surf = .true. ! Multiple components may contribute to surface pressure.
   endif
   if (associated(iob%salt_flux)) then
     do j=js,je ; do i=is,ie
       fluxes%salt_flux(i,j)    = g%mask2dT(i,j)*(fluxes%salt_flux(i,j) + iob%salt_flux(i-i0,j-j0))
       fluxes%salt_flux_in(i,j) = g%mask2dT(i,j)*( iob%salt_flux(i-i0,j-j0) )
     enddo ; enddo
   endif
   ! adjust the NET fresh-water flux to zero, if flagged
   if (cs%adjust_net_fresh_water_to_zero) then
     sign_for_net_fw_bug = 1.
     if (cs%use_net_FW_adjustment_sign_bug) sign_for_net_fw_bug = -1.
     do j=js,je ; do i=is,ie
       net_fw(i,j) = (((fluxes%lprec(i,j)   + fluxes%fprec(i,j) + fluxes%seaice_melt(i,j)) + &
           (fluxes%lrunoff(i,j) + fluxes%frunoff(i,j))) + &
           (fluxes%evap(i,j)    + fluxes%vprec(i,j)) ) * g%areaT(i,j)
       net_fw2(i,j) = net_fw(i,j)/g%areaT(i,j)
     enddo; enddo
     if (cs%adjust_net_fresh_water_by_scaling) then
       call adjust_area_mean_to_zero(net_fw2, g, fluxes%netFWGlobalScl)
       do j=js,je ; do i=is,ie
         fluxes%vprec(i,j) = fluxes%vprec(i,j) + (net_fw2(i,j) - net_fw(i,j)/g%areaT(i,j)) * g%mask2dT(i,j)
       enddo; enddo
     else
       fluxes%netFWGlobalAdj = reproducing_sum(net_fw(:,:), isr, ier, jsr, jer) / cs%area_surf
       do j=js,je ; do i=is,ie
         fluxes%vprec(i,j) = ( fluxes%vprec(i,j) - fluxes%netFWGlobalAdj ) * g%mask2dT(i,j)
       enddo; enddo
     endif
   endif
   if (coupler_type_initialized(fluxes%tr_fluxes) .and. &
       coupler_type_initialized(iob%fluxes)) &
     call coupler_type_copy_data(iob%fluxes, fluxes%tr_fluxes)
   if (cs%allow_flux_adjustments) then
     ! Apply adjustments to fluxes
     call apply_flux_adjustments(g, cs, time, fluxes)
   endif
   ! Allow for user-written code to alter fluxes after all the above
   call user_alter_forcing(sfc_state, fluxes, time, g, cs%urf_CS)
   call cpu_clock_end(id_clock_forcing)
References mom_spatial_means::adjust_area_mean_to_zero(), apply_flux_adjustments(), and id_clock_forcing.
convert_iob_to_forces()
subroutine, public mom_surface_forcing_mct::convert_iob_to_forces (type(ice_ocean_boundary_type), intent(in), target IOB, type(mech_forcing), intent(inout) forces, integer, dimension(4), intent(in) index_bounds, type(time_type), intent(in) Time, type(ocean_grid_type), intent(inout) G, type(unit_scale_type), intent(in) US, type(surface_forcing_cs), pointer CS)
This subroutine translates the Ice_ocean_boundary_type into a MOM mechanical forcing type, including changes of units, sign conventions, and putting the fields into arrays with MOM-standard halos.
Parameters
[in] iob An ice-ocean boundary type with fluxes to drive
[in,out] forces A structure with the driving mechanical forces
[in] index_bounds The i- and j- size of the arrays in IOB.
[in] time The time of the fluxes, used for interpolating the salinity to the right time, when it is being restored.
[in,out] g The ocean's grid structure
[in] us A dimensional unit scaling type
cs A pointer to the control structure returned by a previous call to surface_forcing_init.
Definition at line 581 of file mom_surface_forcing_mct.F90.
   type(ice_ocean_boundary_type), &
                    target, intent(in)    :: IOB    !< An ice-ocean boundary type with fluxes to drive
                                                    !! the ocean in a coupled model
   type(mech_forcing),      intent(inout) :: forces !< A structure with the driving mechanical forces
   integer, dimension(4),   intent(in)    :: index_bounds !< The i- and j- size of the arrays in IOB.
   type(time_type),         intent(in)    :: Time   !< The time of the fluxes, used for interpolating the
                                                    !! salinity to the right time, when it is being restored.
   type(ocean_grid_type),   intent(inout) :: G      !< The ocean's grid structure
   type(unit_scale_type),   intent(in)    :: US     !< A dimensional unit scaling type
   type(surface_forcing_CS),pointer       :: CS     !< A pointer to the control structure returned by a
                                                    !! previous call to surface_forcing_init.
   ! local variables
   real, dimension(SZIB_(G),SZJB_(G)) :: &
     taux_at_q, & !< Zonal wind stresses at q points [Pa]
     tauy_at_q    !< Meridional wind stresses at q points [Pa]
   real, dimension(SZI_(G),SZJ_(G)) :: &
     rigidity_at_h, & !< Ice rigidity at tracer points (m3 s-1)
     taux_at_h, & !< Zonal wind stresses at h points [Pa]
     tauy_at_h    !< Meridional wind stresses at h points [Pa]
   real :: gustiness     !< unresolved gustiness that contributes to ustar [Pa]
   real :: Irho0         !< inverse of the mean density in (m^3/kg)
   real :: taux2, tauy2  !< squared wind stresses (Pa^2)
   real :: tau_mag       !< magnitude of the wind stress [Pa]
   real :: I_GEarth      !< 1.0 / G%G_Earth  (s^2/m)
   real :: Kv_rho_ice    !< (CS%kv_sea_ice / CS%density_sea_ice) ( m^5/(s*kg) )
   real :: mass_ice      !< mass of sea ice at a face (kg/m^2)
   real :: mass_eff      !< effective mass of sea ice for rigidity (kg/m^2)
   integer :: wind_stagger  !< AGRID, BGRID_NE, or CGRID_NE (integers from MOM_domains)
   integer :: i, j, is, ie, js, je, Isq, Ieq, Jsq, Jeq, i0, j0
   integer :: isd, ied, jsd, jed, IsdB, IedB, JsdB, JedB, isr, ier, jsr, jer
   integer :: isc_bnd, iec_bnd, jsc_bnd, jec_bnd
   call cpu_clock_begin(id_clock_forcing)
   isc_bnd = index_bounds(1) ; iec_bnd = index_bounds(2)
   jsc_bnd = index_bounds(3) ; jec_bnd = index_bounds(4)
   is   = g%isc   ; ie   = g%iec    ; js   = g%jsc   ; je   = g%jec
   isq  = g%IscB  ; ieq  = g%IecB   ; jsq  = g%JscB  ; jeq  = g%JecB
   isd  = g%isd   ; ied  = g%ied    ; jsd  = g%jsd   ; jed  = g%jed
   isdb = g%IsdB  ; iedb = g%IedB   ; jsdb = g%JsdB  ; jedb = g%JedB
   isr = is-isd+1 ; ier  = ie-isd+1 ; jsr = js-jsd+1 ; jer = je-jsd+1
  !i0 = is - isc_bnd ; j0 = js - jsc_bnd
   i0 = 0; j0 = 0
   irho0 = 1.0/cs%Rho0
   ! allocation and initialization if this is the first time that this
   ! mechanical forcing type has been used.
   if (.not.forces%initialized) then
     call allocate_mech_forcing(g, forces, stress=.true., ustar=.true., press=.true.)
     call safe_alloc_ptr(forces%p_surf,isd,ied,jsd,jed)
     call safe_alloc_ptr(forces%p_surf_full,isd,ied,jsd,jed)
     if (cs%rigid_sea_ice) then
       call safe_alloc_ptr(forces%rigidity_ice_u,isdb,iedb,jsd,jed)
       call safe_alloc_ptr(forces%rigidity_ice_v,isd,ied,jsdb,jedb)
     endif
     forces%initialized = .true.
   endif
   if ( (associated(iob%area_berg) .and. (.not. associated(forces%area_berg))) .or. &
        (associated(iob%mass_berg) .and. (.not. associated(forces%mass_berg))) ) &
     call allocate_mech_forcing(g, forces, iceberg=.true.)
   if (associated(iob%ice_rigidity)) then
     rigidity_at_h(:,:) = 0.0
     call safe_alloc_ptr(forces%rigidity_ice_u,isdb,iedb,jsd,jed)
     call safe_alloc_ptr(forces%rigidity_ice_v,isd,ied,jsdb,jedb)
   endif
   forces%accumulate_rigidity = .true. ! Multiple components may contribute to rigidity.
   if (associated(forces%rigidity_ice_u)) forces%rigidity_ice_u(:,:) = 0.0
   if (associated(forces%rigidity_ice_v)) forces%rigidity_ice_v(:,:) = 0.0
   !applied surface pressure from atmosphere and cryosphere
   if (cs%use_limited_P_SSH) then
      forces%p_surf_SSH => forces%p_surf
   else
      forces%p_surf_SSH => forces%p_surf_full
   endif
   if (associated(iob%p)) then
     if (cs%max_p_surf >= 0.0) then
       do j=js,je ; do i=is,ie
         forces%p_surf_full(i,j) = g%mask2dT(i,j) * iob%p(i-i0,j-j0)
         forces%p_surf(i,j) = min(forces%p_surf_full(i,j),cs%max_p_surf)
       enddo ; enddo
     else
       do j=js,je ; do i=is,ie
         forces%p_surf_full(i,j) = g%mask2dT(i,j) * iob%p(i-i0,j-j0)
         forces%p_surf(i,j) = forces%p_surf_full(i,j)
       enddo ; enddo
     endif
   else
     do j=js,je ; do i=is,ie
       forces%p_surf_full(i,j) = 0.0
       forces%p_surf(i,j) = 0.0
     enddo ; enddo
   endif
   forces%accumulate_p_surf = .true. ! Multiple components may contribute to surface pressure.
   ! GMM, CIME uses AGRID. All the BGRID_NE code can be cleaned later
   wind_stagger = agrid
   if (wind_stagger == bgrid_ne) then
     ! This is necessary to fill in the halo points.
     taux_at_q(:,:) = 0.0 ; tauy_at_q(:,:) = 0.0
   endif
   if (wind_stagger == agrid) then
     ! This is necessary to fill in the halo points.
     taux_at_h(:,:) = 0.0 ; tauy_at_h(:,:) = 0.0
   endif
   ! obtain fluxes from IOB; note the staggering of indices
   do j=js,je ; do i=is,ie
     if (associated(iob%area_berg)) &
       forces%area_berg(i,j) = iob%area_berg(i-i0,j-j0) * g%mask2dT(i,j)
     if (associated(iob%mass_berg)) &
       forces%mass_berg(i,j) = iob%mass_berg(i-i0,j-j0) * g%mask2dT(i,j)
     if (associated(iob%ice_rigidity)) &
       rigidity_at_h(i,j) = iob%ice_rigidity(i-i0,j-j0) * g%mask2dT(i,j)
     if (wind_stagger == bgrid_ne) then
       if (associated(iob%u_flux)) taux_at_q(i,j) = iob%u_flux(i-i0,j-j0) * cs%wind_stress_multiplier
       if (associated(iob%v_flux)) tauy_at_q(i,j) = iob%v_flux(i-i0,j-j0) * cs%wind_stress_multiplier
     elseif (wind_stagger == agrid) then
       if (associated(iob%u_flux)) taux_at_h(i,j) = iob%u_flux(i-i0,j-j0) * cs%wind_stress_multiplier
       if (associated(iob%v_flux)) tauy_at_h(i,j) = iob%v_flux(i-i0,j-j0) * cs%wind_stress_multiplier
     else ! C-grid wind stresses.
       if (associated(iob%u_flux)) forces%taux(i,j) = iob%u_flux(i-i0,j-j0) * cs%wind_stress_multiplier
       if (associated(iob%v_flux)) forces%tauy(i,j) = iob%v_flux(i-i0,j-j0) * cs%wind_stress_multiplier
     endif
   enddo ; enddo
   ! surface momentum stress related fields as function of staggering
   if (wind_stagger == bgrid_ne) then
     if (g%symmetric) &
       call fill_symmetric_edges(taux_at_q, tauy_at_q, g%Domain, stagger=bgrid_ne)
     call pass_vector(taux_at_q, tauy_at_q, g%Domain, stagger=bgrid_ne, halo=1)
     do j=js,je ; do i=isq,ieq
       forces%taux(i,j) = 0.0
       if ((g%mask2dBu(i,j) + g%mask2dBu(i,j-1)) > 0) &
         forces%taux(i,j) = (g%mask2dBu(i,j)*taux_at_q(i,j) + &
                             g%mask2dBu(i,j-1)*taux_at_q(i,j-1)) / &
                            (g%mask2dBu(i,j) + g%mask2dBu(i,j-1))
     enddo; enddo
     do j=jsq,jeq ; do i=is,ie
       forces%tauy(i,j) = 0.0
       if ((g%mask2dBu(i,j) + g%mask2dBu(i-1,j)) > 0) &
         forces%tauy(i,j) = (g%mask2dBu(i,j)*tauy_at_q(i,j) + &
                             g%mask2dBu(i-1,j)*tauy_at_q(i-1,j)) / &
                            (g%mask2dBu(i,j) + g%mask2dBu(i-1,j))
     enddo; enddo
     ! ustar is required for the bulk mixed layer formulation. The background value
     ! of 0.02 Pa is a relatively small value intended to give reasonable behavior
     ! in regions of very weak winds.
     do j=js,je ; do i=is,ie
       tau_mag = 0.0 ; gustiness = cs%gust_const
       if (((g%mask2dBu(i,j) + g%mask2dBu(i-1,j-1)) + &
            (g%mask2dBu(i,j-1) + g%mask2dBu(i-1,j))) > 0) then
         tau_mag = sqrt(((g%mask2dBu(i,j)*(taux_at_q(i,j)**2 + tauy_at_q(i,j)**2) + &
              g%mask2dBu(i-1,j-1)*(taux_at_q(i-1,j-1)**2 + tauy_at_q(i-1,j-1)**2)) + &
              (g%mask2dBu(i,j-1)*(taux_at_q(i,j-1)**2 + tauy_at_q(i,j-1)**2) + &
              g%mask2dBu(i-1,j)*(taux_at_q(i-1,j)**2 + tauy_at_q(i-1,j)**2)) ) / &
              ((g%mask2dBu(i,j) + g%mask2dBu(i-1,j-1)) + (g%mask2dBu(i,j-1) + g%mask2dBu(i-1,j))) )
         if (cs%read_gust_2d) gustiness = cs%gust(i,j)
       endif
       forces%ustar(i,j) = us%m_to_Z * sqrt(gustiness*irho0 + irho0*tau_mag)
     enddo; enddo
   elseif (wind_stagger == agrid) then
     call pass_vector(taux_at_h, tauy_at_h, g%Domain, to_all+omit_corners, stagger=agrid, halo=1)
     do j=js,je ; do i=isq,ieq
       forces%taux(i,j) = 0.0
       if ((g%mask2dT(i,j) + g%mask2dT(i+1,j)) > 0) &
         forces%taux(i,j) = (g%mask2dT(i,j)*taux_at_h(i,j) + &
                             g%mask2dT(i+1,j)*taux_at_h(i+1,j)) / &
                            (g%mask2dT(i,j) + g%mask2dT(i+1,j))
     enddo; enddo
     do j=jsq,jeq ; do i=is,ie
       forces%tauy(i,j) = 0.0
       if ((g%mask2dT(i,j) + g%mask2dT(i,j+1)) > 0) &
         forces%tauy(i,j) = (g%mask2dT(i,j)*tauy_at_h(i,j) + &
                             g%mask2dT(i,j+1)*tauy_at_h(i,j+1)) / &
                            (g%mask2dT(i,j) + g%mask2dT(i,j+1))
     enddo; enddo
     do j=js,je ; do i=is,ie
       gustiness = cs%gust_const
       if (cs%read_gust_2d .and. (g%mask2dT(i,j) > 0)) gustiness = cs%gust(i,j)
       forces%ustar(i,j) = us%m_to_Z * sqrt(gustiness*irho0 + irho0 * g%mask2dT(i,j) * &
                                sqrt(taux_at_h(i,j)**2 + tauy_at_h(i,j)**2))
     enddo; enddo
   else ! C-grid wind stresses.
     if (g%symmetric) &
       call fill_symmetric_edges(forces%taux, forces%tauy, g%Domain)
     call pass_vector(forces%taux, forces%tauy, g%Domain, halo=1)
     do j=js,je ; do i=is,ie
       taux2 = 0.0
       if ((g%mask2dCu(i-1,j) + g%mask2dCu(i,j)) > 0) &
         taux2 = (g%mask2dCu(i-1,j)*forces%taux(i-1,j)**2 + &
                  g%mask2dCu(i,j)*forces%taux(i,j)**2) / (g%mask2dCu(i-1,j) + g%mask2dCu(i,j))
       tauy2 = 0.0
       if ((g%mask2dCv(i,j-1) + g%mask2dCv(i,j)) > 0) &
         tauy2 = (g%mask2dCv(i,j-1)*forces%tauy(i,j-1)**2 + &
                  g%mask2dCv(i,j)*forces%tauy(i,j)**2) / (g%mask2dCv(i,j-1) + g%mask2dCv(i,j))
       if (cs%read_gust_2d) then
         forces%ustar(i,j) = us%m_to_Z * sqrt(cs%gust(i,j)*irho0 + irho0*sqrt(taux2 + tauy2))
       else
         forces%ustar(i,j) = us%m_to_Z * sqrt(cs%gust_const*irho0 + irho0*sqrt(taux2 + tauy2))
       endif
     enddo; enddo
   endif   ! endif for wind related fields
   ! sea ice related dynamic fields
   if (associated(iob%ice_rigidity)) then
     call pass_var(rigidity_at_h, g%Domain, halo=1)
     do i=is-1,ie ; do j=js,je
       forces%rigidity_ice_u(i,j) = forces%rigidity_ice_u(i,j) + &
               min(rigidity_at_h(i,j), rigidity_at_h(i+1,j))
     enddo ; enddo
     do i=is,ie ; do j=js-1,je
       forces%rigidity_ice_v(i,j) = forces%rigidity_ice_v(i,j) + &
               min(rigidity_at_h(i,j), rigidity_at_h(i,j+1))
     enddo ; enddo
   endif
   if (cs%rigid_sea_ice) then
     call pass_var(forces%p_surf_full, g%Domain, halo=1)
     i_gearth = 1.0 / g%G_Earth
     kv_rho_ice = (cs%kv_sea_ice / cs%density_sea_ice)
     do i=is-1,ie ; do j=js,je
       mass_ice = min(forces%p_surf_full(i,j), forces%p_surf_full(i+1,j)) * i_gearth
       mass_eff = 0.0
       if (mass_ice > cs%rigid_sea_ice_mass) then
         mass_eff = (mass_ice - cs%rigid_sea_ice_mass) **2 / &
                    (mass_ice + cs%rigid_sea_ice_mass)
       endif
       forces%rigidity_ice_u(i,j) = forces%rigidity_ice_u(i,j) + kv_rho_ice * mass_eff
     enddo ; enddo
     do i=is,ie ; do j=js-1,je
       mass_ice = min(forces%p_surf_full(i,j), forces%p_surf_full(i,j+1)) * i_gearth
       mass_eff = 0.0
       if (mass_ice > cs%rigid_sea_ice_mass) then
         mass_eff = (mass_ice - cs%rigid_sea_ice_mass) **2 / &
                    (mass_ice + cs%rigid_sea_ice_mass)
       endif
       forces%rigidity_ice_v(i,j) = forces%rigidity_ice_v(i,j) + kv_rho_ice * mass_eff
     enddo ; enddo
   endif
   if (cs%allow_flux_adjustments) then
     ! Apply adjustments to forces
     call apply_force_adjustments(g, cs, time, forces)
   endif
 !###  ! Allow for user-written code to alter fluxes after all the above
 !###  call user_alter_mech_forcing(forces, Time, G, CS%urf_CS)
   call cpu_clock_end(id_clock_forcing)
References mom_forcing_type::allocate_mech_forcing(), apply_force_adjustments(), and id_clock_forcing.
forcing_save_restart()
subroutine, public mom_surface_forcing_mct::forcing_save_restart (type(surface_forcing_cs), pointer CS, type(ocean_grid_type), intent(inout) G, type(time_type), intent(in) Time, character(len=*), intent(in) directory, logical, intent(in), optional time_stamped, character(len=*), intent(in), optional filename_suffix)
Save any restart files associated with the surface forcing.
Parameters
cs A pointer to the control structure returned by a previous call to surface_forcing_init
[in,out] g The ocean's grid structure
[in] time The current model time
[in] directory The directory into which to write the restart files
[in] time_stamped If true, the restart file names include a unique time stamp. The default is false.
[in] filename_suffix An optional suffix (e.g., a time- stamp) to append to the restart file names.
Definition at line 969 of file mom_surface_forcing_mct.F90.
   type(surface_forcing_CS),   pointer       :: CS   !< A pointer to the control structure returned
                                                     !! by a previous call to surface_forcing_init
   type(ocean_grid_type),      intent(inout) :: G    !< The ocean's grid structure
   type(time_type),            intent(in)    :: Time !< The current model time
   character(len=*),           intent(in)    :: directory !< The directory into which to write the
                                                     !! restart files
   logical,          optional, intent(in)    :: time_stamped !< If true, the restart file names include
                                                     !! a unique time stamp.  The default is false.
   character(len=*), optional, intent(in)    :: filename_suffix !< An optional suffix (e.g., a time-
                                                     !! stamp) to append to the restart file names.
   if (.not.associated(cs)) return
   if (.not.associated(cs%restart_CSp)) return
   call save_restart(directory, time, g, cs%restart_CSp, time_stamped)
References mom_restart::save_restart().
Referenced by mom_ocean_model_mct::ocean_model_restart(), mom_ocean_model_mct::ocean_model_save_restart(), and ocn_comp_mct::ocn_run_mct().
ice_ocn_bnd_type_chksum()
subroutine, public mom_surface_forcing_mct::ice_ocn_bnd_type_chksum (character(len=*), intent(in) id, integer, intent(in) timestep, type(ice_ocean_boundary_type), intent(in) iobt)
Write out a set of messages with checksums of the fields in an ice_ocen_boundary type.
Parameters
[in] id An identifying string for this call
[in] timestep The number of elapsed timesteps
[in] iobt An ice-ocean boundary type with fluxes to drive the
Definition at line 1339 of file mom_surface_forcing_mct.F90.
   character(len=*), intent(in) :: id     !< An identifying string for this call
   integer,          intent(in) :: timestep !< The number of elapsed timesteps
   type(ice_ocean_boundary_type), &
                     intent(in) :: iobt   !< An ice-ocean boundary type with fluxes to drive the
                                          !! ocean in a coupled model whose checksums are reported
   ! local variables
   integer ::   n,m, outunit
   outunit = stdout()
   write(outunit,*) "BEGIN CHECKSUM(ice_ocean_boundary_type):: ", id, timestep
   write(outunit,100) 'iobt%u_flux         '   , mpp_chksum( iobt%u_flux         )
   write(outunit,100) 'iobt%v_flux         '   , mpp_chksum( iobt%v_flux         )
   write(outunit,100) 'iobt%t_flux         '   , mpp_chksum( iobt%t_flux         )
   write(outunit,100) 'iobt%q_flux         '   , mpp_chksum( iobt%q_flux         )
   write(outunit,100) 'iobt%salt_flux      '   , mpp_chksum( iobt%salt_flux      )
   write(outunit,100) 'iobt%seaice_melt_heat'  , mpp_chksum( iobt%seaice_melt_heat)
   write(outunit,100) 'iobt%seaice_melt    '   , mpp_chksum( iobt%seaice_melt    )
   write(outunit,100) 'iobt%lw_flux        '   , mpp_chksum( iobt%lw_flux        )
   write(outunit,100) 'iobt%sw_flux_vis_dir'   , mpp_chksum( iobt%sw_flux_vis_dir)
   write(outunit,100) 'iobt%sw_flux_vis_dif'   , mpp_chksum( iobt%sw_flux_vis_dif)
   write(outunit,100) 'iobt%sw_flux_nir_dir'   , mpp_chksum( iobt%sw_flux_nir_dir)
   write(outunit,100) 'iobt%sw_flux_nir_dif'   , mpp_chksum( iobt%sw_flux_nir_dif)
   write(outunit,100) 'iobt%lprec          '   , mpp_chksum( iobt%lprec          )
   write(outunit,100) 'iobt%fprec          '   , mpp_chksum( iobt%fprec          )
   write(outunit,100) 'iobt%runoff         '   , mpp_chksum( iobt%runoff         )
   write(outunit,100) 'iobt%calving        '   , mpp_chksum( iobt%calving        )
   write(outunit,100) 'iobt%p              '   , mpp_chksum( iobt%p              )
   if (associated(iobt%ustar_berg)) &
     write(outunit,100) 'iobt%ustar_berg     ' , mpp_chksum( iobt%ustar_berg )
   if (associated(iobt%area_berg)) &
     write(outunit,100) 'iobt%area_berg      ' , mpp_chksum( iobt%area_berg  )
   if (associated(iobt%mass_berg)) &
     write(outunit,100) 'iobt%mass_berg      ' , mpp_chksum( iobt%mass_berg  )
 100 FORMAT("   CHECKSUM::",a20," = ",z20)
   call coupler_type_write_chksums(iobt%fluxes, outunit, 'iobt%')
surface_forcing_end()
subroutine, private mom_surface_forcing_mct::surface_forcing_end (type(surface_forcing_cs), pointer CS, type(forcing), intent(inout), optional fluxes) private
Clean up and deallocate any memory associated with this module and its children.
Parameters
cs A pointer to the control structure returned by a previous call to surface_forcing_init, it will be deallocated here.
[in,out] fluxes A structure containing pointers to all possible mass, heat or salt flux forcing fields. If present, it will be deallocated here.
Definition at line 1321 of file mom_surface_forcing_mct.F90.
   type(surface_forcing_CS), pointer       :: CS !< A pointer to the control structure returned by
                                                 !! a previous call to surface_forcing_init, it will
                                                 !! be deallocated here.
   type(forcing), optional,  intent(inout) :: fluxes !< A structure containing pointers to all
                                                 !! possible mass, heat or salt flux forcing fields.
                                                 !! If present, it will be deallocated here.
   if (present(fluxes)) call deallocate_forcing_type(fluxes)
 !###  call controlled_forcing_end(CS%ctrl_forcing_CSp)
   if (associated(cs)) deallocate(cs)
   cs => null()
surface_forcing_init()
subroutine, public mom_surface_forcing_mct::surface_forcing_init (type(time_type), intent(in) Time, type(ocean_grid_type), intent(in) G, type(unit_scale_type), intent(in) US, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(surface_forcing_cs), pointer CS, logical, intent(in), optional restore_salt, logical, intent(in), optional restore_temp)
Initialize the surface forcing, including setting parameters and allocating permanent memory.
Parameters
[in] time The current model time
[in] g The ocean's grid structure
[in] us A dimensional unit scaling type
[in] param_file A structure to parse for run-time parameters
[in,out] diag A structure that is used to regulate diagnostic output
cs A pointer that is set to point to the control structure for this module
[in] restore_salt If present and true surface salinity restoring will be applied in this model.
[in] restore_temp If present and true surface temperature restoring will be applied in this model.
Definition at line 988 of file mom_surface_forcing_mct.F90.
   type(time_type),          intent(in)    :: Time !< The current model time
   type(ocean_grid_type),    intent(in)    :: G    !< The ocean's grid structure
   type(unit_scale_type),    intent(in)    :: US   !< A dimensional unit scaling type
   type(param_file_type),    intent(in)    :: param_file !< A structure to parse for run-time parameters
   type(diag_ctrl), target,  intent(inout) :: diag !< A structure that is used to regulate
                                                   !! diagnostic output
   type(surface_forcing_CS), pointer       :: CS   !< A pointer that is set to point to the control
                                                   !! structure for this module
   logical, optional,        intent(in)    :: restore_salt !< If present and true surface salinity
                                                   !! restoring will be applied in this model.
   logical, optional,        intent(in)    :: restore_temp !< If present and true surface temperature
                                                   !! restoring will be applied in this model.
   ! Local variables
   real :: utide  ! The RMS tidal velocity, in m s-1.
   type(directories)  :: dirs
   logical            :: new_sim, iceberg_flux_diags
   type(time_type)    :: Time_frc
   character(len=200) :: TideAmp_file, gust_file, salt_file, temp_file ! Input file names.
 ! This include declares and sets the variable "version".
 #include "version_variable.h"
   character(len=40)  :: mdl = "MOM_surface_forcing_mct"  ! This module's name.
   character(len=48)  :: stagger
   character(len=48)  :: flnam
   character(len=240) :: basin_file
   integer :: i, j, isd, ied, jsd, jed
   isd = g%isd ; ied = g%ied ; jsd = g%jsd ; jed = g%jed
   if (associated(cs)) then
     call mom_error(warning, "surface_forcing_init called with an associated "// &
                             "control structure.")
     return
   endif
   allocate(cs)
   id_clock_forcing=cpu_clock_id('Ocean surface forcing', grain=clock_subcomponent)
   call cpu_clock_begin(id_clock_forcing)
   cs%diag => diag
   call write_version_number(version)
   ! Read all relevant parameters and write them to the model log.
   call log_version(param_file, mdl, version, "")
   call get_param(param_file, mdl, "INPUTDIR", cs%inputdir, &
                  "The directory in which all input files are found.", &
                  default=".")
   cs%inputdir = slasher(cs%inputdir)
   call get_param(param_file, mdl, "ENABLE_THERMODYNAMICS", cs%use_temperature, &
                  "If true, Temperature and salinity are used as state "//&
                  "variables.", default=.true.)
   call get_param(param_file, mdl, "RHO_0", cs%Rho0, &
                  "The mean ocean density used with BOUSSINESQ true to "//&
                  "calculate accelerations and the mass for conservation "//&
                  "properties, or with BOUSSINSEQ false to convert some "//&
                  "parameters from vertical units of m to kg m-2.", &
                  units="kg m-3", default=1035.0)
   call get_param(param_file, mdl, "LATENT_HEAT_FUSION", cs%latent_heat_fusion, &
                  "The latent heat of fusion.", units="J/kg", default=hlf)
   call get_param(param_file, mdl, "LATENT_HEAT_VAPORIZATION", cs%latent_heat_vapor, &
                  "The latent heat of fusion.", units="J/kg", default=hlv)
   call get_param(param_file, mdl, "MAX_P_SURF", cs%max_p_surf, &
                  "The maximum surface pressure that can be exerted by the "//&
                  "atmosphere and floating sea-ice or ice shelves. This is "//&
                  "needed because the FMS coupling structure does not "//&
                  "limit the water that can be frozen out of the ocean and "//&
                  "the ice-ocean heat fluxes are treated explicitly.  No "//&
                  "limit is applied if a negative value is used.", units="Pa", &
                  default=-1.0)
   call get_param(param_file, mdl, "ADJUST_NET_SRESTORE_TO_ZERO", &
                  cs%adjust_net_srestore_to_zero, &
                  "If true, adjusts the salinity restoring seen to zero "//&
                  "whether restoring is via a salt flux or virtual precip.",&
                  default=restore_salt)
   call get_param(param_file, mdl, "ADJUST_NET_SRESTORE_BY_SCALING", &
                  cs%adjust_net_srestore_by_scaling, &
                  "If true, adjustments to salt restoring to achieve zero net are "//&
                  "made by scaling values without moving the zero contour.",&
                  default=.false.)
   call get_param(param_file, mdl, "ADJUST_NET_FRESH_WATER_TO_ZERO", &
                  cs%adjust_net_fresh_water_to_zero, &
                  "If true, adjusts the net fresh-water forcing seen "//&
                  "by the ocean (including restoring) to zero.", default=.false.)
   if (cs%adjust_net_fresh_water_to_zero) &
     call get_param(param_file, mdl, "USE_NET_FW_ADJUSTMENT_SIGN_BUG", &
                  cs%use_net_FW_adjustment_sign_bug, &
                    "If true, use the wrong sign for the adjustment to "//&
                    "the net fresh-water.", default=.false.)
   call get_param(param_file, mdl, "ADJUST_NET_FRESH_WATER_BY_SCALING", &
                  cs%adjust_net_fresh_water_by_scaling, &
                  "If true, adjustments to net fresh water to achieve zero net are "//&
                  "made by scaling values without moving the zero contour.",&
                  default=.false.)
   call get_param(param_file, mdl, "ICE_SALT_CONCENTRATION", &
                  cs%ice_salt_concentration, &
                  "The assumed sea-ice salinity needed to reverse engineer the "//&
                  "melt flux (or ice-ocean fresh-water flux).", &
                  units="kg/kg", default=0.005)
   call get_param(param_file, mdl, "USE_LIMITED_PATM_SSH", cs%use_limited_P_SSH, &
                  "If true, return the sea surface height with the "//&
                  "correction for the atmospheric (and sea-ice) pressure "//&
                  "limited by max_p_surf instead of the full atmospheric "//&
                  "pressure.", default=.true.)
   call get_param(param_file, mdl, "WIND_STAGGER", stagger, &
                  "A case-insensitive character string to indicate the "//&
                  "staggering of the input wind stress field.  Valid "//&
                  "values are 'A', 'B', or 'C'.", default="C")
   if (uppercase(stagger(1:1)) == 'A') then ; cs%wind_stagger = agrid
   elseif (uppercase(stagger(1:1)) == 'B') then ; cs%wind_stagger = bgrid_ne
   elseif (uppercase(stagger(1:1)) == 'C') then ; cs%wind_stagger = cgrid_ne
   else ; call mom_error(fatal,"surface_forcing_init: WIND_STAGGER = "// &
                         trim(stagger)//" is invalid.") ; endif
   call get_param(param_file, mdl, "WIND_STRESS_MULTIPLIER", cs%wind_stress_multiplier, &
                  "A factor multiplying the wind-stress given to the ocean by the "//&
                  "coupler. This is used for testing and should be =1.0 for any "//&
                  "production runs.", default=1.0)
   if (restore_salt) then
     call get_param(param_file, mdl, "FLUXCONST", cs%Flux_const, &
                  "The constant that relates the restoring surface fluxes "//&
                  "to the relative surface anomalies (akin to a piston "//&
                  "velocity).  Note the non-MKS units.", units="m day-1", &
                  fail_if_missing=.true.)
     call get_param(param_file, mdl, "SALT_RESTORE_FILE", cs%salt_restore_file, &
                  "A file in which to find the surface salinity to use for restoring.", &
                  default="salt_restore.nc")
     call get_param(param_file, mdl, "SALT_RESTORE_VARIABLE", cs%salt_restore_var_name, &
                  "The name of the surface salinity variable to read from "//&
                  "SALT_RESTORE_FILE for restoring salinity.", &
                  default="salt")
 ! Convert CS%Flux_const from m day-1 to m s-1.
     cs%Flux_const = cs%Flux_const / 86400.0
     call get_param(param_file, mdl, "SRESTORE_AS_SFLUX", cs%salt_restore_as_sflux, &
                  "If true, the restoring of salinity is applied as a salt "//&
                  "flux instead of as a freshwater flux.", default=.false.)
     call get_param(param_file, mdl, "MAX_DELTA_SRESTORE", cs%max_delta_srestore, &
                  "The maximum salinity difference used in restoring terms.", &
                  units="PSU or g kg-1", default=999.0)
     call get_param(param_file, mdl, "MASK_SRESTORE_UNDER_ICE", &
                  cs%mask_srestore_under_ice, &
                  "If true, disables SSS restoring under sea-ice based on a frazil "//&
                  "criteria (SST<=Tf). Only used when RESTORE_SALINITY is True.",      &
                  default=.false.)
     call get_param(param_file, mdl, "MASK_SRESTORE_MARGINAL_SEAS", &
                  cs%mask_srestore_marginal_seas, &
                  "If true, disable SSS restoring in marginal seas. Only used when "//&
                  "RESTORE_SALINITY is True.", default=.false.)
     call get_param(param_file, mdl, "BASIN_FILE", basin_file, &
                  "A file in which to find the basin masks, in variable 'basin'.", &
                  default="basin.nc")
     basin_file = trim(cs%inputdir) // trim(basin_file)
     call safe_alloc_ptr(cs%basin_mask,isd,ied,jsd,jed) ; cs%basin_mask(:,:) = 1.0
     if (cs%mask_srestore_marginal_seas) then
       call mom_read_data(basin_file,'basin',cs%basin_mask,g%domain, timelevel=1)
       do j=jsd,jed ; do i=isd,ied
         if (cs%basin_mask(i,j) >= 6.0) then ; cs%basin_mask(i,j) = 0.0
         else ; cs%basin_mask(i,j) = 1.0 ; endif
       enddo ; enddo
     endif
     call get_param(param_file, mdl, "MASK_SRESTORE", cs%mask_srestore, &
                  "If true, read a file (salt_restore_mask) containing "//&
                  "a mask for SSS restoring.", default=.false.)
   endif
   if (restore_temp) then
     call get_param(param_file, mdl, "FLUXCONST", cs%Flux_const, &
                  "The constant that relates the restoring surface fluxes "//&
                  "to the relative surface anomalies (akin to a piston "//&
                  "velocity).  Note the non-MKS units.", units="m day-1", &
                  fail_if_missing=.true.)
     call get_param(param_file, mdl, "SST_RESTORE_FILE", cs%temp_restore_file, &
                  "A file in which to find the surface temperature to use for restoring.", &
                  default="temp_restore.nc")
     call get_param(param_file, mdl, "SST_RESTORE_VARIABLE", cs%temp_restore_var_name, &
                  "The name of the surface temperature variable to read from "//&
                  "SST_RESTORE_FILE for restoring sst.", &
                  default="temp")
   ! Convert CS%Flux_const from m day-1 to m s-1.
     cs%Flux_const = cs%Flux_const / 86400.0
     call get_param(param_file, mdl, "MAX_DELTA_TRESTORE", cs%max_delta_trestore, &
                  "The maximum sst difference used in restoring terms.", &
                  units="degC ", default=999.0)
     call get_param(param_file, mdl, "MASK_TRESTORE", cs%mask_trestore, &
                  "If true, read a file (temp_restore_mask) containing "//&
                  "a mask for SST restoring.", default=.false.)
   endif
 ! Optionally read tidal amplitude from input file (m s-1) on model grid.
 ! Otherwise use default tidal amplitude for bottom frictionally-generated
 ! dissipation. Default cd_tides is chosen to yield approx 1 TWatt of
 ! work done against tides globally using OSU tidal amplitude.
   call get_param(param_file, mdl, "CD_TIDES", cs%cd_tides, &
                  "The drag coefficient that applies to the tides.", &
                  units="nondim", default=1.0e-4)
   call get_param(param_file, mdl, "READ_TIDEAMP", cs%read_TIDEAMP, &
                  "If true, read a file (given by TIDEAMP_FILE) containing "//&
                  "the tidal amplitude with INT_TIDE_DISSIPATION.", default=.false.)
   if (cs%read_TIDEAMP) then
     call get_param(param_file, mdl, "TIDEAMP_FILE", tideamp_file, &
                  "The path to the file containing the spatially varying "//&
                  "tidal amplitudes with INT_TIDE_DISSIPATION.", &
                  default="tideamp.nc")
     cs%utide=0.0
   else
     call get_param(param_file, mdl, "UTIDE", cs%utide, &
                  "The constant tidal amplitude used with INT_TIDE_DISSIPATION.", &
                  units="m s-1", default=0.0)
   endif
   call safe_alloc_ptr(cs%TKE_tidal,isd,ied,jsd,jed)
   call safe_alloc_ptr(cs%ustar_tidal,isd,ied,jsd,jed)
   if (cs%read_TIDEAMP) then
     tideamp_file = trim(cs%inputdir) // trim(tideamp_file)
     call mom_read_data(tideamp_file,'tideamp',cs%TKE_tidal,g%domain,timelevel=1)
     do j=jsd, jed; do i=isd, ied
       utide = cs%TKE_tidal(i,j)
       cs%TKE_tidal(i,j) = g%mask2dT(i,j)*cs%Rho0*cs%cd_tides*(utide*utide*utide)
       cs%ustar_tidal(i,j)=sqrt(cs%cd_tides)*utide
     enddo ; enddo
   else
     do j=jsd,jed; do i=isd,ied
       utide=cs%utide
       cs%TKE_tidal(i,j) = cs%Rho0*cs%cd_tides*(utide*utide*utide)
       cs%ustar_tidal(i,j)=sqrt(cs%cd_tides)*utide
     enddo ; enddo
   endif
   call time_interp_external_init
 ! Optionally read a x-y gustiness field in place of a global
 ! constant.
   call get_param(param_file, mdl, "READ_GUST_2D", cs%read_gust_2d, &
                  "If true, use a 2-dimensional gustiness supplied from "//&
                  "an input file", default=.false.)
   call get_param(param_file, mdl, "GUST_CONST", cs%gust_const, &
                "The background gustiness in the winds.", units="Pa", &
                default=0.02)
   if (cs%read_gust_2d) then
     call get_param(param_file, mdl, "GUST_2D_FILE", gust_file, &
                  "The file in which the wind gustiness is found in "//&
                  "variable gustiness.")
     call safe_alloc_ptr(cs%gust,isd,ied,jsd,jed)
     gust_file = trim(cs%inputdir) // trim(gust_file)
     call mom_read_data(gust_file,'gustiness',cs%gust,g%domain, timelevel=1) ! units should be Pa
   endif
 ! See whether sufficiently thick sea ice should be treated as rigid.
   call get_param(param_file, mdl, "USE_RIGID_SEA_ICE", cs%rigid_sea_ice, &
                  "If true, sea-ice is rigid enough to exert a "//&
                  "nonhydrostatic pressure that resist vertical motion.", &
                  default=.false.)
   if (cs%rigid_sea_ice) then
     call get_param(param_file, mdl, "SEA_ICE_MEAN_DENSITY", cs%density_sea_ice, &
                  "A typical density of sea ice, used with the kinematic "//&
                  "viscosity, when USE_RIGID_SEA_ICE is true.", units="kg m-3", &
                  default=900.0)
     call get_param(param_file, mdl, "SEA_ICE_VISCOSITY", cs%Kv_sea_ice, &
                  "The kinematic viscosity of sufficiently thick sea ice "//&
                  "for use in calculating the rigidity of sea ice.", &
                  units="m2 s-1", default=1.0e9)
     call get_param(param_file, mdl, "SEA_ICE_RIGID_MASS", cs%rigid_sea_ice_mass, &
                  "The mass of sea-ice per unit area at which the sea-ice "//&
                  "starts to exhibit rigidity", units="kg m-2", default=1000.0)
   endif
   call get_param(param_file, mdl, "ALLOW_ICEBERG_FLUX_DIAGNOSTICS", iceberg_flux_diags, &
                  "If true, makes available diagnostics of fluxes from icebergs "//&
                  "as seen by MOM6.", default=.false.)
   call register_forcing_type_diags(time, diag, us, cs%use_temperature, cs%handles, &
                                    use_berg_fluxes=iceberg_flux_diags)
   call get_param(param_file, mdl, "ALLOW_FLUX_ADJUSTMENTS", cs%allow_flux_adjustments, &
                  "If true, allows flux adjustments to specified via the "//&
                  "data_table using the component name 'OCN'.", default=.false.)
   if (cs%allow_flux_adjustments) then
     call data_override_init(ocean_domain_in=g%Domain%mpp_domain)
   endif
   if (present(restore_salt)) then ; if (restore_salt) then
     salt_file = trim(cs%inputdir) // trim(cs%salt_restore_file)
     cs%id_srestore = init_external_field(salt_file, cs%salt_restore_var_name, domain=g%Domain%mpp_domain)
     call safe_alloc_ptr(cs%srestore_mask,isd,ied,jsd,jed); cs%srestore_mask(:,:) = 1.0
     if (cs%mask_srestore) then ! read a 2-d file containing a mask for restoring fluxes
       flnam = trim(cs%inputdir) // 'salt_restore_mask.nc'
       call mom_read_data(flnam,'mask', cs%srestore_mask, g%domain, timelevel=1)
     endif
   endif ; endif
   if (present(restore_temp)) then ; if (restore_temp) then
     temp_file = trim(cs%inputdir) // trim(cs%temp_restore_file)
     cs%id_trestore = init_external_field(temp_file, cs%temp_restore_var_name, domain=g%Domain%mpp_domain)
     call safe_alloc_ptr(cs%trestore_mask,isd,ied,jsd,jed); cs%trestore_mask(:,:) = 1.0
     if (cs%mask_trestore) then  ! read a 2-d file containing a mask for restoring fluxes
       flnam = trim(cs%inputdir) // 'temp_restore_mask.nc'
       call mom_read_data(flnam, 'mask', cs%trestore_mask, g%domain, timelevel=1)
     endif
   endif ; endif
   ! Set up any restart fields associated with the forcing.
   call restart_init(param_file, cs%restart_CSp, "MOM_forcing.res")
 !###  call register_ctrl_forcing_restarts(G, param_file, CS%ctrl_forcing_CSp, &
 !###                                      CS%restart_CSp)
   call restart_init_end(cs%restart_CSp)
   if (associated(cs%restart_CSp)) then
     call get_mom_input(dirs=dirs)
     new_sim = .false.
     if ((dirs%input_filename(1:1) == 'n') .and. &
         (len_trim(dirs%input_filename) == 1)) new_sim = .true.
     if (.not.new_sim) then
       call restore_state(dirs%input_filename, dirs%restart_input_dir, time_frc, &
                          g, cs%restart_CSp)
     endif
   endif
 !###  call controlled_forcing_init(Time, G, param_file, diag, CS%ctrl_forcing_CSp)
   call user_revise_forcing_init(param_file, cs%urf_CS)
   call cpu_clock_end(id_clock_forcing)
References mom_get_input::get_mom_input(), id_clock_forcing, mom_error_handler::mom_error(), mom_restart::restart_init_end(), mom_restart::restore_state(), and mom_string_functions::uppercase().
Variable Documentation
id_clock_forcing
integer mom_surface_forcing_mct::id_clock_forcing
Definition at line 193 of file mom_surface_forcing_mct.F90.
 integer :: id_clock_forcing
Referenced by convert_iob_to_fluxes(), convert_iob_to_forces(), and surface_forcing_init().