MOM6: atmos_ocean_fluxes_mod Module Reference
atmos_ocean_fluxes_mod Module Reference
Detailed Description
A dummy version of atmos_ocean_fluxes_mod module for use when the vastly larger FMS package is not needed.
Functions/Subroutines
integer function, public aof_set_coupler_flux (name, flux_type, implementation, atm_tr_index, param, flag, mol_wt, ice_restart_file, ocean_restart_file, units, caller, verbosity)
This subroutine duplicates an interface used by the FMS coupler, but only returns a value of -1. None of the arguments are used for anything.
Function/Subroutine Documentation
aof_set_coupler_flux()
integer function, public atmos_ocean_fluxes_mod::aof_set_coupler_flux (character(len=*), intent(in) name, character(len=*), intent(in) flux_type, character(len=*), intent(in) implementation, integer, intent(in), optional atm_tr_index, real, dimension(:), intent(in), optional param, logical, dimension(:), intent(in), optional flag, real, intent(in), optional mol_wt, character(len=*), intent(in), optional ice_restart_file, character(len=*), intent(in), optional ocean_restart_file, character(len=*), intent(in), optional units, character(len=*), intent(in), optional caller, integer, intent(in), optional verbosity)
This subroutine duplicates an interface used by the FMS coupler, but only returns a value of -1. None of the arguments are used for anything.
Parameters
[in] name An unused argument
[in] flux_type An unused argument
[in] implementation An unused argument
[in] atm_tr_index An unused argument
[in] param An unused argument
[in] flag An unused argument
[in] mol_wt An unused argument
[in] ice_restart_file An unused argument
[in] ocean_restart_file An unused argument
[in] units An unused argument
[in] caller An unused argument
[in] verbosity An unused argument
Definition at line 18 of file atmos_ocean_fluxes.F90.
   character(len=*),                intent(in) :: name !< An unused argument
   character(len=*),                intent(in) :: flux_type !< An unused argument
   character(len=*),                intent(in) :: implementation !< An unused argument
   integer,               optional, intent(in) :: atm_tr_index !< An unused argument
   real,    dimension(:), optional, intent(in) :: param !< An unused argument
   logical, dimension(:), optional, intent(in) :: flag !< An unused argument
   real,                  optional, intent(in) :: mol_wt !< An unused argument
   character(len=*),      optional, intent(in) :: ice_restart_file !< An unused argument
   character(len=*),      optional, intent(in) :: ocean_restart_file !< An unused argument
   character(len=*),      optional, intent(in) :: units !< An unused argument
   character(len=*),      optional, intent(in) :: caller !< An unused argument
   integer,               optional, intent(in) :: verbosity !< An unused argument
   ! None of these arguments are used for anything.
   integer :: coupler_index
   coupler_index = -1
Referenced by mom_ocmip2_cfc::flux_init_ocmip2_cfc(), advection_test_tracer::register_advection_test_tracer(), boundary_impulse_tracer::register_boundary_impulse_tracer(), dome_tracer::register_dome_tracer(), regional_dyes::register_dye_tracer(), dyed_obc_tracer::register_dyed_obc_tracer(), ideal_age_example::register_ideal_age_tracer(), isomip_tracer::register_isomip_tracer(), oil_tracer::register_oil_tracer(), and user_tracer_example::user_register_tracer_example().