MOM6: mom_unit_scaling Module Reference
mom_unit_scaling Module Reference
Detailed Description
Provides a transparent unit rescaling type to facilitate dimensional consistency testing.
Data Types
type unit_scale_type
Describes various unit conversion factors.
Functions/Subroutines
subroutine, public unit_scaling_init (param_file, US)
Allocates and initializes the ocean model unit scaling type.
subroutine, public fix_restart_unit_scaling (US)
Set the unit scaling factors for output to restart files to the unit scaling factors for this run.
subroutine, public unit_scaling_end (US)
Deallocates a unit scaling structure.
Function/Subroutine Documentation
fix_restart_unit_scaling()
subroutine, public mom_unit_scaling::fix_restart_unit_scaling (type(unit_scale_type), intent(inout) US)
Set the unit scaling factors for output to restart files to the unit scaling factors for this run.
Parameters
[in,out] us A dimensional unit scaling type
Definition at line 109 of file MOM_unit_scaling.F90.
   type(unit_scale_type), intent(inout) :: US !< A dimensional unit scaling type
   us%m_to_Z_restart = us%m_to_Z
   us%m_to_L_restart = us%m_to_L
   us%s_to_T_restart = us%s_to_T
Referenced by mom::finish_mom_initialization(), and mom_ice_shelf::initialize_ice_shelf().
unit_scaling_end()
subroutine, public mom_unit_scaling::unit_scaling_end (type(unit_scale_type), pointer US)
Deallocates a unit scaling structure.
Parameters
us A dimensional unit scaling type
Definition at line 119 of file MOM_unit_scaling.F90.
   type(unit_scale_type), pointer :: US !< A dimensional unit scaling type
   deallocate( us )
Referenced by mom::mom_end().
unit_scaling_init()
subroutine, public mom_unit_scaling::unit_scaling_init (type(param_file_type), intent(in) param_file, type(unit_scale_type), pointer US)
Allocates and initializes the ocean model unit scaling type.
Parameters
[in] param_file Parameter file handle/type
us A dimensional unit scaling type
Definition at line 41 of file MOM_unit_scaling.F90.
   type(param_file_type), intent(in) :: param_file !< Parameter file handle/type
   type(unit_scale_type), pointer    :: US         !< A dimensional unit scaling type
   ! This routine initializes a unit_scale_type structure (US).
   ! Local variables
   integer :: Z_power, L_power, T_power
   real    :: Z_rescale_factor, L_rescale_factor, T_rescale_factor
   ! This include declares and sets the variable "version".
 # include "version_variable.h"
   character(len=16) :: mdl = "MOM_unit_scaling"
   if (associated(us)) call mom_error(fatal, &
      'unit_scaling_init: called with an associated US pointer.')
   allocate(us)
   ! Read all relevant parameters and write them to the model log.
   call log_version(param_file, mdl, version, &
                    "Parameters for doing unit scaling of variables.")
   call get_param(param_file, mdl, "Z_RESCALE_POWER", z_power, &
                  "An integer power of 2 that is used to rescale the model's "//&
                  "intenal units of depths and heights.  Valid values range from -300 to 300.", &
                  units="nondim", default=0, debuggingparam=.true.)
   call get_param(param_file, mdl, "L_RESCALE_POWER", l_power, &
                  "An integer power of 2 that is used to rescale the model's "//&
                  "intenal units of lateral distances.  Valid values range from -300 to 300.", &
                  units="nondim", default=0, debuggingparam=.true.)
   call get_param(param_file, mdl, "T_RESCALE_POWER", t_power, &
                  "An integer power of 2 that is used to rescale the model's "//&
                  "intenal units of time.  Valid values range from -300 to 300.", &
                  units="nondim", default=0, debuggingparam=.true.)
   if (abs(z_power) > 300) call mom_error(fatal, "unit_scaling_init: "//&
                  "Z_RESCALE_POWER is outside of the valid range of -300 to 300.")
   if (abs(l_power) > 300) call mom_error(fatal, "unit_scaling_init: "//&
                  "L_RESCALE_POWER is outside of the valid range of -300 to 300.")
   if (abs(t_power) > 300) call mom_error(fatal, "unit_scaling_init: "//&
                  "T_RESCALE_POWER is outside of the valid range of -300 to 300.")
   z_rescale_factor = 1.0
   if (z_power /= 0) z_rescale_factor = 2.0**z_power
   us%Z_to_m = 1.0 * z_rescale_factor
   us%m_to_Z = 1.0 / z_rescale_factor
   l_rescale_factor = 1.0
   if (l_power /= 0) l_rescale_factor = 2.0**l_power
   us%L_to_m = 1.0 * l_rescale_factor
   us%m_to_L = 1.0 / l_rescale_factor
   t_rescale_factor = 1.0
   if (t_power /= 0) t_rescale_factor = 2.0**t_power
   us%T_to_s = 1.0 * t_rescale_factor
   us%s_to_T = 1.0 / t_rescale_factor
   ! These are useful combinations of the fundamental scale conversion factors set above.
   us%Z_to_L = us%Z_to_m * us%m_to_L
   us%L_to_Z = us%L_to_m * us%m_to_Z
   us%L_T_to_m_s = us%L_to_m * us%s_to_T
   us%m_s_to_L_T = us%m_to_L * us%T_to_s
   us%L_T2_to_m_s2 = us%L_to_m * us%s_to_T**2
   ! It does not look like US%m_s2_to_L_T2 would be used, so it does not exist.
   us%Z2_T_to_m2_s = us%Z_to_m**2 * us%s_to_T
   us%m2_s_to_Z2_T = us%m_to_Z**2 * us%T_to_s
References mom_error_handler::mom_error().
Referenced by mom_oda_driver_mod::init_oda(), and mom_ice_shelf::initialize_ice_shelf().