MOM6: coord_hycom Module Reference
coord_hycom Module Reference
Detailed Description
Regrid columns for the HyCOM coordinate.
Data Types
type hycom_cs
Control structure containing required parameters for the HyCOM coordinate.
Functions/Subroutines
subroutine, public init_coord_hycom (CS, nk, coordinateResolution, target_density, interp_CS)
Initialise a hycom_CS with pointers to parameters.
subroutine, public end_coord_hycom (CS)
This subroutine deallocates memory in the control structure for the coord_hycom module.
subroutine, public set_hycom_params (CS, max_interface_depths, max_layer_thickness, interp_CS)
This subroutine can be used to set the parameters for the coord_hycom module.
subroutine, public build_hycom1_column (CS, eqn_of_state, nz, depth, h, T, S, p_col, z_col, z_col_new, zScale, h_neglect, h_neglect_edge)
Build a HyCOM coordinate column.
Function/Subroutine Documentation
build_hycom1_column()
subroutine, public coord_hycom::build_hycom1_column (type(hycom_cs), intent(in) CS, type(eos_type), pointer eqn_of_state, integer, intent(in) nz, real, intent(in) depth, real, dimension(nz), intent(in) h, real, dimension(nz), intent(in) T, real, dimension(nz), intent(in) S, real, dimension(nz), intent(in) p_col, real, dimension(nz+1), intent(in) z_col, real, dimension(cs%nk+1), intent(inout) z_col_new, real, intent(in), optional zScale, real, intent(in), optional h_neglect, real, intent(in), optional h_neglect_edge)
Build a HyCOM coordinate column.
Parameters
[in] cs Coordinate control structure
eqn_of_state Equation of state structure
[in] nz Number of levels
[in] depth Depth of ocean bottom (positive [H ~> m or kg m-2])
[in] t Temperature of column [degC]
[in] s Salinity of column [ppt]
[in] h Layer thicknesses, in [m] or [H ~> m or kg m-2]
[in] p_col Layer pressure [Pa]
[in] z_col Interface positions relative to the surface [H ~> m or kg m-2]
[in,out] z_col_new Absolute positions of interfaces
[in] zscale Scaling factor from the input thicknesses in [m] to desired units for zInterface, perhaps m_to_H.
[in] h_neglect A negligibly small width for the purpose of cell reconstructions in the same units as h.
[in] h_neglect_edge A negligibly small width for the purpose of edge value calculations in the same units as h0.
Definition at line 99 of file coord_hycom.F90.
   type(hycom_CS),        intent(in)    :: CS !< Coordinate control structure
   type(EOS_type),        pointer       :: eqn_of_state !< Equation of state structure
   integer,               intent(in)    :: nz !< Number of levels
   real,                  intent(in)    :: depth !< Depth of ocean bottom (positive [H ~> m or kg m-2])
   real, dimension(nz),   intent(in)    :: T !< Temperature of column [degC]
   real, dimension(nz),   intent(in)    :: S !< Salinity of column [ppt]
   real, dimension(nz),   intent(in)    :: h  !< Layer thicknesses, in [m] or [H ~> m or kg m-2]
   real, dimension(nz),   intent(in)    :: p_col !< Layer pressure [Pa]
   real, dimension(nz+1), intent(in)    :: z_col !< Interface positions relative to the surface [H ~> m or kg m-2]
   real, dimension(CS%nk+1), intent(inout) :: z_col_new !< Absolute positions of interfaces
   real, optional,        intent(in)    :: zScale !< Scaling factor from the input thicknesses in [m]
                                                  !! to desired units for zInterface, perhaps m_to_H.
   real,        optional, intent(in)    :: h_neglect !< A negligibly small width for the
                                              !! purpose of cell reconstructions
                                              !! in the same units as h.
   real,        optional, intent(in)    :: h_neglect_edge !< A negligibly small width
                                              !! for the purpose of edge value calculations
                                              !! in the same units as h0.
   ! Local variables
   integer   :: k
   real, dimension(nz) :: rho_col ! Layer quantities
   real, dimension(CS%nk) :: h_col_new ! New layer thicknesses
   real :: z_scale
   real :: stretching ! z* stretching, converts z* to z.
   real :: nominal_z ! Nominal depth of interface when using z* [Z ~> m]
   real :: hNew
   logical :: maximum_depths_set ! If true, the maximum depths of interface have been set.
   logical :: maximum_h_set      ! If true, the maximum layer thicknesses have been set.
   maximum_depths_set = allocated(cs%max_interface_depths)
   maximum_h_set = allocated(cs%max_layer_thickness)
   z_scale = 1.0 ; if (present(zscale)) z_scale = zscale
   ! Work bottom recording potential density
   call calculate_density(t, s, p_col, rho_col, 1, nz, eqn_of_state)
   ! This ensures the potential density profile is monotonic
   ! although not necessarily single valued.
   do k = nz-1, 1, -1
     rho_col(k) = min( rho_col(k), rho_col(k+1) )
   enddo
   ! Interpolates for the target interface position with the rho_col profile
   ! Based on global density profile, interpolate to generate a new grid
   call build_and_interpolate_grid(cs%interp_CS, rho_col, nz, h(:), z_col, &
            cs%target_density, cs%nk, h_col_new, z_col_new, h_neglect, h_neglect_edge)
   ! Sweep down the interfaces and make sure that the interface is at least
   ! as deep as a nominal target z* grid
   nominal_z = 0.
   stretching = z_col(nz+1) / depth ! Stretches z* to z
   do k = 2, cs%nk+1
     nominal_z = nominal_z + (z_scale * cs%coordinateResolution(k-1)) * stretching
     z_col_new(k) = max( z_col_new(k), nominal_z )
     z_col_new(k) = min( z_col_new(k), z_col(nz+1) )
   enddo
   if (maximum_depths_set .and. maximum_h_set) then ; do k=2,cs%nk
     ! The loop bounds are 2 & nz so the top and bottom interfaces do not move.
     ! Recall that z_col_new is positive downward.
     z_col_new(k) = min(z_col_new(k), cs%max_interface_depths(k), &
                        z_col_new(k-1) + cs%max_layer_thickness(k-1))
   enddo ; elseif (maximum_depths_set) then ; do k=2,cs%nk
     z_col_new(k) = min(z_col_new(k), cs%max_interface_depths(k))
   enddo ; elseif (maximum_h_set) then ; do k=2,cs%nk
     z_col_new(k) = min(z_col_new(k), z_col_new(k-1) + cs%max_layer_thickness(k-1))
   enddo ; endif
References regrid_interp::build_and_interpolate_grid().
Referenced by mom_regridding::build_grid_hycom1().
end_coord_hycom()
subroutine, public coord_hycom::end_coord_hycom (type(hycom_cs), pointer CS)
This subroutine deallocates memory in the control structure for the coord_hycom module.
Parameters
cs Coordinate control structure
Definition at line 59 of file coord_hycom.F90.
   type(hycom_CS), pointer :: CS !< Coordinate control structure
   ! nothing to do
   if (.not. associated(cs)) return
   deallocate(cs%coordinateResolution)
   deallocate(cs%target_density)
   if (allocated(cs%max_interface_depths)) deallocate(cs%max_interface_depths)
   if (allocated(cs%max_layer_thickness)) deallocate(cs%max_layer_thickness)
   deallocate(cs)
Referenced by mom_regridding::end_regridding().
init_coord_hycom()
subroutine, public coord_hycom::init_coord_hycom (type(hycom_cs), pointer CS, integer, intent(in) nk, real, dimension(nk), intent(in) coordinateResolution, real, dimension(nk+1), intent(in) target_density, type(interp_cs_type), intent(in) interp_CS)
Initialise a hycom_CS with pointers to parameters.
Parameters
cs Unassociated pointer to hold the control structure
[in] nk Number of layers in generated grid
[in] coordinateresolution Nominal near-surface resolution [m]
[in] target_density Interface target densities [kg m-3]
[in] interp_cs Controls for interpolation
Definition at line 40 of file coord_hycom.F90.
   type(hycom_CS),       pointer    :: CS !< Unassociated pointer to hold the control structure
   integer,              intent(in) :: nk !< Number of layers in generated grid
   real, dimension(nk),  intent(in) :: coordinateResolution !< Nominal near-surface resolution [m]
   real, dimension(nk+1),intent(in) :: target_density !< Interface target densities [kg m-3]
   type(interp_CS_type), intent(in) :: interp_CS !< Controls for interpolation
   if (associated(cs)) call mom_error(fatal, "init_coord_hycom: CS already associated!")
   allocate(cs)
   allocate(cs%coordinateResolution(nk))
   allocate(cs%target_density(nk+1))
   cs%nk                      = nk
   cs%coordinateResolution(:) = coordinateresolution(:)
   cs%target_density(:)       = target_density(:)
   cs%interp_CS               = interp_cs
References mom_error_handler::mom_error().
Referenced by mom_regridding::initcoord().
set_hycom_params()
subroutine, public coord_hycom::set_hycom_params (type(hycom_cs), pointer CS, real, dimension(:), intent(in), optional max_interface_depths, real, dimension(:), intent(in), optional max_layer_thickness, type(interp_cs_type), intent(in), optional interp_CS)
This subroutine can be used to set the parameters for the coord_hycom module.
Parameters
cs Coordinate control structure
[in] max_interface_depths Maximum depths of interfaces in m
[in] max_layer_thickness Maximum thicknesses of layers in m
[in] interp_cs Controls for interpolation
Definition at line 72 of file coord_hycom.F90.
   type(hycom_CS),                 pointer    :: CS !< Coordinate control structure
   real, dimension(:),   optional, intent(in) :: max_interface_depths !< Maximum depths of interfaces in m
   real, dimension(:),   optional, intent(in) :: max_layer_thickness  !< Maximum thicknesses of layers in m
   type(interp_CS_type), optional, intent(in) :: interp_CS !< Controls for interpolation
   if (.not. associated(cs)) call mom_error(fatal, "set_hycom_params: CS not associated")
   if (present(max_interface_depths)) then
     if (size(max_interface_depths) /= cs%nk+1) &
       call mom_error(fatal, "set_hycom_params: max_interface_depths inconsistent size")
     allocate(cs%max_interface_depths(cs%nk+1))
     cs%max_interface_depths(:) = max_interface_depths(:)
   endif
   if (present(max_layer_thickness)) then
     if (size(max_layer_thickness) /= cs%nk) &
       call mom_error(fatal, "set_hycom_params: max_layer_thickness inconsistent size")
     allocate(cs%max_layer_thickness(cs%nk))
     cs%max_layer_thickness(:) = max_layer_thickness(:)
   endif
   if (present(interp_cs)) cs%interp_CS = interp_cs
References mom_error_handler::mom_error().
Referenced by mom_regridding::set_regrid_max_depths(), mom_regridding::set_regrid_max_thickness(), and mom_regridding::set_regrid_params().